src/poky:pango: Make it build with ptest disabled
This avoids the following error:

  ERROR: pango-1.50.11-r0 do_package: QA Issue: pango: Files/directories
  were installed but not shipped in any package:
    /usr/libexec
    /usr/libexec/installed-tests
    /usr/libexec/installed-tests/pango
    /usr/libexec/installed-tests/pango/nofonts
    /usr/libexec/installed-tests/pango/nofonts/fonts.conf

Also use tabs for indentation of shell code.

(From OE-Core rev: 0a449acddca1ba9022c9ffd8af0d9ac5ad2c4e4c)

Signed-off-by: Peter Kjellerstedt <peter.kjellerstedtaxis.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit d4bcd4050a6a9b6b1cb8e68b2053523cc0501814)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>