src/meta-openembedded:python-pyflame: Disable for mips arch
Fails to build as support is missing

src/ptrace.cc:135:48: error: 'regs' has incomplete type

Signed-off-by: Khem Raj <raj.khemgmail.com>