src/meta-openembedded:python3-py: add python3-netclient to RDEPENDS
python3-py requires the uuid.py module, which is contained in
python3-netclient. Without it:

rootqemux86-64:~# python3

>>> import py._path.local
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.8/site-packages/py/_path/local.py", line 7, in <module>
import sys, os, atexit, io, uuid
ModuleNotFoundError: No module named 'uuid'

Signed-off-by: Trevor Gamblin <trevor.gamblinwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>