src/meta-openembedded:tnftp: Add missing header stdc-predef.h
musl highlights this problem

Fixes
| ../../tnftp-20210827/libedit/chartype.h:47:3: error: wchar_t must store ISO 10646 characters
|         #error wchar_t must store ISO 10646 characters                                             |          ^
| 1 error generated.

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Yi Zhao <yi.zhaowindriver.com>