src/meta-openembedded:umip: move to meta-networking
ERROR: Nothing PROVIDES 'radvd' (but /home/akuster/oss/maint/meta-openembedded/meta-oe/recipes-connectivity/umip/umip_1.0.bb DEPENDS on or otherwise requires it)

Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>