src/meta-openembedded:python3-pybind11: Restore strip prevention patch
The patch which removed the pybind11_strip() call from provisioned
pybind11*Tools.cmake files was dropped in commit
5c455804aede17e0ea0cbb7ab55f8580f912e664 ("python3-pybind11: Upgrade
to 2.10.3").

However this change delegated the requirement to set CMAKE_BUILD_TYPE
as 'Debug' or 'RelWithDebInfo' (or as unset) to the cmake utilizing
packages which have build time dependency on python3-pybind11, failure
to do which causes following kind of BitBake failure with Yocto:

  ERROR: foobar-1.0.0-r0 do_package: QA Issue: File '/usr/lib/python3.11/site-packages/foobar.so' from foobar was already stripped, this will prevent future debugging! [already-stripped]

Restore the patch so that the stripping is delegated to Yocto once
more, allowing depending cmake packages to work out of the box also
when they use 'Release' or 'MinSizeRel' as CMAKE_BUILD_TYPE by
default.

Signed-off-by: Joonas Salonpää <joonas.salonpaavaisala.com>
Signed-off-by: Niko Mauno <niko.maunovaisala.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>