src/meta-openembedded:python3-pylint: upgrade 2.17.3 -> 2.17.4
This upgrade fixes most of the ptest errors that have been seen with
pylint, which were caused by a tomlkit issue. Changelog (see also
https://github.com/pylint-dev/pylint/releases/tag/v2.17.4):

False Positives Fixed

- Fix a false positive for bad-dunder-name when there is a
user-defined __index__ method. Closes #8613

Other Bug Fixes

- pyreverse: added escaping of vertical bar character in annotation
labels produced by DOT printer to ensure it is not treated as field
separator of record-based nodes. Closes #8603

- Fixed a crash when generating a configuration file:
tomlkit.exceptions.TOMLKitError: Can't add a table to a dotted key
caused by tomlkit v0.11.8. Closes #8632

Signed-off-by: Trevor Gamblin <tgamblinbaylibre.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>