src/meta-openembedded:switchtec-user: fix installed-vs-shipped with multilib
* fixes:
  ERROR: QA Issue: switchtec-user: Files/directories were installed but not shipped in any package:
    /usr/lib/libswitchtec.a
    /usr/lib/libswitchtec.so
    /usr/lib/libswitchtec.so.4.0
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  switchtec-user: 3 installed and not shipped files. [installed-vs-shipped]

  when libdir is e.g. /usr/lib64

  The Makefile.in defines default LIBDIR with DESTDIR:
  LIBDIR ?= $(DESTDIR)$(PREFIX)/lib
  so include ${D} here as well

* use 4 spaces for indentation and ' instead of " so that it doesn't
  need backslashes

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>