src/poky:ffmpeg: refresh patches to apply cleanly
* the last patch added in:
  https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=874b72fe259cd3a23f4613fccfe2e9cc3f79cd6a
  doesn't apply cleanly.

* fixes:
  ERROR: ffmpeg-5.0.1-r0 do_patch: Fuzz detected:

  Applying patch 0001-avcodec-vp3-Add-missing-check-for-av_malloc.patch
  patching file libavcodec/vp3.c
  Hunk #1 succeeded at 2677 with fuzz 1 (offset -2 lines).

(From OE-Core rev: 6060dec1fc9d215f6b2ff9d6571bac802ac6a09b)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>