src/meta-openembedded:libfaketime: simplify packaging
* avoid dev-so QA issue

* avoid separate package for the library, because the current "lib${PN}"
  has a bit ridiculous name in mulilib builds:
  lib32-liblib32-libfaketime

* fixes:
  ERROR: lib32-libfaketime-0.9.10-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package lib32-liblib32-libfaketime contains symlink .so '/usr/lib32/faketime/libfaketime.so' [dev-so]

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>