src/meta-virtualization:packagegroup-kubernets: add seccomp to REQUIRED_DISTRO_FEATURES
* fixes world build:
ERROR: Nothing RPROVIDES 'k3s-server' (but meta-virtualization/recipes-core/packagegroups/packagegroup-kubernetes.bb RDEPENDS on or otherwise requires it)
k3s RPROVIDES k3s-server but was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'k3s-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['k3s-server']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-kubernetes', 'k3s-server']

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>