src/meta-openembedded:leveldb: prevent installing gtest
* Causes conflicts when leveldb is used in component which itself also depends
  on gtest e.g. leveldb-tl in meta-webosose:

  ERROR: lib32-leveldb-tl-0.1.6-r4 do_prepare_recipe_sysroot: The file
  /usr/lib/pkgconfig/gtest.pc is installed by both lib32-googletest and
  lib32-leveldb, aborting

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>