src/meta-openembedded:libmcrypt: fix multilib conflict
It fails to install libmcrypt-dev and lib32-libmcrypt-dev at same time:

Error: Transaction test error:
  file /usr/bin/libmcrypt-config conflicts between attempted installs of
  libmcrypt-dev-2.5.8-r0.core2_64 and lib32-libmcrypt-dev-2.5.8-r0.i586

Use MULTILIB_SCRIPTS from multilib_script.bbclass to handle them.

Signed-off-by: Kai Kang <kai.kangwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>