src/meta-openembedded:gvfs: backport patch to build with gphoto 2.5 api
With the update of gphoto to a version with the 2.5 API gvfs do_compile
failes with:
gvfs-1.10.1/daemon/gvfsbackendgphoto2.c:1648:35: error: request for member 'name' in something not a structure or union
|    DEBUG ("  '%s' '%s' '%s'",  info.name, info.path, info.library_filename);
and others.

This backports the upstream fix.

Signed-off-by: Max Krummenacher <max.oss.09gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>