src/meta-openembedded:geary: add opengl to REQUIRED_DISTRO_FEATURES
Fixes:
  ERROR: Nothing PROVIDES 'evolution-data-server' (but /build/layers/meta-openembedded/meta-gnome/recipes-connectivity/geary/geary_43.0.bb DEPENDS on or otherwise requires it)
evolution-data-server was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'geary', 'evolution-data-server']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>