src/meta-amd:core-image-sato: add the x11 feature to fix build dependence error
When build the core-image-sato, it will throw out the follow error:
ERROR: Nothing RPROVIDES 'packagegroup-core-x11-base' (but "./meta/recipes-sato
/images/core-image-sato.bb" RDEPENDS on or otherwise requires it)

So add the x11 feature to fix this build error.

Signed-off-by: Baogen Shang <baogen.shangwindriver.com>