src/meta-openembedded:gtkwave: set REQUIRED_DISTRO_FEATURES only to wayland
* after the migration to gtk3 in:
  https://git.openembedded.org/meta-openembedded/commit/?id=8221db74e300619d002e2b385d12a5fe13e8999a
  this was now failing with:

| In file included from ../../gtkwave-gtk3-3.3.109/src/debug.h:17,
|                  from ../../gtkwave-gtk3-3.3.109/src/vlist.h:18,
|                  from ../../gtkwave-gtk3-3.3.109/src/analyzer.h:18,
|                  from ../../gtkwave-gtk3-3.3.109/src/symbol.h:20,
|                  from ../../gtkwave-gtk3-3.3.109/src/vcd.h:32,
|                  from ../../gtkwave-gtk3-3.3.109/src/ae2.h:16,
|                  from ../../gtkwave-gtk3-3.3.109/src/globals.h:27,
|                  from ../../gtkwave-gtk3-3.3.109/src/timeentry.c:11:
| ../../gtkwave-gtk3-3.3.109/src/gtk23compat.h:12:10: fatal error: gdk/gdkwayland.h: No such file or directory
|    12 | #include <gdk/gdkwayland.h>
|       |          ^~~~~~~~~~~~~~~~~~

  for distributions without wayland in DISTRO_FEATURES.

* because https://github.com/gtkwave/gtkwave/blob/f9d82a82aa3ddc30ca47984278371f62c9a3bd81/gtkwave3-gtk3/src/gtk23compat.h#L10
  explicitly includes gdk/gdkwayland.h for gtk-3.22.26 and newer (oe-core currently has 3.24.29)

* restrict REQUIRED_DISTRO_FEATURES to wayland _and_ x11
  (instead of either of them through ANY_OF_DISTRO_FEATURES and GTK3DISTROFEATURES)
  because wayland is needed for gtk3 to provide this gdkwayland.h
  and x11 is needed by tk dependency

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>