src/meta-openembedded:gtksourceview5: add opengl to REQUIRED_DISTRO_FEATURES
Fixes:
  ERROR: Nothing PROVIDES 'gtk4' (but /build/layers/meta-openembedded/meta-gnome/recipes-gnome/gtksourceview/gtksourceview5_5.4.2.bb DEPENDS on or otherwise requires it)
  gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gtksourceview5', 'gtk4']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>