src/meta-openembedded:driverctl: fix installed-vs-shipped
* introduced in upgrade to 0.115 version:
  https://git.openembedded.org/meta-openembedded/commit/?id=1f2c2ebcbcf5944225462f530e0d56b20f1b4630

* fixes:
ERROR: driverctl-0.115-r0 do_package: QA Issue: driverctl: Files/directories were installed but not shipped in any package:
  /usr/lib/systemd
  /usr/lib/systemd/system
  /usr/lib/systemd/system/driverctl@.service
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
driverctl: 3 installed and not shipped files. [installed-vs-shipped]

  when systemd_system_unitdir isn't subdirectory of libdir, e.g. with multilib using:
  export libdir="/usr/lib64"
  export systemd_system_unitdir="/usr/lib/systemd/system"

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>