src/meta-openembedded:vdpauinfo: require x11 in DISTRO_FEATURES
It depends on libvdpau and libvdpau has:
inherit features_check
REQUIRED_DISTRO_FEATURES = "x11"

since:
commit 0055684612edddae0f041e984c8497c5e5b32e74
Author: Armin Kuster <akuster808gmail.com>
Date:   Tue Mar 6 17:27:30 2018 -0800
Subject: libvdpau: only include when x11 in DISTRO_FEATURES

the same restriction should be repeated here to avoid:
ERROR: Nothing PROVIDES 'libvdpau' (but meta-oe/meta-oe/recipes-graphics/vdpau/vdpauinfo_1.5.bb DEPENDS on or otherwise requires it)
libvdpau was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Also add it to packagegroup-meta-oe and fix libvdpau there.

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>