src/poky:llvm: fix typo in CVE-2024-0151.patch
During backporting the patch, accidentally a variable was removed.
In case the recipe is compiled for 32-bit Arm target, compilation
fails with the following error:

3.0.1-r0/git/llvm/lib/Target/ARM/ARMISelLowering.cpp:4481:13: error: 'RegVT' was not declared in this scope
|  4481 |         if (RegVT == MVT::f16 || RegVT == MVT::bf16)
|       |             ^~~~~

This patch corrects the patch, and adds back the removed RegVT variable.

(From OE-Core rev: 77f29f8fea58de40459186952d25279877ce4994)

Signed-off-by: Gyorgy Sarvari <skandigraungmail.com>
Signed-off-by: Steve Sakoman <stevesakoman.com>