src/meta-openembedded:mysql-python: fix compilation with MariaDB 10.3.13
Use standard API function MYSQL_OPT_RECONNECT
instead of direct modification of internal structures
which does not work for MariaDB to fix below compile
issue.
| _mysql.c: In function '_mysql_ConnectionObject_ping':
| _mysql.c:2005:41: error: 'MYSQL' {aka 'struct st_mysql'} has no member named 'reconnect'

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>