src/meta-openembedded:libsmi: use update-alternatives to solve conflicts with frr
Error: Transaction test error:
  file /usr/share/yang/ietf-netconf-acm.yang conflicts between attempted installs of libsmi-yang-0.5.0-r0.aarch64 and frr-10.0-r0.aarch64
  file /usr/share/yang/ietf-netconf-with-defaults.yang conflicts between attempted installs of libsmi-yang-0.5.0-r0.aarch64 and frr-10.0-r0.aarch64
  file /usr/share/yang/ietf-netconf.yang conflicts between attempted installs of libsmi-yang-0.5.0-r0.aarch64 and frr-10.0-r0.aarch64

frr also uses the doc 'ietf-netconf-acm.yang ietf-netconf-with-defaults.yang ietf-netconf.yang'.
frr has a priority of 100.

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>