src/meta-virtualization:go-cross: add relocation fix to 1.4 for new binutils.
Add relocation fix as documented in contained commit log, so that we
can build with newer binutils, as per the ones we get via the self
hosted builder and things like build-appliance.

Fixes:

| go-native/1.4.3-r0/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
| go-native/1.4.3-r0/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
| runtime/cgo(.text): unexpected relocation type 298
| runtime/cgo(.text): unexpected relocation type 298
| # cmd/go
| go-native/1.4.3-r0/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
| go-native/1.4.3-r0/go/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
| runtime/cgo(.text): unexpected relocation type 298
| runtime/cgo(.text): unexpected relocation type 298
| WARNING: go-native/1.4.3-r0/temp/run.do_compile.30243:1 exit 2 from './make.bash --host-only'
| ERROR: Function failed: do_compile (log file is located at go-native/1.4.3-r0/temp/log.do_compile.30243)
ERROR: Task 6 (meta-virtualization/recipes-devtools/go-cross/go-native_1.4.bb, do_compile) failed with exit code '1'

Signed-off-by: Paul Gortmaker <paul.gortmakerwindriver.com>