src/meta-raspberrypi:userland: Add wayland support for libbrcmEGL
These renames are recently added
https://github.com/raspberrypi/userland/commit/dd98890106c3c6145f640c4cfb825be937282a93

Some packages e.g. libSDL2 has started using the new names
and are resulting in undefined symbols e.g.

| /mnt/a/oe/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-gnueabi/libsdl2-mixer/2.0.2-r0/recipe-sysroot/usr/lib/libb
rcmEGL.so: undefined reference to `wl_resource_post_error'

Signed-off-by: Khem Raj <raj.khemgmail.com>