src/meta-openembedded:python-mock: add RDEPENDS on python-pbr and python-funcsigs
python-pbr and python-funcsigs are required by python-mock,
or it fails with:

>>> import mock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 69, in <module>
    from pbr.version import VersionInfo
ImportError: No module named pbr.version

>>> import mock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 80, in <module>
    import funcsigs
ImportError: No module named funcsigs

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>