src/poky:attr: Fix build failure when image includes man-pages pkg
If you attempt to build an image with both attr(-doc) and man-pages
packages your rootfs might fail to assemble. The error will be
something like:

Error: Transaction check error:
  file /usr/share/man/man2/fgetxattr.2 from install of \
    attr-doc-2.4.47-r0.core2_64 conflicts with file from \
    package man-pages-4.11-r0.core2_64

(the error is usually only seen on builders which don't have manpages
installed, if you have /usr/share/man/man1/man.1.gz your build will
complete but you will have duplicate manpages, just one zipped and one
not)

Backporting changes from upstream attr removes the conflicted files in
favour of those in the man-pages package.

(From OE-Core rev: 5e6595ef42807c8d2a100da3d9862152daf68d3d)

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>