src/meta-openembedded:daq: move recipe to meta-networking
ERROR: Nothing PROVIDES 'libdnet' (but /home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-connectivity/daq/daq_2.0.2.bb DEPENDS on or otherwise requires it). Close matches:
 libnet
 libnewt
 libidn
ERROR: Required build target 'daq' has no buildable providers.
Missing or unbuildable dependency chain was: ['daq', 'libdnet']

world build fails for meta-oe.

move daq to meta-networking where snort and libdnet both reside.

Signed-off-by: Armin Kuster <akuster808gmail.com>