src/meta-openembedded:fontforge: add back gnulib to DEPENDS
commit 00ec8bc10df539ecedc3beb2dde28a8e4665cad8
Author: Paul Gortmaker <paul.gortmakerwindriver.com>
Date:   Sun May 8 15:08:12 2016 -0400

    autotools-bootstrap: make bootstrap package specific.

removed this dependency causing:

ERROR: fontforge-20150824-r0 do_configure: Function failed: do_configure (log file is located at /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-angstrom-linux-gnueabi/fontforge/20150824-r0/temp/log.do_configure.26234)
ERROR: Logfile of failure stored in: /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-angstrom-linux-gnueabi/fontforge/20150824-r0/temp/log.do_configure.26234
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_copy_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: Executing shell function do_configure
| cp: cannot stat '/home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi2/usr/share/gnulib': No such file or directory
| WARNING: /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-angstrom-linux-gnueabi/fontforge/20150824-r0/temp/run.do_configure.26234:1 exit 1 from 'cp -rf /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi2/usr/share/gnulib /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-angstrom-linux-gnueabi/fontforge/20150824-r0/git'
| ERROR: Function failed: do_configure (log file is located at /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-angstrom-linux-gnueabi/fontforge/20150824-r0/temp/log.do_configure.26234)

Signed-off-by: Andreas Müller <schnitzeltonygooglemail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>