src/meta-openembedded:ufs-tool: Do not force static linking
build forced static linking if it detect cross-compilation, static
linking with glibc does not work in all circumstances, e.g. when using
clang, glibc expects libgcc to be linked in to provide unwinding, which
may not be the case, ideally the symbols should be looked up independent
of libraries linked in but thats not the case

fixes

| /mnt/a/yoe/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/ufs-tool/1.3+gitAUTOINC+8b00e33003-r0/recipe-sysroot-native/usr/bin/arm-yoe-linux-gnueabi/arm-yoe-linux-gnueabi-ld: /mnt/a/yoe/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/ufs-tool/1.3+gitAUTOINC+8b00e33003-r0/recipe-sysroot/usr/lib//arm-yoe-linux-gnueabi/9.2.0/../../../lib/libpthread.a(unwind.o): in function `__pthread_unwind':
| /usr/src/debug/glibc/2.30-r0/git/nptl/unwind.c:121: undefined reference to `_Unwind_ForcedUnwind'
| clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
| make: *** [Makefile:40: ufs-tool] Error 1

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Denys Dmytriyenko <denysti.com>