src/meta-openembedded:python3-pyzmq: Add missing dep on python3-unixadmin for ptests
Fixes
ImportError while importing test module '/usr/lib/python3-pyzmq/ptest/tests/test_ssh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ssh.py:1: in <module>
    from zmq.ssh.tunnel import select_random_ports
../../python3.12/site-packages/zmq/ssh/__init__.py:1: in <module>
    from zmq.ssh.tunnel import *
../../python3.12/site-packages/zmq/ssh/tunnel.py:18: in <module>
    from getpass import getpass, getuser
E   ModuleNotFoundError: No module named 'getpass'
ERROR: tests/test_ssh.py:tests/test_ssh.py

Signed-off-by: Khem Raj <raj.khemgmail.com>