src/poky:qemu: Add qemu-user-* and qemu-system-* to PACKAGES_DYNAMIC
Fixes:
  Add below line to conf/local.conf
  IMAGE_INSTALL:append = " qemu-system-aarch64"
  $ bitbake core-image-base
  ERROR: Required build target 'core-image-base' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-base', 'qemu-system-aarch64']

(From OE-Core rev: b89201b7c163b075880a35733700c6d4205b4461)

(From OE-Core rev: 3514a3bc6c86c56ee3b23edccbfa566d7a3e4ac5)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>