src/meta-openembedded:linpack: fix build with gcc-15.0.1
* fix following error:
    linpacknew.c: In function 'dgefa':
    linpacknew.c:257:9: error: conflicting types for 'idamax'; have 'int(void)'
    257 |     int idamax(),j,k,kp1,l,nm1;
        |         ^~~~~~
    linpacknew.c:63:13: note: previous declaration of 'idamax' with type 'int(int,  REAL *, int)' {aka 'int(int,  double *, int)'}
    63 | static int  idamax   (int n,REAL *dx,int incx);
        |             ^~~~~~
    linpacknew.c:272:21: error: too many arguments to function 'idamax'; expected 0, have 3
    272 |                 l = idamax(n-k,&a[lda*k+k],1) + k;
        |                     ^~~~~~ ~~~
    linpacknew.c:257:9: note: declared here
    257 |     int idamax(),j,k,kp1,l,nm1;
        |         ^~~~~~
    linpacknew.c:326:21: error: too many arguments to function 'idamax'; expected 0, have 3
    326 |                 l = idamax(n-k,&a[lda*k+k],1) + k;
        |                     ^~~~~~ ~~~
    linpacknew.c:257:9: note: declared here
    257 |     int idamax(),j,k,kp1,l,nm1;
        |         ^~~~~~

    The function was already declared as static int idamax(int n, REAL *dx, int incx);
    on line 63, but it was redeclared as int idamax() inside the dgefa function on line 257,
    causing a conflict.
    where functions are redeclared without parameters,
    causing conflicts with the original function definitions.

Signed-off-by: mark.yang <mark.yanglge.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>