src/meta-openembedded:bubblewrap: fix error with gcc-15
* backport fix from:
  https://github.com/containers/bubblewrap/pull/660
  But patch rework for this version.
  In gcc 15, bool became a reserved keyword in C23, causing conflicts with our custom bool definition.

  See also, https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

* to fix:
  http://errors.yoctoproject.org/Errors/Details/851183/
  ../bubblewrap-0.10.0/utils.h:46:13: error: 'bool' cannot be defined via 'typedef'
   46 | typedef int bool;
      |             ^~~~

Signed-off-by: mark.yang <mark.yanglge.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>