src/poky:bitbake: server/xmlrpc: Fix after currentAsyncCommand locking changes
After changes in bitbake b5215887d2f8ea3f28f1ebda721bd5b8f93ec7f3,
"process/cooker/command: Fix currentAsyncCommand locking/races", command.py
assumes it has access to the process server but the xmlrpc backend was
passing in the xmlrpc server object leading to errors like:

xmlrpc.client.Fault: <Fault 1: "<class 'AttributeError'>:'BitBakeXMLRPCServer' object has no attribute 'set_async_cmd'">

Fixing to pass the process server to command.py resolves this issue.

[YOCTO #15008]

(Bitbake rev: ce5b65d5fada474ef21ac28440af6ad45287650a)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>