src/meta-openembedded:samba: add PACKAGECONFIG for valgrind
* Add configure options '--without-valgrind'
* Disable valgrind by default since it doesn't build for all targets

This fixes build errors:

  ../source3/include/includes.h:156:31: fatal error: \
    valgrind/memcheck.h: No such file or directory
  compilation terminated.

Signed-off-by: Wenzong Fan <wenzong.fanwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>