src/poky:toaster.bbclass: Fix ValueError
Running "bitbake xxx:do_unpack" resulted in exception at the
BuildCompleted event from toaster.

The reason for this exception was usage of ':' as a field
delimiter in toasterstatlist file. As target can optionally
contain ':<task>' suffix it caused split(':') to throw exception:

File "toaster_collect_task_stats(e)", line 71, in
toaster_collect_task_stats(e=<bb.event.BuildCompleted object at
0x7f8434deed50>)
ValueError: too many values to unpack

Fixed by changing delimiter ':' -> '::'

(From OE-Core rev: 03d01393d14b7b20dcb40ff89b1628883fd3b545)

Signed-off-by: Ed Bartosh <ed.bartoshlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>