src/poky:perf: Fix QA error due to most recent kernel
A change in the latest kernel (next), triggers a QA error due to a
missing RDEPENDS on perl for perf-tests.

ERROR: QA Issue: /usr/libexec/perf-core/tests/shell/common/check_no_patterns_found.pl contained in package perf-tests requires /usr/bin/perl, but no providers found in RDEPENDS:perf-tests? [file-rdeps]

(From OE-Core rev: a85e8eb558acbfd77fe83ad150f3dab2f240b094)

Signed-off-by: Ryan Eatmon <reatmonti.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>