src/meta-openembedded:thin-provisioning-tools: use STAGING_LIBDIR_NATIVE variable for LIBCLANG_PATH
* hardcoding:
  ${WORKDIR}/recipe-sysroot-native${libdir}
  is just wrong when there is a better variable

* This path won't be correct for multilib builds where target ${libdir}
  might be e.g. /usr/lib32 while native libdir is /usr/lib.

* use STAGING_LIBDIR_NATIVE variable which uses correct ${libdir_native}

* fixes:
  error: failed to run custom build command for `devicemapper-sys v0.3.0`

  Caused by:
    process didn't exit successfully: `lib32-thin-provisioning-tools/1.1.0/build/target/release/build/devicemapper-sys-88de590bc55acb43/build-script-build` (exit status: 101)
    --- stderr
    thread 'main' panicked at lib32-thin-provisioning-tools/1.1.0/sources-unpack/cargo_home/bitbake/bindgen-0.69.4/lib.rs:622:31:
    Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>