src/poky:devtool: fix update-recipe dry-run mode
When running devtool update-recipe with --mode=srcrev AND --append switch
in dry-run, we get the following error:

  Traceback (most recent call last):
  [...]
  Exception: destpath should be set here

Fix this by removing a misplaced else statement in _update_recipe_srcrev

(From OE-Core rev: edfa2aac5c39e12e1149134a6241ad4e5b2ebc46)

Signed-off-by: Julien Stephan <jstephanbaylibre.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
(cherry picked from commit 85ba125703d5b442133fd7c470b915460ee68ac9)
Signed-off-by: Steve Sakoman <stevesakoman.com>