src/meta-raspberrypi:drbd: Disable for rpi machines
Its enabled in linux-raspberrypi modules in defconfig
so we can ignore external driver for now, fixes

ERROR: linux-raspberrypi-1_4.19.58+gitAUTOINC+d5dc848c98-r0 do_packagedata_setscene: The recipe linux-raspberrypi is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /mnt/a/yoe/build/tmp/pkgdata/raspberrypi3-64/runtime/kernel-module-drbd-4.19.58.packaged
    (matched in manifest-raspberrypi3_64-drbd.packagedata)
  /mnt/a/yoe/build/tmp/pkgdata/raspberrypi3-64/runtime/kernel-module-drbd-4.19.58
    (matched in manifest-raspberrypi3_64-drbd.packagedata)
Please verify which recipe should provide the above files.

Signed-off-by: Khem Raj <raj.khemgmail.com>