src/meta-openembedded:rp-pppoe: Fix rootfs creation errors
error: file /usr/share/doc/README from install of rp-pppoe-doc-3.11-*
conflicts with file from package dmidecode-doc-2.12*

Signed-off-by: Li Xin <lixin.fnstcn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>