src/poky:python3: skip tests requiring tools-sdk
Conditionally skip test_ctypes.test_find unless
IMAGE_FEATURES contains 'tools-sdk' as these test
cases require full packagegroup-core-buildessential

Fixes:
  AssertionError: Failed ptests:
  {'python3': ['test_find_library_with_gcc', 'test_find_library_with_ld']}

(From OE-Core rev: 70e2fc066a18c35e42610d75eeaa1edd9aab7cf2)

(From OE-Core rev: c6567235cba55f50ca77d5db848c887232f3670c)

Signed-off-by: Tim Orling <timothy.t.orlingintel.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>