src/meta-openembedded:gperftools: Use ARM ISA when using clang
It seemingly needs to be fixed in application, chromium also force ARM
ISA for internal gperftools

also see https://bugs.llvm.org/show_bug.cgi?id=31058

Fixes errors like below

| ../git/src/base/atomicops-internals-arm-v6plus.h:228:8: error: instruction requires: arm-mode
|       "ldrexd  %1, [%3]\n"
|        ^

Signed-off-by: Khem Raj <raj.khemgmail.com>