src/poky:pixman: fixing inline failure with -Og
When debug build is enabled(-Og is used), pixman-native do_compile
failed with error:
In function ‘combine_inner’,
    inlined from ‘combine_soft_light_ca_float’ at ../pixman-0.42.2/pixman/pixman-combine-float.c:655:1:
../pixman-0.42.2/pixman/pixman-combine-float.c:370:5: error: inlining failed in call to ‘always_inline’ ‘combine_soft_light_c’: function not considered for inlining
  370 |     combine_ ## name ## _c (float sa, float s, float da, float d)

Refer [1], always_inline is not suggested to use with indirect function
call, replace always_inline with __inline__ to fix the issue

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107931

(From OE-Core rev: 6cd503c5e84bf8090b840c69c7569ae1a46528d0)

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Steve Sakoman <stevesakoman.com>