src/meta-intel:intel-oneapi-dpcpp-cpp-runtime: install missing common headers
Download dev-utilities package to have common headers available too.

fatal error: 'dpc_common.hpp' file not found

Signed-off-by: Naveen Saini <naveen.kumar.sainiintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>