src/meta-openembedded:nodejs: add extra RDEPENDS for building
If you want to perform an "npm install" and a module needs to be compiled,
these additional packages need to be on the target otherwise the compile might
fail with one or more of the following error messages:

	ImportError: No module named compiler.ast
	ImportError: No module named filecmp
	ImportError: No module named multiprocessing

Signed-off-by: Trevor Woerner <twoernergmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>