src/poky:dbus: upgrade to 1.12.2
1. os-test.patch is removed because current dbus has removed
   distro specific init script.

2. Add autoconf-archive to DEPENDS to fix do_configure failure as below.
     error: Unexpanded AX_ macro found.

3. Modify FILES variable to fix installed-vs-shipped QA issue.

(From OE-Core rev: 3e1e783f0e18f7be1527280f39b3c74f048e24e6)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>