src/poky:oe-selftest: devtool: run without poky
If DISTRO is set to poky, the ptest DISTRO_FEATURE is enable. However,
without meta-poky layer, ptest packages are not compiled and the tests
fail with:
   ERROR: Nothing RPROVIDES 'cmake-example-ptest'...

(From OE-Core rev: 7b5b0908a6acf43384a13f2e6801e014a61b8e8f)

Signed-off-by: Adrian Freihofer <adrian.freihofersiemens.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>