src/meta-openembedded:openipmi: fix do_configure error when using dash
We encountered a do_configure error when using dash on Ubuntu 20.04:
conftest.c:31:26: fatal error: Python.h: No such file or directory
   31 |                 #include <Python.h>
      |                          ^~~~~~~~~~

It seems that PYTHON_CPPFLAGS is not passed to configure command
correctly. Use configuration option --with-pythoncflags instead of
passing it in cmdline.

Signed-off-by: Yi Zhao <yi.zhaowindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>