src/meta-openembedded:ssiapi: Disable for ppc64
Internal boost headers are missing ppc64 support
ssiapi.1.3.0/lib/boost/smart_ptr/detail/sp_counted_base.hpp:66:11: fatal error: boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp: No such file or directory

Signed-off-by: Khem Raj <raj.khemgmail.com>