src/meta-openembedded:mpv: remove explicit LICENSE_FLAGS
This flag does not describe the mpv package, but ffmpeg instead.
It gets in the way of using finer-grained LICENSE_FLAGS in ffmpeg.

It is above all not needed, the real problem is even more clear without it:

 ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted i  LICENSE_FLAGS_WHITELIST
 ERROR: Required build target 'mpv' has no buildable providers.
 Missing or unbuildable dependency chain was: ['mpv', 'ffmpeg']

Signed-off-by: Yann Dirson <yannblade-group.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>