src/poky:send-error-report: Fix dubious error reporting
Currently this code prints things like:

ERROR: OK

which is unhelpful at best. After this change it would print:

ERROR: HTTP Error 500

which at least gives us something to work on.

(From OE-Core rev: 06079240e4eb0a3e1f528f6c8d6f3ea20754afee)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>