src/poky:busybox.inc: install rcS, rcK and rcS.default only with busybox in VIRTUAL-RUNTIME_init_manager
* since
  https://git.openembedded.org/openembedded-core/commit/?id=991394be9e695f9ddb5e2fca167c06f7a56a7449
  the rcS.default is in SRC_URI only when VIRTUAL-RUNTIME_init_manager is 'busybox'
  but this section in do_install was controlled by
  CONFIG_INIT=y in /.config which for busybox-initrd from meta-virtualization
  caused:

  ERROR: busybox-initrd-1.32.0-r0 do_install: Execution of '/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/busybox-initrd/1.32.0-r0/temp/run.do_install.1481880' failed with exit code 1:
  CONFIG_FEATURE_MDEV_CONF=y
  install: cannot stat '/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/busybox-initrd/1.32.0-r0/rcS.default': No such file or directory
  WARNING: exit code 1 from a shell command.

(From OE-Core rev: 00f22daa9774783ba14073fb871bbbc6e7c5354d)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>