src/meta-openembedded:packagegroup-efl-sdk: exclude packagegroup-core-sdk dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* packagegroup-core-sdk is MACHINE_ARCH since:
  commit 66ff089603618dc9b22532509bf39274bf6adf67
  Author: Dan McGregor <dan.mcgregorusask.ca>
  Date:   Wed Dec 10 20:14:57 2014 -0600
  packagegroup-core-sdk: add gcc-sanitizers to core SDK
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: packagegroup-efl-sdk different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['efledbus_1.7.9.bb.do_packagedata', 'eflefl_1.15.1.bb.do_packagedata', 'eflelementary_1.15.1.bb.do_packagedata', 'lttnglttng-ust_git.bb.do_packagedata', 'luajitluajit_2.0.4.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'packagegroupspackagegroup-core-sdk.bb.do_packagedata', 'packagegroupspackagegroup-efl-sdk.bb.do_package', 'packagegroupspackagegroup-efl-sdk.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'valgrindvalgrind_3.10.1.bb.do_packagedata']
to
['efledbus_1.7.9.bb.do_packagedata', 'eflefl_1.15.1.bb.do_packagedata', 'eflelementary_1.15.1.bb.do_packagedata', 'lttnglttng-ust_git.bb.do_packagedata', 'luajitluajit_2.0.4.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'packagegroupspackagegroup-core-sdk.bb.do_packagedata', 'packagegroupspackagegroup-efl-sdk.bb.do_package', 'packagegroupspackagegroup-efl-sdk.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'valgrindvalgrind_3.10.1.bb.do_packagedata']
openembedded-core/meta/recipes-core/packagegroups/packagegroup-core-sdk.bb.do_packagedata with hash 34ab468f4471fb07663ce2952ad545b5
 changed to
openembedded-core/meta/recipes-core/packagegroups/packagegroup-core-sdk.bb.do_packagedata with hash 0a589cc6975e9a4d4fdbdc63bc76b84f
Hash for dependent task packagegroupspackagegroup-core-sdk.bb.do_packagedata changed from 34ab468f4471fb07663ce2952ad545b5 to 0a589cc6975e9a4d4fdbdc63bc76b84f

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>