src/meta-openembedded:libplacebo: fix glslang PACKAGECONFIG
In case glslang PACKAGECONFIG is enabled, compilation fails with
a lot of errors about undefined references from the glslang namespace, e.g.

| /usr/src/debug/libplacebo/7.349.0/src/glsl/glslang.cc:79:(.text+0x160): undefined reference to `glslang::TShader::TShader(EShLanguage)'

This has been solved in the upstream project, and this change backports
the commit that fixes the meson.build file to find the correct libraries
during compilation.

Additionally, fix also the TMPDIR QA error that popped up after fixing
the above issue: remove the RECIPE_SYSROOT value from the generated
pkgconf file (and instead of referring to the libraries by absolute path,
just refer to them by name, as they are supposed to be present in the
standard library lookup path).

Signed-off-by: Gyorgy Sarvari <skandigraungmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>