src/meta-openembedded:upower: add REQUIRED_DISTRO_FEATURES for polkit
After below commits to add polkit as a required
distro feature:
97a1a55 polkit: add polkit as a required distro feature
c049e02 polkit: inherit distro_features_check

Need to add REQUIRED_DISTRO_FEATURES for polkit to
fix below error for these packages which depend on
polkit:
$ bitbake upower
ERROR: Nothing PROVIDES 'polkit' (but /build/layers/meta-openembedded/meta-oe/recipes-support/upower/upower_0.99.7.bb DEPENDS on or otherwise requires it)

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>