src/meta-virtualization:ceph: Add the missing Upstream-Status Field
Fixes:
  INFO: Traceback (most recent call last):
    File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
      self.assertEqual(len(patches), 0 , \
  AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
/build/layers/meta-virtualization/recipes-extended/ceph/ceph/0001-delete-install-layout-deb.patch

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>