src/meta-openembedded:packagegroup-meta-oe: fix build issues
ERROR: Required build target 'meta-oe-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-oe-image', 'packagegroup-meta-oe', 'freeglut']

ERROR: Required build target 'meta-oe-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-oe-image', 'packagegroup-meta-oe', 'libsdl2-ttf']

ERROR: Required build target 'meta-oe-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-oe-image', 'packagegroup-meta-oe', 'libmad']

ERROR: Required build target 'meta-oe-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-oe-image', 'packagegroup-meta-oe', 'faad2']

ERROR: Required build target 'meta-oe-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-oe-image', 'packagegroup-meta-oe', 'mpv']

Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>