src/meta-openembedded:python-singledispatch: initial recipe for version 3.4.0.3
This package backports functools.singledispatch from Python 3.4 to earlier
Python versions.

It is being added as one of the two missing backport modules that Tornado 4.3
needs in order to prevent tornado/gen.py from bombing on import errors when
running on python2 rather than python3.4

  ImportError: No module named singledispatch

Signed-off-by: S. Lockwood-Childs <sjlvctlabs.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>