src/meta-openembedded:xorgxrdp: add distro_features_check for x11
* fixes: following errors in every world build:
  ERROR: Nothing PROVIDES 'xrdp' (but meta-oe/recipes-support/xorg-xrdp/xorgxrdp_0.2.5.bb DEPENDS on or otherwise requires it)
  xrdp was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'xorgxrdp', 'xrdp']

  ERROR: Nothing PROVIDES 'virtual/libx11' (but meta-oe/recipes-support/xorg-xrdp/xorgxrdp_0.2.5.bb DEPENDS on or otherwise requires it)
  libx11-diet PROVIDES virtual/libx11 but was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
  libx11 PROVIDES virtual/libx11 but was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'xorgxrdp', 'virtual/libx11']

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>