src/poky:bluez5: Correct support for building without systemd
This avoids the following error when the systemd DISTRO_FEATURE is
enabled, but the systemd PACKAGECONFIG is not:

  ERROR: bluez5-5.46-r0 do_package: SYSTEMD_SERVICE_bluez5 value
  bluetooth.service does not exist

(From OE-Core rev: a751a1f4ab0625cbfedb6445b0da080fc455848f)

Signed-off-by: Peter Kjellerstedt <peter.kjellerstedtaxis.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>