src/meta-tensorflow:tensorflow: drop Upstream-Status inside third_party .patch files
* these patches create:
  third_party/0001-XNNPACK-support-32-bit-x86.patch
  third_party/0001-cpuinfo-support-32-bit-x86.patch
  third_party/0001-hardcode-go-SDKS.patch
  third_party/eigen3/0001-workaround-ice-failure-while-building-from-source-wi.patch

  which aren't applied by do_patch bitbake task but by bazel:

  tensorflow $ grep patch_file tensorflow/workspace2.bzl | head -n 2
  tensorflow/workspace2.bzl: patch_file = ["//third_party:0001-XNNPACK-support-32-bit-x86.patch"],
  tensorflow/workspace2.bzl: patch_file = ["//third_party:0001-cpuinfo-support-32-bit-x86.patch"],
  tensorflow/workspace2.bzl: patch_file = ["//third_party:0001-hardcode-go-SDKS.patch"],
  third_party/eigen3/workspace.bzl: patch_file = ["//third_party/eigen3:0001-workaround-ice-failure-while-building-from-source-wi.patch"],

  so they don't really need Upstream-Status and including it there
  might cause false possitive e.g. in
  0001-fix-XNNPACK-build-failure-for-qemuarm.patch

  ERROR: tensorflow-lite-2.10.0-r0 do_patch: QA Issue: Malformed Upstream-Status in patch
  recipes-framework/tensorflow/tensorflow-lite/0001-fix-XNNPACK-build-failure-for-qemuarm.patch
  Please correct according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status :
   Upstream-Status: Inappropriate [oe specific] [patch-status]
  ERROR: tensorflow-lite-2.10.0-r0 do_patch: Fatal QA errors were found, failing task.

  caused by extra space before Upstream-Status

  Maybe we should drop 0001-fix-XNNPACK-build-failure-for-qemuarm.patch completely
  as it was already dropped from tensorflow in:
  https://git.yoctoproject.org/meta-tensorflow/commit/?h=mickledore&id=baae9cd6d92f69aa16b874958a332e1d3a362fea
  and from tensorflow-lite in scarthgap branch:
  https://git.yoctoproject.org/meta-tensorflow/commit/?h=scarthgap&id=29509c97e9009ed0ae99ce6c2554e463575dc10c

  and is now used only for tensorflow-lite, refresh it to apply

  It was originally introduced for both in:
  https://git.yoctoproject.org/meta-tensorflow/commit/?h=mickledore&id=e0efac349f2aac3d65ccbeee20475dbb1ea3dd19
  and refreshed in:
  https://git.yoctoproject.org/meta-tensorflow/commit/?h=mickledore&id=30fbec74ea37b646473b08d0ee8d3992ccd56245

Signed-off-by: Martin Jansa <martin.jansagmail.com>