src/meta-openembedded:xdotool: pass correct libdir to make
When MACHINE=qemux86-64 and enable multilib:
ERROR: QA Issue: xdotool: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/libxdo.so
  /usr/lib/libxdo.so.1
  /usr/lib/.debug
  /usr/lib/.debug/libxdo.so.1
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install. [installed-vs-shipped]

Pass the correct libdir to make, otherwise it assumes $prefix/lib even
on multilib.

Signed-off-by: Yi Zhao <yi.zhaowindriver.com>