src/meta-openembedded:snort3: fix snort.pc
* fixes:
  ERROR: lib32-snort3-3+git-r0 do_populate_sysroot: QA Issue: snort.pc failed sanity test (tmpdir) in path lib32-snort3/3+git/sysroot-destdir/usr/lib/pkg

* it's broken for non-multilib builds as well, the issue is that
  FLEX_CPPFLAGS points to native include dir, e.g.
  FLEX_CPPFLAGS=-I/OE/../lib32-snort3/3+git/recipe-sysroot-native/usr/include
  and the work around from:
  https://github.com/openembedded/meta-openembedded/commit/973647848049abda6f2adbee0189720109863731
  sed -i "s#${RECIPE_SYSROOT}##g" ${D}${libdir}/pkgconfig/snort.pc
  strips the "/OE/../lib32-snort3/3+git/recipe-sysroot" part in non-multilib
  case, but leaves:
  FLEX_CPPFLAGS=-I-native/usr/include
  which is still wrong, but not detected by buildpaths QA check anymore
  and in multilib case, this didn't strip the first part because the
  target sysroot is:
  "/OE/../lib32-snort3/3+git/lib32-recipe-sysroot"
  so it didn't strip anything from native sysroot:
  "/OE/../lib32-snort3/3+git/recipe-sysroot-native"

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>