src/meta-openembedded:netkit-rusers: Add dep on rpcsvc-proto for rpc headers
needs rpcsvc/rstat.h which is no longer in libc but provided
by separate package now

Fixes
up.c:51:10: fatal error: rstat.h: No such file or directory
   51 | #include "rstat.h"
      |          ^~~~~~~~~
compilation terminated.

Signed-off-by: Khem Raj <raj.khemgmail.com>