src/poky:python3-numpy: upgrade to 1.24.2
* remove patch applied upstream

* FWIW: this version still fails to build with DEBUG_BUILD AND gcc-13 as
  shown in:
  http://errors.yoctoproject.org/Errors/Details/689841/

In file included from TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/13.0.1/include/immintrin.h:57,
                 from TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/numpy-1.24.1/numpy/distutils/checks/cpu_avx512_knl.c:14:
In function '_mm512_mask_prefetch_i64scatter_pd',
    inlined from 'main' at TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/numpy-1.24.1/numpy/distutils/checks/cpu_avx512_knl.c:23:5:
TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/13.0.1/include/avx512pfintrin.h:180:3: error: 'base' may be used uninitialized [-Werror=maybe-uninitialized]
  180 |   __builtin_ia32_scatterpfqpd (__mask, (__v8di) __index, __addr, __scale,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  181 |                                __hint);
      |                                ~~~~~~~
<built-in>: In function 'main':
<built-in>: note: by argument 3 of type 'const void *' to '__builtin_ia32_scatterpfqpd' declared here
TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/numpy-1.24.1/numpy/distutils/checks/cpu_avx512_knl.c:18:9: note: 'base' declared here
   18 |     int base[128];
      |         ^~~~

In file included from TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/13.0.1/include/immintrin.h:53,
                 from numpy/core/src/umath/simd.inc.src:25:
TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/13.0.1/include/avx512fintrin.h: In function 'AVX512F_square_CFLOAT':
TOPDIR/tmp-glibc/work/core2-64-oe-linux/python3-numpy/1.24.1-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/13.0.1/include/avx512fintrin.h:314:1: error: inlining failed in call to 'always_inline' '_mm512_setzero_ps': target specific option mismatch
  314 | _mm512_setzero_ps (void)
      | ^~~~~~~~~~~~~~~~~
numpy/core/src/umath/simd.inc.src:977:20: note: called from here
  977 |     vtype@ zeros = _mm512_setzero_vsuffix@();
      |                    ^~~~~~~~~~~~~~~~~~~
numpy/core/src/umath/simd.inc.src:596:1: error: inlining failed in call to 'always_inline' 'avx512_get_full_load_mask_ps': target specific option mismatch
  596 | avx512_get_full_load_mask_ps(void)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

It will be probably resolved in next release from 1.25 as whole simd.inc.src was removed in:
https://github.com/numpy/numpy/commit/640e85017aa8eac3e9be68b475acf27d623b16b7
but this PR https://github.com/numpy/numpy/pull/21056 wasn't backported
to maintenance/1.24.x and probably isn't worth backporting now as
neither DEBUG_BUILD is enabled by default nor gcc-13 merged in oe-core,
and the changes don't backport cleanly.

(From OE-Core rev: 8596678667797971559aed962b1c204266032186)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>