src/meta-openembedded:cmocka: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/share/cmocka/example/mock/libproc_uptime.so conflicts between attempted installs of lib32-libcmocka-examples-1.1.7+git0+a01cc69ee9-r0.armv7ahf_neon and libcmocka-examples-1.1.7+git0+a01cc69ee9-r0.cortexa57

Change install directory from share to lib to resolve conflict.

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>