src/meta-openembedded:jasper: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/include/jasper/jas_config.h conflicts between attempted installs of lib32-jasper-dev-4.1.1-r0.armv7ahf_neon and jasper-dev-4.1.1-r0.cortexa57

The differences between the two files are as follows:
@@ -44,10 +44,10 @@
 /* #undef JAS_HAVE_INT128_T */

 #define JAS_SIZEOF_INT 4
-#define JAS_SIZEOF_LONG 4
+#define JAS_SIZEOF_LONG 8
 #define JAS_SIZEOF_LLONG 8
-#define JAS_SIZEOF_SIZE_T 4
-#define JAS_SIZEOF_SSIZE_T 4
+#define JAS_SIZEOF_SIZE_T 8
+#define JAS_SIZEOF_SSIZE_T 8

 #define JAS_HAVE_FCNTL_H
 /* #undef JAS_HAVE_IO_H */

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>