src/poky:systemtap_git: update to newer version to fix a build issue
This build issue was observed with the 2.4+git version of the systemtap.

.../x86_64-linux/systemtap-native/2.4+gitAUTOINC+9190b3acfe-r0/git/tapsets.cxx: In function 'void validate_module_elf(Dwfl_Module*, const char*, base_query*)':
.../x86_64-linux/systemtap-native/2.4+gitAUTOINC+9190b3acfe-r0/git/tapsets.cxx:1998:10: error: 'EM_AARCH64' was not declared in this scope
.../x86_64-linux/systemtap-native/2.4+gitAUTOINC+9190b3acfe-r0/git/tapsets.cxx: In constructor 'sdt_uprobe_var_expanding_visitor::sdt_uprobe_var_expanding_visitor(systemtap_session&, int, const string&, const string&, const string&, stap_sdt_probe_type, const string&, int)':
.../x86_64-linux/systemtap-native/2.4+gitAUTOINC+9190b3acfe-r0/git/tapsets.cxx:5613:31: error: 'EM_AARCH64' was not declared in this scope

This is a known issue, and it is already fixed in the upstream tree.

Updating the recipe to get the commit which fixes the issue.

(From OE-Core rev: 5170f58f4a46edead40d98f302ba3294e078c113)

Signed-off-by: Nitin A Kamble <nitin.a.kambleintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>