src/poky:libdnf: Fix arm arch mapping issues for qemuarmv5
qemuarmv5 currently fails with:

$ dnf --help
Error: Incorrect or unknown "arch": armv5hl

Fix this by removing the code in libdnf which is trying to be too
clever, we don't need this mappings given the way OE configures rpm.

(From OE-Core rev: 7d620c754c92da9dcc56a0a7ec9f3355c2ba733e)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>