src/poky:binutils: package static libs from gprofng
* fixes:
  ERROR: binutils-2.40-r0 do_package: QA Issue: binutils: Files/directories were installed but not shipped in any package:
    /usr/lib/gprofng/libgp-collectorAPI.a
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  binutils: 1 installed and not shipped files. [installed-vs-shipped]

(From OE-Core rev: ab6ae4b715143364288ba164f8ab5c3cd7f486ae)

(From OE-Core rev: 4ed0f0cc0ecc290f1bbb8262afa62b45513e9cc6)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit f72fd51e0da100e7ed90992225688bf43e2a69b6)
Signed-off-by: Steve Sakoman <stevesakoman.com>