src/poky:man-pages: remove conflict pages
Remove the pages which libxcrypt and shadow already have to avoid
following conflicts during install man-pages and libxcrypt/shadow at the
same time.

Error: Transaction test error:
  file /usr/share/man/man3/crypt.3 from install of
  libcrypt-doc-4.4.33-r0.x86_64 conflicts with file from package
  man-pages-6.04-r0.x86_64

(From OE-Core rev: fbc8f5381e8e1da0d06f7f8e5b8c63a49b1858c2)

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit 605b4a91dc44d33bd4742841e71645275bc039e8)
Signed-off-by: Jonas Gorski <jonas.gorskibisdn.de>
Signed-off-by: Steve Sakoman <stevesakoman.com>