src/meta-openembedded:libnet: Fix install conflict when enable multilib.
Error: Transaction test error:
file /usr/bin/libnet-config conflicts between attempted installs of libnet-dev-1.2-r0.aarch64 and lib32-libnet-dev-1.2-r0.armv7ahf_neon

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>