src/poky:oescripts.py: avoid error when cairo module is not available
When running 'oe-selftest -r oescripts', the following error appeared.

    cls.skipTest('Python module cairo is not present')
    TypeError: skipTest() missing 1 required positional argument: 'reason'

This is because the host does not have the cairo python module installed.
Fix this problem by using unittest's SkipTest exception.

(From OE-Core rev: 785bb108ceb9dc137ec8d75d887b6a3869cbfb9c)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>