src/meta-cloud-services:python-nova: add missing rdepends
Add the missing rdepends on python-oslo.log, python-psutil
and python-amqp or it fails with:

  File "/usr/lib64/python2.7/site-packages/nova/cmd/compute.py", line 23, in <module>
    from oslo_log import log as logging
  ImportError: No module named oslo_log

  File "/usr/lib64/python2.7/site-packages/nova/openstack/common/report/generators/process.py", line 23, in <module>
    import psutil
  ImportError: No module named psutil

  File "/usr/lib64/python2.7/site-packages/stevedore/driver.py", line 50, in _default_on_load_failure
    raise err
  ImportError: No module named amqp

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>