src/meta-security:suricata: drop pkg_postinst_ontarget systemd init
/var/log/suricata initialization is handled by
systemd-tmpfiles-setup.service, which occurs before services like
suricata

Work towards resolving:
ERROR: [...] do_rootfs: The following packages could not be configured
offline and rootfs is read-only: ['100-suricata']

Added in commit 36d656fe7244 ("suricata: add tmpfiles.d config")

systemd testing:

rootbeaglebone-yocto:~# ls -d /var/log/suricata
/var/log/suricata

rootbeaglebone-yocto:~# systemctl enable suricata
Created symlink '/etc/systemd/system/multi-user.target.wants/suricata.service' -> '/usr/lib/systemd/system/suricata.service'.

rootbeaglebone-yocto:~# rmdir /var/log/suricata

rootbeaglebone-yocto:~# reboot now

rootbeaglebone-yocto:~# ls -d /var/log/suricata
/var/log/suricata

rootbeaglebone-yocto:~# journalctl -o short-iso-precise -u systemd-tmpfiles-setup -u suricata
2025-05-20T00:45:46.450027+00:00 beaglebone-yocto systemd[1]: Starting Create System Files and Directories...
[...]
2025-05-20T00:45:47.041049+00:00 beaglebone-yocto systemd[1]: Finished Create System Files and Directories.
2025-05-20T00:45:47.542976+00:00 beaglebone-yocto systemd[1]: Started Suricata IDS/IDP daemon.
[...]

Signed-off-by: Clayton Casciato <majortomtosourcecontrolgmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>