src/poky:bitbake.conf: use http:// for GNU_MIRROR instead of ftp://
The past few weeks ftp://ftp.gnu.org has been intermittently giving errors like this:

WARNING: Failed to fetch URL ftp://ftp.gnu.org/gnu/emacs/emacs-23.4.tar.gz;name=tarball, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, output:
Cannot parse PASV response.
accept: Connection timed out
Cannot parse PASV response.
Error in server response, closing control connection.

Which is annoying because binutils lives there. Using http://ftp.gnu.org hasn't given any problems so far.

(From OE-Core rev: 25fe8d95298a457e828190412d7148470edc5592)

Signed-off-by: Koen Kooi <koen.kooilinaro.org>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>