src/poky:qt4-4.8.7: fix build for mips n32
Issue: LIN8-1720

If _ABIN32 is defined, it should go into 32 bit branch.

Fixed:
./wtf/StdLibExtras.h: In instantiation of 'TO WTF::bitwise_cast(FROM) [with TO = int; FROM = double]':
runtime/JSValueInlineMethods.h:495:44:   required from here
./wtf/Assertions.h:326:47: error: size of array is negative
 #define COMPILE_ASSERT(exp, name) typedef int dummy##name [(exp) ? 1 : -1]

(LOCAL REV: NOT UPSTREAM) -- Sent to oe-core on 20151127

(From OE-Core rev: 12c3982f4845929c0d0a1324cff4edbfb4cf59a7)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>