src/meta-cgl:pacemaker: add missing header file
 mainloop.c:406:8: error: unknown type name 'qb_array_t'
|  static qb_array_t *gio_map = NULL;

Signed-off-by: Armin Kuster <akustermvista.com>
Signed-off-by: Adrian Dudau <adrian.dudauenea.com>