src/meta-openembedded:gyp: fix for compatibility with Python 3.10 (part 2)
The patch for python 3.10 compatibility was missing an update to
'import' line.

Fixes the following problem encountered making use of gyp:

|   File "[...]/usr/lib/python3.10/site-packages/gyp/common.py", line 497, in <module>
|     class OrderedSet(collections.abc.MutableSet):
| AttributeError: module 'collections' has no attribute 'abc'

Signed-off-by: S. Lockwood-Childs <sjlvctlabs.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>