src/meta-openembedded:python3-colorama: add native and nativesdk to BBCLASSEXTEND
* python3-cmd2 depends on colorama since the first version in:
  commit dc66ca8495eb051e1e6de5333e36f7f8054094a1
  Author: Zheng Ruoqin <zhengrq.fnstcn.fujitsu.com>
  Date:   Mon Sep 2 13:22:08 2019 +0800

    python-cmd2: Add python3 version

    Providing a python3 version of python-cmd2.

  has both BBCLASSEXTENDs since:

  commit e929ea7a18b0aa4d7767d2264d26fcc5c8dde688
  Author: Binghua Guan <freebendygmail.com>
  Date:   Mon Jul 23 21:29:50 2018 +0800

    python-cmd2: add native and nativesdk

  causing:
ERROR: Nothing RPROVIDES 'python3-colorama-native' (but virtual:native:/OE/meta-openembedded/meta-python/recipes-devtools/python/python3-cmd2_1.3.11.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-colorama-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colorama-native']
NOTE: Runtime target 'python3-cmd2-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-cmd2-native', 'python3-colorama-native']
NOTE: Runtime target 'python3-pyflakes-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-pyflakes-native', 'python3-cmd2-native', 'python3-colorama-native']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'ament-cmake-pyflakes', 'ament-pyflakes-native', 'python3-pyflakes-native', 'python3-cmd2-native', 'python3-colorama-native']

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Acked-by: Trevor Gamblin <trevor.gamblinwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>