src/meta-openembedded:postgresql: upgrade 13.1 -> 13.2
-License-Update: Copyright year updated to 2021.

Upgrade patches to fix

ERROR: postgresql-13.2-r0 do_patch: Fuzz detected:

Applying patch 0001-configure.in-bypass-autoconf-2.69-version-check.patch
patching file configure.in
Hunk #1 succeeded at 19 with fuzz 2.

Signed-off-by: Zheng Ruoqin <zhengrq.fnstcn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>