src/meta-openembedded:zeromq: consider license exception over LGPL-3.0
MJ: v1 was already merged before LGPLv3+ was dropped from LICENSE
based on https://lists.openembedded.org/g/openembedded-devel/message/103320
causing:
ERROR: QA Issue: Recipe LICENSE includes obsolete licenses LGPLv3+ [obsolete-license]

Signed-off-by: Remi Peuvergne <remi.peuvergnenon.se.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>