src/meta-openembedded:fwupd: Fix plugin_gpio PACKAGECONFIG
Trying to disable the gpio plugin results in an error

	ERROR: Option 'plugin_gpio' must have a value separated by equals sign.

Correct the PACKAGECONFIG for this option so it can be disabled.

Signed-off-by: Robert Joslyn <robert.joslynredrectangle.org>
Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit 2ab46bac63c32a1f37576b4b8be61c95585ffcf2)
Signed-off-by: Armin Kuster <akuster808gmail.com>