src/meta-openembedded:libgnomeprint: Add missing dependency on freetype
Fixes compile errors like

| gnome-rfont.c:31:30: fatal error: freetype/ftglyph.h: No such file or
directory
|  #include <freetype/ftglyph.h>
|                               ^
| compilation terminated.
| make[3]: *** [gnome-rfont.lo] Error 1

Fix header inclusion mechanism for freetype headers

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>