src/meta-virtualization:docker-ce/docker-moby: fixup GO compiler calls
With oe-core commit c23f9e80492e4b [tcmode-default: use go-binary-native
by default], we must explictly call the proper cross go binary, versus
just the go-native variant.

These builds were working by luck, since the go compiler was capable of
building the target binaries previously (in its build-from-source
creation). We fixup the calls and we no longer see fpu build issues:

fatal error: gnu/stubs-soft.h: No such file or directory

    7 | # include <gnu/stubs-soft.h>
      |           ^~~~~~~~~~~~~~~~~~

This commit also moves the docker-ce patches from "files" to a named
directory to reduce confusion.

Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>