src/meta-amd:amd: Conditionalize firmware-wireless on MEL based distros.
Resolves open Yocto build errors such as:
    ERROR: Nothing RPROVIDES 'firmware-wireless' (but
    ...poky/meta/recipes-core/packagegroups/packagegroup-base.bb
    RDEPENDS on or otherwise requires it)

Signed-off-by: Drew Moseley <drew_moseleymentor.com>