src/meta-intel:intel-graphics-compiler: upgrade 1.0.6083 -> 1.0.6410
Patches applied from Open PR#171, in order to build with llvm-12.
https://github.com/intel/intel-graphics-compiler/pull/171

Error logs:
(1)
|
/build/tmp/work/corei7-64-poky-linux/intel-graphics-compiler/1.0.6410-r0/git/IGC/Compiler/CISACodeGen/VariableReuseAnalysis.hpp:83:56:
error: 'unsigned int llvm::VectorType::getNumElements() const' is
deprecated: Calling this function via a base VectorType is deprecated.
Either call getElementCount() and handle the case where Scalable is true
or cast to FixedVectorType. [-Werror=deprecated-declarations]
|    83 |             NumElts = VTy ? (short)VTy->getNumElements() : 1;

Ref:https://github.com/llvm/llvm-project/commit/867de151a52b6d0750485ac1cf9b3bc012ee51fd

(2)
|
/build/tmp/work/corei7-64-poky-linux/intel-graphics-compiler/1.0.6410-r0/git/IGC/common/igc_resourceDimTypes.h:69:23:
error: 'const class llvm::Module' has no member named 'getTypeByName'
|    69 |         return
module.getTypeByName(ResourceDimensionTypeName[resourceDimTypeId]);

Ref:
https://github.com/llvm/llvm-project/commit/fe431683484a3041e024ab2373bb707b1ca8d1cf

Update copyright year in headers in IGC Compiler and some format updates.

Signed-off-by: Naveen Saini <naveen.kumar.sainiintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>