src/meta-openembedded:transmission: fix compliance checking
'''
ERROR: Nothing PROVIDES 'gtk4' (but meta-openembedded/meta-oe/recipes-connectivity/transmission/transmission_4.0.6.bb DEPENDS on or otherwise requires it)
gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers
'''

Add opengl to DISTRO_FEATURES contain condition

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>