src/meta-openembedded:libutempter: update SRC_URI
altlinux.org link is dead, update to new git repo

WARNING: Failed to fetch URL ftp://ftp.altlinux.org/pub/people/ldv/utempter/libutempter-1.1.6.tar.bz2, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, no output
ERROR: Function failed: Fetcher failure for URL: 'ftp://ftp.altlinux.org/pub/people/ldv/utempter/libutempter-1.1.6.tar.bz2'. Unable to fetch URL from any source.

Signed-off-by: Armin Kuster <akuster808gmail.com>