src/meta-openembedded:ibus: missing installed file w/ gtk2 PACKAGECONFIG
In case gtk2 PACKAGECONFIG is enabled, do_package task fails
with the following error:

ERROR: ibus-1.5.26-r0 do_package: QA Issue: ibus: Files/directories were installed but not shipped in any package:
  /usr/lib/gtk-2.0/2.10.0/immodules/im-ibus.so

This patch adds the missing folder to the FILES variable.

Signed-off-by: Gyorgy Sarvari <skandigraungmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>