src/meta-openembedded:vim: don't check acl header if acl support disabled
Vim/vim-tiny always check 'sys/acl.h' existence even acl support
has been disabled from configure line. This works in mostly time
but except for acl works in an odd mode - while acl was mirrored
from sstate_cache, it will install 'sys/acl.h' to sysroot dir and
and then clean the header file with sysroot_cleansstate().

If build vim/vim-tiny and acl in parallel, below errors will occur:

* os_unix.c:2668:23: fatal error: sys/acl.h: No such file or directory

This change only workaround the failure and get build running, we
still need to fix it from acl side.

Signed-off-by: Wenzong Fan <wenzong.fanwindriver.com>
Signed-off-by: Randy MacLeod <Randy.MacLeodwindriver.com>
Signed-off-by: Chong Lu <Chong.Luwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>