src/meta-openembedded:klibc_2.0.4: update to 4d1997d - Fix build for qemux86
Minimally rebase staging.patch and follow upstream commits.

Fixes:
| usr/klibc/socketcalls/socket.o: In function `socket':
| .../usr/klibc/socketcalls/socket.S:8: multiple definition of `socket'

Signed-off-by: Andrea Adami <andrea.adamigmail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>