src/meta-openembedded:pipewire: fix build error when pipewire-jack is used
If PACKAGECONFIG contains pipewire-jack the following error was seen:

    ERROR: pipewire-0.3.45-r0 do_package: QA Issue: pipewire: Files/directories were installed but not shipped in any package:
      /usr/bin/pw-jack
      /usr/share/pipewire/minimal.conf
    Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
    pipewire: 2 installed and not shipped files. [installed-vs-shipped]

File /usr/bin/pw-jack is added to pipewire-jack package.

The removal of minimal.conf was conditional to not configuring 'pipewire-jack'.
Can not see any reason to make it conditional on that specific option and make
it always removed to avoid packaging error.

Errors introduced in 687483235b5542401245711cb610ec327b33c403

Signed-off-by: Peter Bergin <peterberginkonsult.se>
Signed-off-by: Khem Raj <raj.khemgmail.com>