src/meta-openembedded:lldpd: configure the systemd unit file dir
configure the systemd unit file dir, otherwise it will be auto-checked
by 'pkg-config --variable=systemdsystemunitdir systemd', but if systemd
is not built firstly, and the the unit file will not be installed, and
lead to below error:
    ERROR: Function failed: SYSTEMD_SERVICE_lldpd value lldpd.service does not exist
and disable sysusersdir, since sysuser is not used currently.

Signed-off-by: Roy Li <rongqing.liwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>