src/meta-openembedded:pidgin: upgrade to 2.14.1 and fix autoconf-2.71 compatibility
* also log.do_configure is showing this since switch to python3:
  DEBUG: Executing shell function do_configure
  File "<string>", line 1
    import sys ; print sys.version[0:3]
                       ^
  SyntaxError: invalid syntax

  and this whole line doesn't make much sense and PY_VERSION shouldn't be used in configure.ac since:

  commit 9087a59b1c3f9708642a2327b0cf6ecceac0a66f
  Author: Martin Jansa <Martin.Jansagmail.com>
  Date:   Thu May 5 16:58:59 2016 +0200

    pidgin: use pkg-config instead of hardcoded paths or python-config

* use separate recipe for libgnt (needed only when consoleui PACKAGECONFIG is enabled)
  with 0.14.0 release libgnt was moved to separate repository

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>