src/poky:systemd: Make libnss-mymachines conditional upon packageconfig
nss-mymachines packageconfig controls this features therefore add this
dependency only when it is enabled.

Fixes
    ERROR: systemd-1_254.4-r0 do_package_qa: QA Issue: systemd-container rdepends on libnss-mymachines, but it isn't a build dependency? [build-deps]

(From OE-Core rev: 40f2e5776ebf6cf93694d05189488e8448767b3a)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Florian Wickert <fwferncast.de>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>