src/meta-virtualization:python-m2crypto: Fix issue with swig 3.0.5
The version 0.22.3 of python-m2crypto fails to work after
swig updated to 3.0.5+:
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'

It's fixed since 0.22.4 and we could update it to latest version,
but docker-registry depends on the version 0.22.3, so backport
the patch to fix the issue with swig 3.0.5.

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>