src/poky:glibc: make glibc-dev depend on kernel headers
The linux kernel headers are necessary for glibc-dev, so
we need to use RDEPENDS instead of DEV_PKG_DEPENDENCY which
specifies RRECOMMENDS.

Currently, in case of NO_RECOMMENDATIONS set to "1", linux
kernel headers are not pulled in by glibc-dev, causing error
like below when compiling.

  fatal error: linux/errno.h: No such file or directory

The problem could be reproduced by setting NO_RECOMMENDATIONS
to "1" and then running:

  bitbake core-image-minimal -c populate_sdk
  bitbake core-image-minimal -c testsdk

(From OE-Core rev: fdb16e1a78c2abcc8ac89678b1b250ca4fa9c0d9)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>