src/poky:archiver: avoid empty incfile in ar_recipe
do_ar_recipe fails on perf recipe on line:

include ${bb.utils.contains('PACKAGECONFIG', 'scripting', 'perf-perl.inc', '', d)}

1. "${...}" part expands into empty string
2. bb.utils.which() takes empty string and returns first directory name from bbpath
3. shutil.copy() fails on copying directory:

Exception: IsADirectoryError: [Errno 21] Is a directory: ......

Hence, check "incfile" variable on each step.

(From OE-Core rev: 3b393da7d2d15de12e2a8a9c11591078b40b188a)

Signed-off-by: grygorii tertychnyi <gtertychcisco.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>