src/meta-openembedded:xscreensaver: Remove xserver-nodm-init rdep
this seems to be not required anyway

Fixes
ERROR: xscreensaver different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
Hash for dependent task x11-common/xserver-nodm-init_3.0.bb:do_packagedata changed from de0944d4fcaeed0efdb143a18cc406bd043469ae291de1704a999bc878a7691c to ba7bdaf35860ba5bf5a5f4ce06379a77c88eb9806e09a1fc5373933888a46507

Signed-off-by: Khem Raj <raj.khemgmail.com>