src/poky:kernel-arch: add macro-prefix-map in KERNEL_CC
When building external modules, macros can include absolute names of
kernel headers. The macro-prefix-map for the STAGING_KERNEL_DIR is
currently missing. Add it in the same way as its done in bitbake.conf.

This fixes reproducible builds and following build error:
ERROR: cryptodev-module-1.14-r0 do_package_qa: QA Issue: File <..>
cryptodev.ko <..> contains reference to TMPDIR [buildpaths]

(From OE-Core rev: a741e11751bfb8f52be58cf51abeddca4559e5e9)

(From OE-Core rev: 58eb15cdc2dd95bf5eb0bed2a0f1c43bf29cf273)

Signed-off-by: Stefan Müller-Klieser <s.mueller-klieserphytec.de>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
Signed-off-by: Alexander Sverdlin <alexander.sverdlinsiemens.com>
Signed-off-by: Steve Sakoman <stevesakoman.com>