src/meta-openembedded:fluentbit: fix SYSTEMD_SERVICE name
* the binary and service name was renamed in 0.11.11
  from fluent-bit to td-agent-bit, but unfortunately
  SYSTEMD_SERVICE wasn't updated in the recipe with
  the upgrade causing do_package failures as in:
  http://errors.yoctoproject.org/Errors/Details/147040/
  ERROR: SYSTEMD_SERVICE_fluentbit value fluent-bit.service does not exist

0.11.3-r0/image/
0.11.3-r0/image/etc
0.11.3-r0/image/etc/fluent-bit
0.11.3-r0/image/etc/fluent-bit/parsers.conf
0.11.3-r0/image/etc/fluent-bit/fluent-bit.conf
0.11.3-r0/image/lib
0.11.3-r0/image/lib/systemd
0.11.3-r0/image/lib/systemd/system
0.11.3-r0/image/lib/systemd/system/fluent-bit.service
0.11.3-r0/image/usr
0.11.3-r0/image/usr/bin
0.11.3-r0/image/usr/bin/fluent-bit
0.11.3-r0/image/usr/lib
0.11.3-r0/image/usr/lib/libfluent-bit.so
0.11.3-r0/image/usr/lib/pkgconfig
0.11.3-r0/image/usr/lib/pkgconfig/msgpack.pc

0.11.11-r0/image
0.11.11-r0/image/etc
0.11.11-r0/image/etc/td-agent-bit
0.11.11-r0/image/etc/td-agent-bit/parsers.conf
0.11.11-r0/image/etc/td-agent-bit/td-agent-bit.conf
0.11.11-r0/image/lib
0.11.11-r0/image/lib/systemd
0.11.11-r0/image/lib/systemd/system
0.11.11-r0/image/lib/systemd/system/td-agent-bit.service
0.11.11-r0/image/usr
0.11.11-r0/image/usr/bin
0.11.11-r0/image/usr/bin/td-agent-bit
0.11.11-r0/image/usr/lib
0.11.11-r0/image/usr/lib/libfluent-bit.so
0.11.11-r0/image/usr/lib/pkgconfig
0.11.11-r0/image/usr/lib/pkgconfig/msgpack.pc

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>