src/meta-openembedded:ufs-utils: upgrade 6.14.11 -> 7.14.11
Extending _GNU_SOURCE to the CFGLAS of all platforms, not just
mipsarchn64, was necessary to fix the following error raised during the
compilation of the new version:

ufs_emon.c: In function ‘do_emon’:
ufs_emon.c:455:51: error: ‘O_DIRECT’ undeclared (first use in this function); did you mean ‘O_DIRECTORY’?
  455 |         fill_data_fd = open("fill_file", O_RDWR | O_DIRECT | O_CREAT,
      |                                                   ^~~~~~~~
      |                                                   O_DIRECTORY
ufs_emon.c:455:51: note: each undeclared identifier is reported only once for each function it appears in

This _GNU_SOURCE define was added upstream in commit [1] in the Makefile
default CFLAGS, but since Yocto redefines those it needs to be added
back.

Release notes:
https://github.com/SanDisk-Open-Source/ufs-utils/releases/tag/v7.14.11

[1] https://github.com/SanDisk-Open-Source/ufs-utils/commit/183e0deb28f13cfb3caf161fc6d0f3cd1edb05c2

Signed-off-by: Dario Binacchi <dario.binacchiamarulasolutions.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>