src/meta-openembedded:libpfm4: Remove -Werror from compiler flags
Newer versions of compilers get stricter and add new diagnostics which
cause build failures that upstream should address not distros

Fixes
| In function 'perf_table_alloc_umask',
|     inlined from 'gen_tracepoint_table' at pfmlib_perf_event_pmu.c:434:10:
| pfmlib_perf_event_pmu.c:304:47: error: pointer may be used after 'realloc' [-Werror=use-after-free]

Signed-off-by: Khem Raj <raj.khemgmail.com>