src/meta-intel:lms: use sh instead of bash in notifyDesktop.sh
A recent update to OE-core revealed the missing runtime dependency:

ERROR: lms8-8.0.0-7-r0 do_package_qa: QA Issue: /usr/bin/notifyDesktop.sh
contained in package lms8 requires /bin/bash, but no providers found in
RDEPENDS_lms8? [file-rdeps]

But it turns out that notifyDesktop doesn't actually require bash:

$ checkbashisms.pl notifyDesktop.sh
could not find any possible bashisms in bash script notifyDesktop.sh

So just change the shebang line to /bin/sh.

Signed-off-by: California Sullivan <california.l.sullivanintel.com>
CC: mikko.ylinenlinux.intel.com
CC: anand.vastradintel.com
Signed-off-by: Saul Wold <sgwlinux.intel.com>