src/meta-openembedded:libldb: Add samba to rdeps for pyldb
Fixes
ERROR: QA Issue: pyldb rdepends on samba, but it isn't a build
dependency, missing samba in DEPENDS or PACKAGECONFIG? [build-deps]

Signed-off-by: Khem Raj <raj.khemgmail.com>