src/meta-openembedded:mariadb: Include missing sys/type.h for ssize_t
musl finds this problem in sources where its missing to include
needed system header for ssize_t

Fixes
wsrep-lib/include/wsrep/gtid.hpp:80:5: error: unknown type name 'ssize_t'; did you mean 'size_t'?
    ssize_t scan_from_c_str(const char* buf, size_t buf_len,
    ^~~~~~~
    size_t

Signed-off-by: Khem Raj <raj.khemgmail.com>