src/meta-openembedded:libcamera: Update to latest master tip
Drop upstreamed patch
jinja2.Environment.compile_templates no longer accepts py_compile
argument so delete it

Fixes
TypeError: compile_templates() got an unexpected keyword argument 'py_compile'

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Andreas Müller <schnitzeltonygmail.com>