src/poky:python: Add missing RDEPENDS for python-unittest
After installing python-unittest, the following errors occur when executing
"import unittest" from a python commandline:
ImportError: No module named StringIO
ImportError: No module named pprint
ImportError: No module named difflib
ImportError: No module named pprint
ImportError: No module named fnmatch

Fix this by adding the missing dependencies to the generator script and run
the generator.

(From OE-Core rev: 496adfe84ef05d031444988d41451a018133f5a8)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>