src/poky:oeqa/selftest/devtool: fix test_devtool_add_git_style2
The problem is the following:
AssertionError: 'gitsm://gitgithub.com/ARMmbed/mbedtls.git;protocol=https;branch=master' != 'git://gitgithub.com/ARMmbed/mbedtls.git;protocol=https;branch=master'

Mbedlts made changes to their repository, adding a sub-module, thus the
assert triggers an error with the url:
git://gitgithub.com/ARMmbed/mbedtls.git;protocol=https;branch=master

https://github.com/Mbed-TLS/mbedtls/commit/456a54da8ef44c8b725b524567c08cffec6a7214
was the upstream change.

To fix the issue, the url has been changed to:
gitsm://gitgithub.com/ARMmbed/mbedtls.git;protocol=https;branch=master

(From OE-Core rev: 9ac737fbe05c85ec8333b396ce2f89de6654916f)

Signed-off-by: Alexandre Truong <alexandre.truongsmile.fr>
Reviewed-by: Yoann Congal <yoann.congalsmile.fr>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>