src/meta-openembedded:mariadb: Upgrade to 10.7.3
Remove two patches which are already included in new version and rebase
one patch to new version and add lzo rdepends to fix below qa issue. [1]
ERROR: mariadb-10.7.3-r0 do_package_qa: QA Issue: /usr/lib64/plugin/provider_lzo.so contained in package mariadb-server requires liblzo2.so.2()(64bit), but no providers found in RDEPENDS:mariadb-server? [file-rdeps]

Add gnutls to depends to fix below error and fmt to depends [2]
 | Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR)

[1] https://github.com/MariaDB/server/commit/bf8b699f649b7f947e8ad8eeeb48c3d5f973be39
[2] https://github.com/MariaDB/server/commit/284ed643369dec9ff600bf4b2a2d9457986eda6e

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>