src/meta-openembedded:apache-websocket: add depend on pbzip2-native
This fixes the build failure:

ERROR: apache-websocket-0.1.1-r0 do_install_source: Failed to
archive (...) /bin/sh: pbzip2: command not found

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiuni.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>