src/meta-openembedded:xfce4-panel: fix QA issue 'installed-vs-shipped'
Since commit 5f31db601408 [xfce4-panel: upgrade 4.12.2 -> 4.13.3] we
are getting a QA Warnings/Erros for 'installed-vs-shipped':

    ERROR: xfce4-panel-4.13.3-r0 do_package: QA Issue: xfce4-panel:
    Files/directories were installed but not shipped in any package:
      /usr/lib64/xfce4/panel/plugins/liblauncher.la
      /usr/lib64/xfce4/panel/plugins/libdirectorymenu.la
      ...

>From various OE documents the .la files should not be packaged in
either the main recipe package or the -dev package unless required. So
inherit 'remove-libtool' to have all the .la files cleaned up as they
don't appear to be necessary.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>