src/meta-raspberrypi:eglinfo-x11: Disable --as-needed
--as-needed exposes a dependency problem where libegl needs some symbols
from libgles2 but the order that waf uses on linker cmdline for these
libs is reversed so we end up with link time failures e.g.

libEGL.so: undefined reference to `glxx_client_GetRenderbufferParameteriv'

Signed-off-by: Khem Raj <raj.khemgmail.com>