src/meta-openembedded:multipath-tools: depend on libdevmapper instead of lvm2
Now we've separted libdevmapper out of lvm2 recipe, we need to change
multipath-tools to depend on libdevmapper instead of lvm2 to avoid
build error like below.

  fatal error: libdevmapper.h: No such file or directory

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>