src/poky:rpm: avoid empty plugindir error
When using dnf/rpm, we'll see error messages like below:

  error: /usr/lib64/rpm/macros: line 1183: Macro %__plugindir has empty body

The problem was introduced by the following commit in RPM upstream:
https://github.com/rpm-software-management/rpm/commit/ab28534f9e68aff8be65cd1adbac86b5a2cafde4

We'll need to move RPM_PLUGINDIR definition to top-level CMakefile.txt
to solve this problem.

(From OE-Core rev: 3a54d93052cb7f3d591517a873e516136e965ba8)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>