src/meta-openembedded:python3-twisted: Add python3-typing-extensions to RDEPENDS
To fix crash due to missing module:

File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 42, in <module>
from typing_extensions import Literal, ParamSpec, Protocol
ModuleNotFoundError: No module named 'typing_extensions'

Signed-off-by: Hains van den Bosch <hainsvdboschziggo.nl>
Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Guðni Már Gilbert <gudnimarnoxmedical.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>