src/meta-openembedded:xfce4-datetime-setter: fix compile error and requires distro feature x11
It fails to compile xfce4-datetime-setter occasionally when system load
is high:

| ../git/xfce/main.c:42:10: fatal error: cc-datetime-resources.h: No such file or directory
|    42 | #include "cc-datetime-resources.h"
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

Update datetime_panel_dep to make sure cc-datetime-resources.h be
generated before including.

xfce4-datetime-setter depends on libxfce4ui which requires distro
feature 'x11', so make it require 'x11' too.

Signed-off-by: Kai Kang <kai.kangwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>