src/poky:python-smartpm: fix option typo of command channel
When run smart, it fails:

rootqemu1:~# smart channel --remove-all
error: No action specified for command 'channel'

If no default value of arg 'dest' is provided in method add_option() of
optparse.OptionParser, it replaces hyphen('-') in new added option with
underscore('_') as dest.

In function ensure_action() it checks action strings with options from
optparse.OptionParser. So it is 'remove_all' which need to be checked
rather than 'remove-all'.

(From OE-Core rev: 03266e89a67ec1373529fae32b2cedff21414ff5)

Signed-off-by: Kai Kang <kai.kangwindriver.com>
Signed-off-by: Saul Wold <sgwlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>