src/poky:ltp: Fix __sighandler_t for mips
mips definition of kernel_sigaction was added later
and the patch did not apply to mips part which ended
in ltp failing to compile on mips parts

In file included from rt_sigaction01.c:42:0:
../../../../include/lapi/rt_sigaction.h:39:2: error: unknown type name '__sighandler_t'
  __sighandler_t k_sa_handler;
  ^~~~~~~~~~~~~~

(From OE-Core rev: 74f4dcfd447fb528ab230e67e3f7ab37e8f93898)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>