src/poky:systemd: backport another change from v252 to fix build with CVE-2022-45873.patch
* CVE-2022-45873.patch was backported from systemd/main, but it doesn't
  build without another change from v252 when elfutils PACKAGECONFIG is
  enabled.

* fixes:
  | ../git/src/shared/elf-util.c: In function 'parse_elf_object':
  | ../git/src/shared/elf-util.c:792:27: error: void value not ignored as it ought to be
  |   792 |                         r = json_variant_dump(package_metadata, JSON_FORMAT_FLUSH, json_out, NULL);
  |       |                           ^

(From OE-Core rev: bc8501a5a2ffc5673bad50f744d78822525bea9d)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>