src/meta-openembedded:mariadb: Upgrade to 10.11.7
As the change [1] introduced in 10.11.7, there comes below configure failure:
 | -- Performing Test HAVE_SYSTEM_LIBFMT
 | CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
 |    HAVE_SYSTEM_LIBFMT_EXITCODE (advanced)
 | For details see /build/tmp-glibc/work/core2-64-wrs-linux/mariadb/10.11.7/build/TryRunResults.cmake
 | -- Performing Test HAVE_SYSTEM_LIBFMT - Failed
 [snip]

Considering [1] is mainly used to test fmt 10.0.0 failure and we use libfmt
10.2.1 now, so define "-DHAVE_SYSTEM_LIBFMT_EXITCODE=0" as workaround [2] to
fix the above configure error.

Remove the problematic assert lines to fix the below build failure on 32bit
arm as the next 10.11 release will bring the assert back in a way that works
on 32-bit arm [3].
 In file included from TOPDIR/build/tmp/work/cortexa15t2hf-neon-yoe-linux-gnueabi/mariadb/10.11.7/mariadb-10.11.7/tests/mysql_client_test.c:38:
 TOPDIR/build/tmp/work/cortexa15t2hf-neon-yoe-linux-gnueabi/mariadb/10.11.7/mariadb-10.11.7/tests/mysql_client_fw.c:1438:3: error: 'compile_time_assert' declared as an array with a negative size
  1438 |   compile_time_assert(sizeof(MYSQL) == 77*sizeof(void*)+656);
       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[1] https://github.com/MariaDB/server/commit/b5c367cd88e37091ab5f8dab0396c01c97d037e2
[2] https://jira.mariadb.org/browse/MDEV-30694
[3] https://jira.mariadb.org/browse/MDEV-33429

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>