src/poky:oeqa/runtime: fix race-condition in minidebuginfo test
Fix this error where 'coredumpctl info' warns that the coredump is still being
processed:

```
AssertionError: 1 != 0 : MiniDebugInfo Test failed: No match found.
-- Notice: 1 systemd-coredump@.service unit is running, output may be incomplete.
```

(From OE-Core rev: ad1ce64f5c1f22a7b10025d8cba20dc74354ac81)

(From OE-Core rev: f7e824477ef75fcea8e0b777278413304def631c)

Signed-off-by: Etienne Cordonnier <ecordonniersnap.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit ed562345d5a5f2edb649028553199f3f7966e19e)
Signed-off-by: Steve Sakoman <stevesakoman.com>