src/meta-openembedded:influxdb: remove S in recipes that fetch from git via setting BB_GIT_DEFAULT_DESTSUFFIX
Removing all the S = ${WORKDIR}/git assignments works because BB_GIT_DEFAULT_DESTSUFFIX
is set to match S from bitbake.conf (which itself is set to match typical tarball
releases).

ERROR: influxdb-1.8.10-r0 do_unpack: Recipes that set S = "${WORKDIR}/git" or S = "${UNPACKDIR}/git" should remove that assignment, as S set by bitbake.conf in oe-core now works.

Signed-off-by: Alper Ak <alperyasinak1gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>