src/meta-openembedded:networkmanager: package additional .la files
This fixes:
     ERROR: networkmanager-1.14.4-r0 do_package: QA Issue: networkmanager: Files/directories were installed but not shipped in any package:
       /usr/lib64/NetworkManager/1.14.4/libnm-settings-plugin-ifupdown.la
       /usr/lib64/NetworkManager/1.14.4/libnm-device-plugin-adsl.la
       /usr/lib64/NetworkManager/1.14.4/libnm-device-plugin-wifi.la
       /usr/lib64/NetworkManager/1.14.4/libnm-device-plugin-ovs.la
     Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
     networkmanager: 4 installed and not shipped files. [installed-vs-shipped]

As with similar changes in the past, if the distro makes use of
'remove-libtool' this issue is not seen but we should add .la files to
the -dev package when they do exist.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>