src/poky:perl: Fix build with gcc-12
Fix the build failure when debug build is enabled.
Add DEBUG_BUILD = "1" in conf/local.conf.
 $ bitbake perl
  | In function 'dynprep',
    inlined from 'S_sortsv_flags_impl' at pp_sort.c:358:20,
    inlined from 'sortsv_amagic_i_ncmp' at pp_sort.c:572:5:
  |  pp_sort.c:1232:1: error: inlining failed in call to 'always_inline' 'S_amagic_i_ncmp': function not considered for inlining
  | 1232 | S_amagic_i_ncmp(pTHX_ SV *const a, SV *const b)

(From OE-Core rev: 4eb85dbace4d6d2cccdeed96b4aee80a8fc24e37)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit 880296e68cfd92cfd4c9474972c8d8e6f21a2a40)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>