src/meta-openembedded:glmark2: Fix build error due a missing space before a macro
This fixes following error:

../src/native-state-x11.cpp:63:33: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
     static const char *win_name("glmark2 "GLMARK_VERSION);

Signed-off-by: Otavio Salvador <otavioossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>