src/meta-openembedded:collectd: fix libvirt PACKAGECONFIG
* fixes:
  ERROR: collectd-5.8.0-r0 do_configure: QA Issue: collectd: configure was passed unrecognised options: --disable-libvirt [unknown-configure-option]
* the PACKAGECONFIG in meta-oe was introduced long time ago:

commit 5fbe2ac4e8ff67707b907c736966ee3d3357fd0d
Author: Wenzong Fan <wenzong.fanwindriver.com>
Date:Tue Dec 23 16:55:50 2014 +0800

 collectd: add PACKAGECONFIG for libvirt, libesmtp

 Add PACKAGECONFIG for libvirt, libesmtp to fix below warnings:

and at that time in 5.4.1 there was libvirt (renamed from libvirtstats) option, since this commit:
https://github.com/collectd/collectd/commit/553376a3a6c63875c84b406962e56b908dc4e675

but then in 5.5.0 it was renamed again to just virt:
https://github.com/collectd/collectd/commit/62f948605f54e1f5575699360376d75a2f849faf

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>