src/poky:libstd-rs: Fix build on riscv64/musl
Backport necessary patch, which was dropped in upgrade to 1.59

Fixes:

error[E0425]: cannot find value `SYS_clone3` in this scope
   --> library/std/src/sys/unix/weak.rs:202:17
    |
202 |                   concat_idents!(SYS_, $name),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `SYS_clone`
    |
   ::: library/std/src/sys/unix/process/process_unix.rs:165:9
    |
165 | /         raw_syscall! {
166 | |             fn clone3(cl_args: *mut clone_args, len: libc::size_t) -> libc::c_long
167 | |         }
    | |_________- in this macro invocation
    |

(From OE-Core rev: f529401cd8d2c45273f706636e5ed89123238200)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>