src/meta-openembedded:polkit: add REQUIRED_DISTRO_FEATURES for polkit
After below commits to add polkit as a required
distro feature:
97a1a55 polkit: add polkit as a required distro feature
c049e02 polkit: inherit distro_features_check

All recipes that includes polkit-group-rule.inc will fail to parse
when polkit is not in DISTRO_FEATURE, especially 'world'. e.g.

ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'udisks', 'polkit']

Signed-off-by: Nicolas Dechesne <nicolas.dechesnelinaro.org>
Signed-off-by: Khem Raj <raj.khemgmail.com>