src/poky:qemu: fix for virtfs configuration error in qemu 5.0.0
Add --enable-cap-ng as virtfs dependency in qemu configuration.
When using meta-virtualization layer, qemu requires virtfs,
but during do_configure stage below error message shows up:

  ERROR: VirtFS requires libcap-ng devel and libattr devel

(From OE-Core rev: 632b83372d74da749ec9c07621a17c5193db9f2b)

Signed-off-by: Kamil Dziezyk <kamil.dziezykarm.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>