src/poky:diffutils: allow native & nativesdk builds
Required by the new dtc rdepends to avoid errors like this:

ERROR: Required build target 'ionel-rpi-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['ionel-rpi-image', 'nativesdk-packagegroup-sdk-host', 'nativesdk-qemu', 'nativesdk-dtc', 'nativesdk-diffutils']

(From OE-Core rev: dc3829f31bcc7522e8eb457623a74655a738c0d9)

Signed-off-by: Ioan-Adrian Ratiu <adiadirat.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>