src/poky:iproute2: Remove bogus workaround patch for musl
This patch worked around a problem in musl but caused
the following:

iplink_bridge.c: In function 'br_dump_bridge_id':
iplink_bridge.c:77:2: warning: implicit declaration of function 'ether_ntoa_r'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
  ether_ntoa_r((const struct ether_addr *)id->addr, eaddr);
  ^~~~~~~~~~~~

In the meantime upstream has already implemented a different
workaround for musl, so this patch can just be dropped.

Signed-off-by: Adrian Bunk <bunkstusta.de>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>