src/meta-openembedded:libhugetlbfs: update patch to make it work for python3
Fix error:
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>