src/meta-openembedded:safec: Define _GNU_SOURCE
musl does not define this variable automatically but safec does provide
wrapper for some GNU extentions as well e.g.

error: implicit declaration of function 'localtime_r' is invalid in C99

Signed-off-by: Khem Raj <raj.khemgmail.com>