src/meta-openembedded:pure-ftpd: upgrade 1.0.47 -> 1.0.49
1) Upgrade pure-ftpd from 1.0.47 to 1.0.49.

2) Update LIC_FILES_CHKSUM as date has been changed.

3) Update 0001-Remove-hardcoded-usr-local-includes-from-configure.a.patch for 1.0.49.

4) Delete "--with-minimal" to fix error as follows:

/usr/src/debug/pure-ftpd/1.0.49-r0/build/src/../../pure-ftpd-1.0.49/src/ls.c:1080: undefined reference to `modernformat'

Signed-off-by: Zheng Ruoqin <zhengrq.fnstcn.fujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>