src/meta-openembedded:python3-protobuf: add cpp implementation support
- Compiling with option `--cpp_implementation', add cpp implementation
support which requires to build with protobuf.

- Workaround native compile failure while host gcc <= 4.8
Setting environment KOKORO_BUILD_NUMBER, the build will explicitly compile
with option `-std=c++11', it could  workaround native compile failure while
host gcc <= 4.8
...
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file
requires compiler and library support for the ISO C++ 2011 standard. This
support is currently experimental, and must be enabled with the -std=c++11
or -std=gnu++11 compiler options
...

- Add Python 3.7 compatibility

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>