src/meta-openembedded:net-snmp: fix compile error with --disable-des
| scapi.c: In function 'sc_encrypt':
| scapi.c:1256:5: error: 'pad_size' undeclared (first use in this function); did you mean 'dysize'?
|      pad_size = pai->pad_size;
|      ^~~~~~~~
|      dysize

pad_size is defined only without --disable-des
[snip]
    int             pad, plast, pad_size = 0;

but used when disable-des
[snip]
        QUITFUN(SNMPERR_GENERR, sc_encrypt_quit);
    }
    pad_size = pai->pad_size;

    memset(my_iv, 0, sizeof(my_iv));

    if (USM_CREATE_USER_PRIV_DES == (pai->type & USM_PRIV_MASK_ALG)) {

        /*

fix by move it into #ifndef NETSNMP_DISABLE_DES

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>