src/meta-openembedded:dracut: exclude kernel-modules dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: dracut different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['bash-completionbash-completion_2.1.bb.do_packagedata', 'bashbash_4.3.30.bb.do_packagedata', 'busyboxbusybox_1.23.2.bb.do_packagedata', 'coreutilscoreutils_8.24.bb.do_packagedata', 'cpiocpio_2.11.bb.do_packagedata', 'dracutdracut_git.bb.do_package', 'dracutdracut_git.bb.do_packagedata', 'findutilsfindutils_4.5.14.bb.do_packagedata', 'glibcglibc_2.22.bb.do_packagedata', 'linuxlinux-yocto_4.1.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'systemdsystemd_225.bb.do_packagedata', 'util-linuxutil-linux_2.26.2.bb.do_packagedata']
to
['bash-completionbash-completion_2.1.bb.do_packagedata', 'bashbash_4.3.30.bb.do_packagedata', 'busyboxbusybox_1.23.2.bb.do_packagedata', 'coreutilscoreutils_8.24.bb.do_packagedata', 'cpiocpio_2.11.bb.do_packagedata', 'dracutdracut_git.bb.do_package', 'dracutdracut_git.bb.do_packagedata', 'findutilsfindutils_4.5.14.bb.do_packagedata', 'glibcglibc_2.22.bb.do_packagedata', 'linuxlinux-yocto_4.1.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'systemdsystemd_225.bb.do_packagedata', 'util-linuxutil-linux_2.26.2.bb.do_packagedata']
openembedded-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb.do_packagedata with hash a98b79faed8b6633269560af1add43a5
 changed to
openembedded-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb.do_packagedata with hash 15962f296d6961232d7350368c604464
Hash for dependent task linuxlinux-yocto_4.1.bb.do_packagedata changed from a98b79faed8b6633269560af1add43a5 to 15962f296d6961232d7350368c604464

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>