src/meta-openembedded:evolution-data-server: update 3.2.3 -> 3.26.3
In recent meta-universe 3.2.3 started to fail with:

| camel-enumtypes.c:42:7: error: expected expression at end of input
|        { 512, "CAMEL_FOLDER_SHARED_BY_ME", "shared-by-me" },
|        ^

Instead of cleaning I decided to update. The following changed:

* eds builds with cmake instead of autotools
* musl: I checked src/time/strftime.c and it seems strftime does not support
  '%l' / '%k'. musl-case was added to be a good boy but was not tested.
* remove 0001-imapx-Fix-signature-for-imapx_tokenise_struct.patch:
  src/camel/providers/imapx/camel-imapx-tokens.txt has text-only format these days
* remove 0002-Fix-for-automake-1.12.x.patch: autotools was replaced by cmake
* remove 0003-Disable-Werror-for-automake.patch: autotools was replaced by cmake
* remove 0004-configure-Fix-libical-pkg-config-trying-to-use-host-.patch: autotools was replaced by cmake
* remove 0005-soup-adapt-to-new-libxml2-API-from-2.9.0.patch:
  src/calendar/backends/caldav/e-cal-backend-caldav.c was reworked competely
* remove 0006-configure.ac-do-not-overwrite-localedir.patch: autotools was replaced by cmake

Tested: abiword build and run

Signed-off-by: Andreas Müller <schnitzeltonygmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>