src/meta-openembedded:python3-h5py: Upgrade 3.1.0 -> 3.2.1
Upgrade to release 3.2.1:

- Added support to use the HDF5 ROS3 driver to access HDF5 files
  on S3
- Setting the config option default_file_mode to values other than
  'r' is deprecated. Pass the desired mode when opening a
  :class:`~.File` instead.
- :exc:`OSError` exceptions raised by h5py should now have a useful
  .errno attribute, where HDF5 provides this information.
  Subclasses such as :exc:`FileNotFoundError` should also be raised
  where appropriate.
- Fix reading data with a datatype of variable-length arrays of
  fixed length strings.
- Fix :meth:`.Dataset.read_direct` and :meth:`.Dataset.write_direct`
  when the source and destination have different shapes.
- Fix selecting data using integer indices in
  :meth:`.Dataset.read_direct` and :meth:`.Dataset.write_direct`.
- Fix exception handling in :meth:`.Group.visititems`.
- Issue a warning when File(..., swmr=True) is specified with any
  mode other than 'r', as the SWMR option is ignored in these cases.
- Fix NumPy 1.20 deprecation warnings concerning the use of None as
  shape, and the deprecated aliases np.float, np.int and np.bool.
- Fix :attr:`.File.driver` when the read-only S3 driver is
  available.

Add hdf5-native as a dependency to avoid:

error: libhdf5.so: cannot open shared object file: No such file or directory

Signed-off-by: Leon Anavi <leon.anavikonsulko.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Trevor Gamblin <trevor.gamblinwindriver.com>