src/meta-openembedded:gpsd: Install also the generated parts of the Python library
The Python library cannot be copied from the source code directory,
otherwise generated files like gps.py and packet.py are missing.

This is noticed when starting ubxtool which otherwise crashes:

Traceback (most recent call last):
  File "/usr/bin/ubxtool", line 48, in <module>
    import gps.ubx
  File "/usr/lib/python3.10/site-packages/gps/ubx.py", line 244, in <module>
    class ubx(object):
  File "/usr/lib/python3.10/site-packages/gps/ubx.py", line 255, in ubx
    verbosity = gps.VERB_NONE
AttributeError: module 'gps' has no attribute 'VERB_NONE'

Signed-off-by: Matthias Klein <matthiasextraklein.de>
Signed-off-by: Khem Raj <raj.khemgmail.com>