src/meta-cloud-services:rabbitmq-server: start failed
Starting : FAILED - check /var/log/rabbitmq/startup_{log, _err}

rabbitmq-server status also shows an error message:
Status of node rabbitcontroller ...
Error: unable to connect to node rabbitcontroller: nodedown

<snip>

There's a problem with erlang cookie synchronization.

rabbitmq's home directory is created and is used as the location
for the cookie.

Signed-off-by: Amy Fong <amy.fongwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>