src/poky:image_types_wic.bbclass: fix cross binutils dependency
Enable multilib and wic at the same time and we'll meet the
following error.

  ERROR: Nothing PROVIDES 'virtual/i686-wrsmllib32-linux-binutils'

Adjust the dependency to take multilib into consideration.

(From OE-Core rev: f5713addbe47eb6c998cfe1514a537acbd367c3e)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Luca Ceresoli <luca.ceresolibootlin.com>
(cherry picked from commit 958ee0eede859bdba659e3343856b1c226207854)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>