src/meta-openembedded:python3-webcolors: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import webcolors
 [snip]
 ModuleNotFoundError: No module named 'typing'

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Acked-by: Trevor Gamblin <trevor.gamblinwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>