src/poky:eglibc-locale: add missing dependency on virtual/${TARGET_PREFIX}binutils
* eglibc-collateral.inc inhibits all default deps, but do_package needs
  objcopy:
  ERROR: objcopy failed with exit code 127 (cmd was
  'i586-webos-linux-objcopy' --only-keep-debug
  'eglibc-locale/2.17-r0/package/usr/lib/gconv/IBM1166.so'
  'eglibc-locale/2.17-r0/package/usr/lib/gconv/.debug/IBM1166.so')
  ERROR: Function failed: split_and_strip_files

(From OE-Core rev: 9e615e2a6845d3a98f5d9b0cb555d132c696fc92)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Saul Wold <sgwlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>