src/meta-openembedded:xfstests: bstat: use uint32_t instead of __uint32_t to fix build with musl
* with musl this fails with:
  http://errors.yoctoproject.org/Errors/Details/853041/

bstat.c:65:33: error: unknown type name '__uint32_t'; did you mean 'uint32_t'?
   65 | static inline int xfs_highbit32(__uint32_t v)
      |                                 ^~~~~~~~~~
      |                                 uint32_t

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>