src/meta-openembedded:rrdtool: fix multilib problem
When building rrdtool with multilib enabled, we would meet the following error.

ERROR: QA Issue: rrdtool: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python2.7
  /usr/lib/python2.7/site-packages
  /usr/lib/python2.7/site-packages/rrdtool.so
  ....

Fix this problem by using nonarch_libdir instead of libdir.

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>