src/poky:boost: adjust hard-coded path after python3 upgrade
When using `PACKAGECONFIG = "python"` in the boost recipe, `bitbake boost`
fails at do_compile with:

    ./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
    compilation terminated.

This issue is due to the recent version upgrade from python 3.4 to 3.5:

701ec1977ced1bb08461e6de98b4f63d21cba8a6 python3: Upgrade from 3.4.3 to 3.5

The boost.inc file modifies the boost build configuration with a path
containing the python3 major version, which is hard-coded in the boost.inc
file. Hence after the python3 update, the path points to the outdated
location and it needs to be updated to the new location.

This issue was unrevealed by an internal continuous integration system
for the meta-ros application layer. Further manual bisecting lead to the
critical commit 701ec1977ced1bb08461e6de98b4f63d21cba8a6.

(From OE-Core rev: 0eefd38a13a6ecb35f26ed8cd16f0b36f2c5d652)

Signed-off-by: Lukas Bulwahn <lukas.bulwahnoss.bmw-carit.de>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>