src/meta-openembedded:tnftp: fix lib32-tnftp build failure with gcc-14
lib32-tnftp do_compile failed with gcc-14:
../../tnftp-20230507/libedit/terminal.c:597:56: error: passing argument 2 of 'terminal_overwrite' from incompatible pointer type [-Wincompatible-pointer-types]
  597 |                                 terminal_overwrite(el, &el->el_display[
      |                                                        ^~~~~~~~~~~~~~~~
      |                                                        |
      |                                                        wint_t * {aka unsigned int *}
  598 |                                     el->el_cursor.v][el->el_cursor.h],
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../tnftp-20230507/libedit/refresh.c:114:38: error: initialization of 'wchar_t *' {aka 'long int *'} from incompatible pointer type 'wint_t *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
  114 |                 wchar_t *firstline = el->el_vdisplay[0];

For 64bit system:
wchar_t is defined as int
wint_t is define as unsigned int

For 32bit system:
wchar_t is defined as long int
wint_t is define as unsigned int

In 64bit case, it works well, but in 32bit case, gcc will take it as
incompatible, and report above error

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>