src/meta-openembedded:spice-gtk: add opengl to REQUIRED_DISTRO_FEATURES
Fixes:
  ERROR: Nothing PROVIDES 'libepoxy' (but /build/layers/meta-openembedded/meta-networking/recipes-support/spice/spice-gtk_0.4.1.bb DEPENDS on or otherwise requires it)
libepoxy was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'spice-gtk', 'libepoxy']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>