src/meta-openembedded:python3-attrs: Add nativesdk to BBCLASSEXTEND
By doing so we mitigate failure when trying to bitbake recipe which
rdepends on nativesdk-python3-attrs, such as following error
when bitbaking nativesdk-python3-jsonschema:

  ERROR: Nothing RPROVIDES 'nativesdk-python3-attrs' (but virtual:nativesdk:.../meta-openembedded/meta-python/recipes-devtools/python/python3-jsonschema_3.2.0.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Niko Mauno <niko.maunovaisala.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>