src/meta-openembedded:wxwidgets: Fix checking for PACKAGECONFIG and DISTRO_FEATURES
The PACKAGECONFIG depends on DISTRO_FEATURES, not DISTRO_FEATURES depends on
PACKAGECONFIG. And the REQUIRED_DISTRO_FEATURES is not needed since it can work
with gtk or x11.

Fixed when x11 is not in DISTRO_FEATURES:
$ bitbake wxwidgets
ERROR: Nothing PROVIDES 'wxwidgets'
wxwidgets was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>