src/poky:webkitgtk: fix compile error for arm64
It removes function JSC::AssemblerBuffer::data() for ARM64 in commit
https://trac.webkit.org/changeset/236589/webkit. But it is required by
Cortex A53 from https://trac.webkit.org/changeset/175514/webkit and
fails to compile for arm64:

| .../tmp/work/aarch64-poky-linux/webkitgtk/2.24.0-r0/webkitgtk-2.24.0/Source/JavaScriptCore/assembler/ARM64Assembler.h:3769:100: error: 'class JSC::AssemblerBuffer' has no member named 'data'
|     if (UNLIKELY((*reinterpret_cast_ptr<int32_t*>(reinterpret_cast_ptr<char*>(m_buffer.data()) + m_buffer.codeSize() - sizeof(int32_t)) & 0x0a000000) == 0x08000000))

Not set WTF_CPU_ARM64_CORTEXA53 for arm64 to fix the failure.

(From OE-Core rev: 754baa7ccc8afad300f1a391469b6b428e37f096)

Signed-off-by: Kai Kang <kai.kangwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>