src/meta-openembedded:python3-pandas: Fix contains reference to TMPDIR [buildpaths] error
Ensures TMPDIR is removed before packaging.

ERROR: python3-pandas-2.2.3-r0 do_package_qa: QA Issue: File /usr/src/debug/python3-pandas/2.2.3/pandas/_libs/sparse.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/sparse.pyx.c in package python3-pandas-src contains reference to TMPDIR [buildpaths]

Signed-off-by: Alper Ak <alperyasinak1gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>