src/meta-openembedded:waylandpp: add opengl to REQUIRED_DISTRO_FEATURES
waylandpp needs virtual/libgles2 which is available when opengl
is enabled in mesa recipe, so also add the check for waylandpp.

Fixes:
  ERROR: Nothing PROVIDES 'virtual/libgles2' (but /build/layers/meta-openembedded/meta-oe/recipes-graphics/wayland/waylandpp_1.0.0.bb DEPENDS on or otherwise requires it). Close matches:
    virtual/imlib2
    virtual/libc
    virtual/libsdl2
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'waylandpp', 'virtual/libgles2']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>