src/meta-tensorflow:tensorflow.inc: add write permission to 2 more directories
CAUTION: This email comes from a non Wind River email account!
Do not click links or open attachments unless you recognize the sender and know the content is safe.

Missing write permission prevents the WORKDIR to be deleted, e.g. when recipe becames unreachable

Removing 41 recipes from the core2-64 sysroot: 100% |##########################################################################################################################################################################| Time: 0:00:21
Removing 35 recipes from the qemux86_64 sysroot: 100% |########################################################################################################################################################################| Time: 0:00:00
ERROR: Execution of event handler 'sstate_eventhandler_reachablestamps' failed                                                                                                                                                 | ETA:  0:00:07
Traceback (most recent call last):
  File "/OE/build/oe-core/openembedded-core/meta/classes-global/sstate.bbclass", line 1293, in sstate_eventhandler_reachablestamps
    bb.utils.remove(workdir, recurse = True)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/OE/build/oe-core/bitbake/lib/bb/utils.py", line 751, in remove
    subprocess.check_call(cmd + ['rm', '-rf'] + glob.glob(path))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 421, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rm', '-rf', '/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0']' returned non-zero exit status 1.

ERROR: Command execution failed: Traceback (most recent call last):
  File "/OE/build/oe-core/bitbake/lib/bb/command.py", line 123, in runAsyncCommand
    self.cooker.updateCache()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/OE/build/oe-core/bitbake/lib/bb/cooker.py", line 1646, in updateCache
    bb.event.fire(event, self.databuilder.mcdata[mc])
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/OE/build/oe-core/bitbake/lib/bb/event.py", line 224, in fire
    fire_class_handlers(event, d)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/OE/build/oe-core/bitbake/lib/bb/event.py", line 131, in fire_class_handlers
    execute_handler(name, handler, event, d)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/OE/build/oe-core/bitbake/lib/bb/event.py", line 102, in execute_handler
    ret = handler(event, d)
  File "/OE/build/oe-core/openembedded-core/meta/classes-global/sstate.bbclass", line 1293, in sstate_eventhandler_reachablestamps
    bb.utils.remove(workdir, recurse = True)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/OE/build/oe-core/bitbake/lib/bb/utils.py", line 751, in remove
    subprocess.check_call(cmd + ['rm', '-rf'] + glob.glob(path))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 421, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rm', '-rf', '/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0']' returned non-zero exit status 1.

Summary: There were 2 ERROR messages, returning a non-zero exit code.

OE qemux86-64@ /OE/build/oe-core $ find /OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/python
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/python/schema_py_srcs_no_include_all
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/python/schema_py_srcs_no_include_all/schema_generated.py
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/python/schema_py_srcs_no_include_all/__init__.py
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/tools
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/tools/pip_package
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/tools/pip_package/wheel_house
/OE/build/oe-core/tmp/work/x86_64-linux/tensorflow-native/2.17.0/bazel/output_base/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/tools/pip_package/wheel_house/tensorflow-2.17.0-cp312-cp312-linux_x86_64.whl

Signed-off-by: Martin Jansa <martin.jansagmail.com>