src/meta-virtualization:lxc: fix build failure, failing QA check
The build is failing due to a failing QA check:

  ERROR: lxc-2.0.8-r0 do_package_qa: QA Issue:
  /usr/lib/lxc/ptest/src/tests/lxc-test-may-control contained in
  package lxc-ptest requires /bin/bash, but no providers found in
  RDEPENDS_lxc-ptest? [file-rdeps]

Add bash to the the ptest RDEPENDS.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>