src/meta-cloud-services:python-cinder: Move tgt config files to avoid conflicts
We might have the following warning and error since both tgt and python-
cinder create /etc/tgt/targets.conf. This patch creates conf.d/ under
/etc/tgt/ and puts python-cinder's config file there. tgt's config file
will include it automatically.

warning: Removing tgt-1.0.63+git0+eca74a72d2-r0.0corei7_64 due to
file /etc/tgt/targets.conf conflicting with
python-cinder-7.0.0+git0+61026d4e4f-r0.0corei7_64
error: tgt-dev-1.0.63+git0+eca74a72d2-r0.0 requires tgt =
1.0.63+git0+eca74a72d2-r0.0

Signed-off-by: He Zhe <zhe.hewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>