src/poky:initscripts: Fix regression for requiring /bin/bash
It is not possible to create a rootfs with only busybox + initscipts.
This is a result of a regression from commit
a4b53872a8a9a2743299acbff015f7f2750a69d6 (initscripts: add
/sbin/sushell for systemd service debug-shell).

The /sbin/sushell should just use /bin/sh else you end up with a
problem when creating the end image with a failed smart transaction
shown below:

ERROR: Unable to install packages. Command '/proj/bitbake_build/tmp/sysroots/x86_64-linux/usr/bin/smart --quiet --data-dir=/proj/bitbake_build/tmp/work/qemuarma9-wrs-linux-gnueabi/wrlinux-image-glibc-small/1.0-r1/rootfs/var/lib/smart install -y dropbeararmv7at2_vfp hacarmv7at2_vfp run-postinstsall kernel-modulesqemuarma9 packagegroup-core-bootqemuarma9' returned 1:
error: Can't install initscripts-1.0-r155.0armv7at2_vfp: no package provides /bin/bash

(From OE-Core rev: 4917e36a77bd6821b45db52caa43939d344d92f6)

Signed-off-by: Jason Wessel <jason.wesselwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>