src/meta-openembedded:mongodb: add and fix Upstream-Status
* add 'Upstream-Status: Pending' where it was missing and fix malformatted one
  in 1296.patch

* fixes:
  ERROR: lib32-mongodb-4.4.24-r0 do_patch: QA Issue: Malformed Upstream-Status in patch
  meta-oe/meta-oe/dynamic-layers/meta-python/recipes-dbs/mongodb/mongodb/1296.patch
  Please correct according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status :
  Upstream-Status: submitted https://github.com/mongodb/mongo/pull/1296 [patch-status]
  ERROR: lib32-mongodb-4.4.24-r0 do_patch: QA Issue: Missing Upstream-Status in patch
  meta-oe/meta-oe/dynamic-layers/meta-python/recipes-dbs/mongodb/mongodb/0001-free_mon-Include-missing-cstdint.patch
  Please add according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status . [patch-status]
  ...

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>