src/poky:populate_sdk_base.bbclass: nativesdk-glibc-locale is required on musl too
musl based extensible sdk fails to install

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Your system needs to support the en_US.UTF-8 locale.

The real reason is that its missing locale-archive in buildtools-tarball
hence python3 from buildtools-tarball fails to run bitbake when
installing esdk

(From OE-Core rev: c6e8e13f910544b2a4435d8b9e6dbc65847ef182)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>