src/poky:mobile-broadband-provider-info: fix .pc file conflict
Issue: LIN10-4485

Error: Transaction check error:
  file /usr/share/pkgconfig/mobile-broadband-provider-info.pc from install of \
  lib32-mobile-broadband-provider-info-dev.core2_32 conflicts with file from package \
  mobile-broadband-provider-info-dev.core2_64

(From OE-Core rev: fbb2df435140eafc3fe1ca7419398e3b5ef273c8)

Signed-off-by: Zhixiong Chi <zhixiong.chiwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>