src/meta-openembedded:python3-flask-babel: update to 1.0.0 and consolidate
The python3-werkzeug 1.0.0 requires this package to be updated.
Fixes:
File "/usr/lib/python3.8/site-packages/flask_babel/__init__.py", line 19, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict' from 'werkzeug' (/usr/lib/python3.8/site-packages/werkzeug/__init__.py)

https://github.com/python-babel/flask-babel/issues/162

Signed-off-by: Armin Kuster <akuster808gmail.com>
Acked-by: Trevor Gamblin <trevor.gamblinwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>