src/poky:perf: remove CFLAGS override
definition of __SANE_USERSPACE_TYPES__ was added in kernel source by
commit e3541ec75219819d3235f80125a1a75d798ff6e1
perf tools, powerpc: Fix compile warnings in tests/attr.c

Overriding the CFLAGS makes it impossible for kernel build system to
append to it, thus making the build fail in various ways as:

|     CC /.../perf/1.0-r9/perf-1.0/perf.o
| In file included from builtin.h:4:0,
|                  from perf.c:9:
| util/util.h:74:24: fatal error: lk/debugfs.h: No such file or directory
|  #include <lk/debugfs.h>
|                         ^
| compilation terminated.

(From OE-Core rev: 7e7063e495d6451b46e06d08d16f92d0597a7d11)

Signed-off-by: Ting Liu <ting.liufreescale.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>