src/poky:wpa-supplicant: Add dependency on openssl
Building of wpa-supplicant failed due to missing dependency on openssl:
crypto_openssl.c:10:30: fatal error: openssl/opensslv.h: No such file or directory

(From OE-Core rev: 9d1cdb59cb9fcbc4927f04a226405766ab3c4fc8)

Signed-off-by: Mikhail Durnev <Mikhail_Durnevmentor.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>