src/meta-openembedded:gensio: fix QA issue: non -staticdev package with .a libraries
This fixes a bunch of the following errors:
ERROR: gensio-2.6.4-r0 do_package_qa: QA Issue: non -staticdev package contains static .a library: gensio path '/usr/libexec/gensio/2.6.4/libgensio_xxx.a'

Signed-off-by: Petr Gotthard <petr.gotthardadvantech.cz>
Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit f030642efa8d58b8ef98e2cdd248b9423b8e6570)
Signed-off-by: Armin Kuster <akuster808gmail.com>