src/poky:build-appliance-image: check for xattr feature
The xattr DISTRO_FEATURE is required otherwise a bitbake build will fail due
to a failure with the 'cp' utility:

	Subprocess output:
	cp: cannot preserve extended attributes, cp is built without xattr support

	ERROR: Logfile of failure stored in: /home/builder/poky/build/tmp/work/qemux86_64-poky-linux/packagegroup-base/1.0-r83/temp/log.do_populate_lic.1001
	ERROR: Task (/home/builder/poky/meta/recipes-core/packagegroups/packagegroup-base.bb:do_populate_lic) failed with exit code '1'

(From OE-Core rev: 7e1b2598fedfdc7c9a79c5c94273218f2eedcba9)

Signed-off-by: Trevor Woerner <twoernergmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>