src/meta-cloud-services:python-pyscss: add missing rdepends on python-enum
Add missing rdepends on python-enum or it fails with:
  File "/usr/lib64/python2.7/site-packages/scss/compiler.py", line 7, in <module>
    from enum import Enum
  ImportError: No module named enum

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>