src/poky:distcc: Change SRC_URI
ERROR: distcc-3.2-r0 do_fetch: Fetcher failure: Unable to find revision d8b18df3e9dcbe4f092bed565835d3975e99432c in branch 3.2 even from upstream
ERROR: distcc-3.2-r0 do_fetch: Fetcher failure for URL: 'git://github.com/distcc/distcc.git;branch=3.2'. Unable to fetch URL from any source.
ERROR: distcc-3.2-r0 do_fetch: Function failed: base_do_fetch

[v2]
upstream deleted the branch and the hash no longer exists.

Took the git snapshot from yocto and created a copy on my github.
There was no offical 3.2 release, only rc versions.

(From OE-Core rev: aee44c6b1c36fb1c1f760fec60087933d1e8ea79)

Signed-off-by: Armin Kuster <akustermvista.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>