src/meta-openembedded:goffice: add patch to use pcre_fullinfo instead of pcre_info
* pcre_info was removed in newer pcre and abiword now fails to build
  /usr/lib/libgoffice-0.8.so: undefined reference to pcre_info

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>