src/poky:updated-rc.d: Only add dependencies in target case
Avoid errors like:
  ERROR: Nothing PROVIDES 'nativesdk-update-rc.d' (but virtual:nativesdk:dbus_1.8.18.bb
  DEPENDS on or otherwise requires it).

(From OE-Core rev: 270a1716b02981aad353c266d3d19735fc85cf10)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>