src/poky:package_rpm: Check if file exists before open()
Exception handler tries to read() /etc/passwd file in sysroot
and if file doesn't exist for any reason then it raises FileNotFoundError
exception which mask the original source of the problem and makes
debugging of the issue more difficult.

Fixes:
Exception: FileNotFoundError: [Errno 2] No such file or directory:
'/codebuild/output/src1899304708/src/build/tmp-container/work/core2-64-oe-linux/emqx-bin/4.3.12/recipe-sysroot/etc/passwd'

(From OE-Core rev: 4ad9a0e0b11eb7bc5a3dd45fc8945e094ea949e9)

Signed-off-by: Pavel Zhukov <pavelzhukoff.net>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>