src/poky:gnome-themes-standard: drop .la file as unused
oe-core commit 51b3ee298635b11d5784caaa0ac1c8f4034c25a5
[gnome-themes-standard: Fix packages so dev-pkgs image generation
works] disabled generation of the -dev pkg. Since a libtool archive
file was no longer being picked up by the -dev pkg the build will fail
with a QA issue (if ERROR_QA includes installed-vs-shipped):

ERROR: gnome-themes-standard-3.22.3-r0 do_package: QA Issue:
gnome-themes-standard: Files/directories were installed but not
shipped in any package:
/usr/lib64/gtk-2.0/2.10.0/engines/libadwaita.la

The libtool archive file is mostly useless in modern Linux with a
single shared library file so instead of including this in the -dev
pkg we simply drop it.

(From OE-Core rev: 77797a95569252024fca094d33ae9ecbc833597f)

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>