src/poky:devtool: Fix _copy_file() TypeError
when devtool finish, the _copy_file() failed.
--------------------------------------------
TypeError: _copy_file() got an unexpected keyword argument
'base_outdir'
--------------------------------------------

Fixes: 05f2d5d2ce00 ("devtool: finish: add dry-run option")

(From OE-Core rev: 5e6f4d0d3d314897b8ab2f45b3a78b0da9df99ab)

Signed-off-by: Xiaobing Luo <luoxiaobing0926gmail.com>
Signed-off-by: Luca Ceresoli <luca.ceresolibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit a45d9dc089fb2719ca69b92870917f8c0925f632)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>