src/meta-openembedded:fbset-modes: drop allarch inherit
* setting PACKAGE_ARCH to MACHINE_ARCH together with allarch doesn't work
  well anymore since:
  http://git.openembedded.org/openembedded-core/commit/?id=a23c482cab4f874f4a6a6889716123569eb5ece9
* fixes:
 === Comparing signatures for task do_configure.sigdata between qemux86 and qemuarm ===
ERROR: fbset-modes different signature for task do_configure.sigdata between qemux86 and qemuarm
Task dependencies changed from:
['AR', 'AS', 'B', 'BASEDEPENDS', 'BUILD_AR', 'BUILD_AS', 'BUILD_AS_ARCH', 'BUILD_CC', 'BUILD_CCLD', 'BUILD_CC_ARCH', 'BUILD_CFLAGS', 'BUILD_CPP', 'BUILD_CPPFLAGS', 'BUILD_CXX', 'BUILD_CXXFLAGS', 'BUILD_FC', 'BUILD_LD', 'BUILD_LDFLAGS', 'BUILD_LD_ARCH', 'BUILD_NM', 'BUILD_OPTIMIZATION', 'BUILD_PREFIX', 'BUILD_RANLIB', 'BUILD_STRIP', 'CC', 'CCLD', 'CFLAGS', 'CLEANBROKEN', 'CONFIGURESTAMPFILE', 'CPP', 'CPPFLAGS', 'CXX', 'CXXFLAGS', 'DEPENDS', 'DISABLE_STATIC', 'DISTRO', 'EXTRA_OECONF', 'EXTRA_OEMAKE', 'FC', 'HOST_AS_ARCH', 'HOST_CC_ARCH', 'HOST_LD_ARCH', 'HOST_PREFIX', 'ICECC_AS', 'ICECC_CC', 'ICECC_CXX', 'ICECC_VERSION', 'ICECC_WHICH_AS', 'ICE_PATH', 'LC_ALL', 'LD', 'LDFLAGS', 'LOGFIFO', 'MAKE', 'MLPREFIX', 'NM', 'OBJCOPY', 'OBJDUMP', 'P', 'PACKAGECONFIG',
  'PACKAGE_ARCH', 'PERL_HASH_SEED', 'PKG_CONFIG_DIR', 'PKG_CONFIG_DISABLE_UNINSTALLED', 'PKG_CONFIG_LIBDIR', 'PKG_CONFIG_PATH', 'PKG_CONFIG_SYSROOT_DIR', 'PKG_CONFIG_SYSTEM_INCLUDE_PATH', 'PKG_CONFIG_SYSTEM_LIBRARY_PATH', 'PN', 'PSEUDO_DISABLED', 'PV', 'PYTHONHASHSEED', 'QA_LOGFILE', 'QA_SANE', 'RANLIB', 'READELF', 'RECIPE_SYSROOT_NATIVE', 'S', 'SOURCE_DATE_EPOCH', 'STAGING_BASE_LIBDIR_NATIVE', 'STAGING_BINDIR', 'STAGING_DATADIR', 'STAGING_DIR_NATIVE', 'STAGING_INCDIR_NATIVE', 'STAGING_LIBDIR_NATIVE', 'STRINGS', 'STRIP', 'T', 'TARGET_ARCH', 'TARGET_AS_ARCH', 'TARGET_CC_ARCH', 'TARGET_CFLAGS', 'TARGET_CPPFLAGS', 'TARGET_CXXFLAGS', 'TARGET_LDFLAGS', 'TARGET_LD_ARCH', 'TARGET_OS', 'TARGET_PREFIX', 'TARGET_SYS', 'TARGET_VENDOR', 'TOOLCHAIN_OPTIONS',
  'TZ', 'UNKNOWN_CONFIGURE_WHITELIST', 'base_bindir', 'base_dep_prepend', 'base_do_configure', 'base_libdir', 'base_libdir_native', 'base_prefix', 'base_sbindir', 'baselib', 'bbfatal_log', 'bbnote', 'bbwarn', 'bindir', 'bindir_cross', 'create_path', 'datadir', 'die', 'do_configure[umask]', 'do_qa_configure', 'docdir', 'exec_prefix', 'get_cross_kernel_cc', 'get_icecc', 'icecc_dep_prepend', 'icecc_dir', 'icecc_get_and_check_tool', 'icecc_get_external_tool', 'icecc_get_path_tool', 'icecc_get_tool', 'icecc_get_tool_link', 'icecc_is_allarch', 'icecc_is_cross_canadian', 'icecc_is_kernel', 'icecc_is_native', 'icecc_path', 'icecc_version', 'includedir', 'includedir_native', 'infodir', 'libdir', 'libdir_native', 'libexecdir', 'localstatedir',
  'mandir', 'nonarch_base_libdir', 'nonarch_libdir', 'oe_runmake', 'oe_runmake_call', 'oldincludedir', 'package_qa_handle_error', 'package_qa_write_error', 'prefix', 'prefix_native', 'root_prefix', 'sbindir', 'servicedir', 'set_icecc_env', 'sharedstatedir', 'sysconfdir', 'systemd_system_unitdir', 'systemd_unitdir', 'systemd_user_unitdir', 'use_icecc']
to:
['ABIEXTENSION', 'AR', 'ARMPKGARCH', 'ARMPKGARCH_tune-armv5te', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'AS', 'ASNEEDED', 'B', 'BASEDEPENDS', 'BASE_DEFAULT_DEPS', 'BUILD_AR', 'BUILD_AS', 'BUILD_AS_ARCH', 'BUILD_CC', 'BUILD_CCLD', 'BUILD_CC_ARCH', 'BUILD_CFLAGS', 'BUILD_CPP', 'BUILD_CPPFLAGS', 'BUILD_CXX', 'BUILD_CXXFLAGS', 'BUILD_FC', 'BUILD_LD', 'BUILD_LDFLAGS', 'BUILD_LD_ARCH', 'BUILD_NM', 'BUILD_OPTIMIZATION', 'BUILD_PREFIX', 'BUILD_RANLIB', 'BUILD_STRIP', 'CC', 'CCLD', 'CFLAGS', 'CLEANBROKEN', 'CONFIGURESTAMPFILE', 'CPP', 'CPPFLAGS', 'CXX', 'CXXFLAGS', 'DEBUG_BUILD', 'DEBUG_FLAGS', 'DEBUG_OPTIMIZATION', 'DEBUG_PREFIX_MAP', 'DEFAULTTUNE', 'DEPENDS', 'DISABLE_STATIC', 'DISTRO', 'EXTENDPE', 'EXTRA_OECONF', 'EXTRA_OEMAKE', 'FC', 'FULL_OPTIMIZATION', 'GCCPIE', 'HOST_AS_ARCH', 'HOST_CC_ARCH', 'HOST_LD_ARCH', 'HOST_PREFIX',
  'ICECC_AS', 'ICECC_CC', 'ICECC_CXX', 'ICECC_VERSION', 'ICECC_WHICH_AS', 'ICE_PATH', 'LC_ALL', 'LD', 'LDFLAGS', 'LIBCEXTENSION', 'LINKER_HASH_STYLE', 'LOGFIFO', 'MACHINE', 'MACHINE_ARCH', 'MAKE', 'MLPREFIX', 'NM', 'OBJCOPY', 'OBJDUMP', 'P', 'PACKAGECONFIG', 'PACKAGE_ARCH', 'PE', 'PERL_HASH_SEED', 'PKG_CONFIG_DIR', 'PKG_CONFIG_DISABLE_UNINSTALLED', 'PKG_CONFIG_LIBDIR', 'PKG_CONFIG_PATH', 'PKG_CONFIG_SYSROOT_DIR', 'PKG_CONFIG_SYSTEM_INCLUDE_PATH', 'PKG_CONFIG_SYSTEM_LIBRARY_PATH', 'PN', 'PR', 'PREFERRED_ARM_INSTRUCTION_SET', 'PSEUDO_DISABLED', 'PV', 'PYTHONHASHSEED', 'QA_LOGFILE', 'QA_SANE', 'RANLIB', 'READELF', 'RECIPE_SYSROOT_NATIVE', 'S', 'SECURITY_CFLAGS', 'SECURITY_LDFLAGS', 'SECURITY_PIE_CFLAGS', 'SECURITY_STACK_PROTECTOR', 'SECURITY_STRINGFORMAT', 'SELECTED_OPTIMIZATION', 'SOURCE_DATE_EPOCH', 'STAGING_BASE_LIBDIR_NATIVE', 'STAGING_BINDIR', 'STAGING_DATADIR', 'STAGING_DIR_NATIVE', 'STAGING_INCDIR_NATIVE', 'STAGING_LIBDIR_NATIVE', 'STRINGS', 'STRIP', 'T',
  'TARGET_ARCH', 'TARGET_AS_ARCH', 'TARGET_CC_ARCH', 'TARGET_CFLAGS', 'TARGET_CPPFLAGS', 'TARGET_CXXFLAGS', 'TARGET_LDFLAGS', 'TARGET_LD_ARCH', 'TARGET_LINK_HASH_STYLE', 'TARGET_OS', 'TARGET_PREFIX', 'TARGET_SYS', 'TARGET_VENDOR', 'TOOLCHAIN_OPTIONS', 'TUNE_ARCH', 'TUNE_ASARGS', 'TUNE_CCARGS', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-armv5', 'TUNE_FEATURES_tune-armv5t', 'TUNE_FEATURES_tune-armv5te', 'TUNE_LDARGS', 'TUNE_PKGARCH', 'TZ', 'UNKNOWN_CONFIGURE_WHITELIST', 'base_bindir', 'base_dep_prepend', 'base_do_configure', 'base_libdir', 'base_libdir_native', 'base_prefix', 'base_sbindir', 'baselib', 'bbfatal_log', 'bbnote', 'bbwarn', 'bindir', 'bindir_cross', 'create_path', 'datadir', 'die', 'do_configure[umask]', 'do_qa_configure', 'docdir', 'exec_prefix', 'get_cross_kernel_cc', 'get_icecc', 'icecc_dep_prepend', 'icecc_dir', 'icecc_get_and_check_tool', 'icecc_get_external_tool',
  'icecc_get_path_tool', 'icecc_get_tool', 'icecc_get_tool_link', 'icecc_is_allarch', 'icecc_is_cross_canadian', 'icecc_is_kernel', 'icecc_is_native', 'icecc_path', 'icecc_version', 'includedir', 'includedir_native', 'infodir', 'lcl_maybe_fortify', 'libdir', 'libdir_native', 'libexecdir', 'localstatedir', 'mandir', 'nonarch_base_libdir', 'nonarch_libdir', 'oe_runmake', 'oe_runmake_call', 'oldincludedir', 'package_qa_handle_error', 'package_qa_write_error', 'prefix', 'prefix_native', 'root_prefix', 'sbindir', 'servicedir', 'set_icecc_env', 'sharedstatedir', 'sysconfdir', 'systemd_system_unitdir', 'systemd_unitdir', 'systemd_user_unitdir', 'use_icecc']
basehash changed from ac2e156620321beef53eb90cea8574bc to 5ab527b38214c867bd9574174151c0bf
List of dependencies for variable TARGET_OS changed from 'set()' to '{'ABIEXTENSION', 'LIBCEXTENSION'}'
List of dependencies for variable TARGET_LD_ARCH changed from 'set()' to '{'TUNE_LDARGS'}'
List of dependencies for variable TARGET_LDFLAGS changed from 'set()' to '{'SECURITY_LDFLAGS', 'ASNEEDED', 'TARGET_LINK_HASH_STYLE'}'
List of dependencies for variable BASEDEPENDS changed from '{'base_dep_prepend'}' to '{'BASE_DEFAULT_DEPS', 'base_dep_prepend'}'
changed items: {'BASE_DEFAULT_DEPS'}
List of dependencies for variable TARGET_PREFIX changed from 'set()' to '{'TARGET_SYS'}'
List of dependencies for variable TARGET_AS_ARCH changed from 'set()' to '{'TUNE_ASARGS'}'
List of dependencies for variable PACKAGE_ARCH changed from 'set()' to '{'MACHINE_ARCH'}'
List of dependencies for variable TARGET_CXXFLAGS changed from 'set()' to '{'TARGET_CFLAGS'}'
List of dependencies for variable TARGET_ARCH changed from 'set()' to '{'TUNE_ARCH'}'
List of dependencies for variable TARGET_CC_ARCH changed from 'set()' to '{'SECURITY_CFLAGS', 'TUNE_CCARGS'}'
List of dependencies for variable LDFLAGS changed from 'set()' to '{'TARGET_LDFLAGS'}'
List of dependencies for variable TARGET_CFLAGS changed from 'set()' to '{'SELECTED_OPTIMIZATION', 'TARGET_CPPFLAGS'}'
Dependency on variable PR was added
Dependency on variable PE was added
Dependency on variable ARM_THUMB_OPT was added
Dependency on variable BASE_DEFAULT_DEPS was added
Dependency on variable DEFAULTTUNE was added
Dependency on variable EXTENDPE was added
Dependency on variable ARMPKGARCH was added
Dependency on variable MACHINE_ARCH was added
Dependency on variable TUNE_FEATURES_tune-armv5 was added
Dependency on variable TUNE_FEATURES was added
Dependency on variable TARGET_LINK_HASH_STYLE was added
Dependency on variable lcl_maybe_fortify was added
Dependency on variable DEBUG_OPTIMIZATION was added
Dependency on variable SECURITY_PIE_CFLAGS was added
Dependency on variable SELECTED_OPTIMIZATION was added
Dependency on variable TUNE_CCARGS_MFLOAT was added
Dependency on variable SECURITY_CFLAGS was added
Dependency on variable FULL_OPTIMIZATION was added
Dependency on variable SECURITY_STRINGFORMAT was added
Dependency on variable ASNEEDED was added
Dependency on variable ARMPKGSFX_FPU was added
Dependency on variable GCCPIE was added
Dependency on variable PREFERRED_ARM_INSTRUCTION_SET was added
Dependency on variable TUNE_FEATURES_tune-armv5te was added
Dependency on variable SECURITY_LDFLAGS was added
Dependency on variable TUNE_CCARGS_MFPU was added
Dependency on variable TUNE_ARCH was added
Dependency on variable ABIEXTENSION was added
Dependency on variable LINKER_HASH_STYLE was added
Dependency on variable ARM_M_OPT was added
Dependency on variable ARM_INSTRUCTION_SET was added
Dependency on variable DEBUG_BUILD was added
Dependency on variable DEBUG_PREFIX_MAP was added
Dependency on variable TUNE_PKGARCH was added
Dependency on variable TUNE_FEATURES_tune-armv5t was added
Dependency on variable ARM_THUMB_SUFFIX was added
Dependency on variable SECURITY_STACK_PROTECTOR was added
Dependency on variable LIBCEXTENSION was added
Dependency on variable TUNE_CCARGS was added
Dependency on variable ARMPKGSFX_DSP was added
Dependency on variable ARMPKGARCH_tune-armv5te was added
Dependency on variable ARMPKGSFX_ENDIAN was added
Dependency on variable MACHINE was added
Dependency on variable TUNE_LDARGS was added
Dependency on variable TUNE_ASARGS was added
Dependency on variable ARMPKGSFX_EABI was added
Dependency on variable ARMPKGSFX_THUMB was added
Dependency on variable DEBUG_FLAGS was added
Variable TARGET_OS value changed from 'linux' to 'linux${LIBCEXTENSION}${ABIEXTENSION}'
Variable TARGET_LD_ARCH value changed from 'none' to '${TUNE_LDARGS}'
Variable TARGET_LDFLAGS value changed:
"[-none-] {+-Wl,-O1 ${TARGET_LINK_HASH_STYLE} ${ASNEEDED} ${SECURITY_LDFLAGS}+}"
Variable TARGET_AS_ARCH value changed from 'none' to '${TUNE_ASARGS}'
Variable TARGET_PREFIX value changed from '' to '${TARGET_SYS}-'
Variable PACKAGE_ARCH value changed from 'all' to '${MACHINE_ARCH}'
Variable TARGET_CXXFLAGS value changed from 'none' to '${TARGET_CFLAGS}'
Variable TARGET_ARCH value changed from 'allarch' to '${TUNE_ARCH}'
Variable TARGET_CPPFLAGS value changed from 'none' to ''
Variable TARGET_CC_ARCH value changed:
"[-none-] {+${TUNE_CCARGS} ${SECURITY_CFLAGS}+}"
Variable LDFLAGS value changed from '' to '${TARGET_LDFLAGS}'
Variable TARGET_CFLAGS value changed:
"[-none-] {+${TARGET_CPPFLAGS} ${SELECTED_OPTIMIZATION}+}"
runtaskdeps changed:
fbset/fbset-modes.bb.do_patch with hash 9332ef5e19ea111b5da7669ddc8c0637
 changed to
fbset/fbset-modes.bb.do_patch with hash 9a59ced6a021e0bbaa28f25f7617f9e7
fbset/fbset-modes.bb.do_prepare_recipe_sysroot with hash 2c39514f57b3f732b820bcbb703142aa
 changed to
fbset/fbset-modes.bb.do_prepare_recipe_sysroot with hash 7d5ab8f06ede5d28de82a4a2b1072c6a
Hash for dependent task fbset/fbset-modes.bb.do_patch changed from 9332ef5e19ea111b5da7669ddc8c0637 to 9a59ced6a021e0bbaa28f25f7617f9e7
Hash for dependent task fbset/fbset-modes.bb.do_prepare_recipe_sysroot changed from 2c39514f57b3f732b820bcbb703142aa to 7d5ab8f06ede5d28de82a4a2b1072c6a

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>