src/meta-cloud-services:tgt: Fix the path of header files check
Current Makefile will check headers on host instead of Yocto sysroot, following
error appears. Change the path of header check.
| bs_aio.c:34:20: fatal error: libaio.h: No such file or directory
| #include <libaio.h>
|                     ^
| compilation terminated.

Signed-off-by: Zhenhua Luo <zhenhua.luofreescale.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>