src/meta-openembedded:openhpi: explicitly disable ov-rest plugin
* since elfutils upgrade to 0.192 in:
  https://git.openembedded.org/openembedded-core/commit/?id=1d6ac3c811798732e6addc798656bbe104661d77
  json-c is detected in RSS and ov-rest plugin gets enabled, but fails to build:

../../../openhpi-3.8.0/plugins/ov_rest/ov_rest_event.c:78:10: fatal error: amqp_ssl_socket.h: No such file or directory
   78 | #include <amqp_ssl_socket.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

../../../openhpi-3.8.0/plugins/ov_rest/ov_rest_re_discover.c:707:23: error: initialization of 'SaErrorT' {aka 'int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  707 |         SaErrorT rv = NULL;
      |                       ^~~~

* keep it explicitly disabled as it was disabled before
* add rabbitmq-c dependency for the first issue, the 2nd issue could be
  worked around by:
  # openhpi-3.8.0/plugins/ov_rest/ov_rest_re_discover.c:707:23: error: initialization of 'SaErrorT' {aka 'int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  CFLAGS += "-Wno-error=int-conversion"
  or better fixed properly by someone actually using this recipe

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>