src/poky:xf86-video-intel: update to latest
For changes, please see:

https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/log/?qt=range&q=e4fe79cf0d9a05ee3f3a027148ef0aeb2b1b34e1...0932a6b37ba6d5c9e916a1cb6ab89c3205b81a0c

Enable sna by default and remove upstreamed patches.

Also include a patch from fedora to fix compile issues when using
qemux86 which doesn't enable sse2 leading to gcc refusing to
inline vertex_emit_2s in emit_vertex because they are defined as:

  static __attribute__((always_inline)) void
  vertex_emit_2s(struct sna *sna, int16_t x, int16_t y)

  __attribute__((target("sse2,fpmath=sse"))) __attribute__((always_inline))
  static void emit_vertex(/* omitted */)

leading to errors like:

| In file included from ../../../git/src/sna/gen4_vertex.c:34:
| ../../../git/src/sna/gen4_vertex.c: In function 'emit_vertex':
| ../../../git/src/sna/sna_render_inline.h:40:26: error: inlining failed in call to always_inline 'vertex_emit_2s': target specific option mismatch
|  static force_inline void vertex_emit_2s(struct sna *sna, int16_t x, int16_t y)
|                           ^~~~~~~~~~~~~~
| ../../../git/src/sna/gen4_vertex.c:308:25: note: called from here
|  #define OUT_VERTEX(x,y) vertex_emit_2s(sna, x,y) /* XXX assert(!too_large(x, y)); */
|                          ^~~~~~~~~~~~~~~~~~~~~~~~
| ../../../git/src/sna/gen4_vertex.c:360:2: note: in expansion of macro 'OUT_VERTEX'
|   OUT_VERTEX(dstX, dstY);
|   ^~~~~~~~~~

(From OE-Core rev: a181b36bf2357c5f7d5835df2f828ff1e0007dc6)

Signed-off-by: Anuj Mittal <anuj.mittalintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>