src/meta-cloud-services:dhcp: fix build error
dhcp in oe-core has been upgrade to 4.3.2, so the following error will be caught.

 ERROR: No recipes available for:
   /yocto/meta-cloud-services/recipes-connectivity/dhcp/dhcp_4.3.1.bbappend

Signed-off-by: Bian Naimeng <biannmcn.fujitsu.com>