src/poky:glibc-package.inc: Add linux-libc-headers-dev to glibc-dev
Without linux-libc-headers-dev being added to the libc6-dev as a RDEPENDS,
the system may fail to install the necessary libc headers.

This can happen when NO_RECOMMENDATIONS = "1" is defined.

During the 'testsdk' this results in failures that look like:

    fatal error: linux/errno.h: No such file or directory
    # include <linux/errno.h>
              ^~~~~~~~~~~~~~~

This also matches the behavior of musl, which does not suffer from this
problem.

(From OE-Core rev: ad31c908c8267166ce6cce9d5085ef2ac099a6c5)

Signed-off-by: Mark Hatle <mark.hatlewindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>