src/meta-virtualization:vgabios: don't override the compiler ldflags
Fix for building biossums on genericx86-64 machine, due to QA issue:
ERROR: QA Issue: No GNU_HASH in the elf binary:
'.../0.7a-r0/packages-split/biossums/usr/bin/biossums' [ldflags]
caused by overriding LDFLAGS variable to empty value in project's makefile.

In consequence there's missing LDFLAGS settings from bitbake (including
-Wl,--hash-style=gnu, which causes showing this QA).

Signed-off-by: Dariusz Pelowski <dariusz.pelowskigmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>