src/poky:apt: Fix do_compile error when enable ccache
When apt was upgraded, the '-DCMAKE_DISABLE_FIND_PACKAGE_Zstd=True'
was dropped. However, it was there to fix do_compile error when ccache is
enabled. See details in the following commit.

"""
commit 0aa7d612b8b7e5f14b4ed38f2a32b3f7eefca31c
Author: Robert Yang <liezhi.yangwindriver.com>
Date:   Tue Jan 19 01:23:45 2021 -0800

    apt: Fix do_compile error when enable ccache

    Fixed:
        apt-pkg/libapt-pkg.so.5.0.2: undefined reference to `ZSTD_endStream'
	    collect2: error: ld returned 1 exit status

    This is because ccache-native depends on zstd-native which makes apt wronly
        find it. Disable zstd for apt to fix the problem.
"""

Now we are meeting do_compile failure again when enabling ccache, so add it
back to solve the problem.

(From OE-Core rev: f8aa80a8fc777464f20e864b53af0582487d0387)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>