src/meta-openembedded:packagegroup-meta-multimedia: Remove library only packages from rdeps
Because they get renamed, it is better to ignore them and let a
dependency build them

Fixes errors like
ERROR: packagegroup-meta-multimedia-1.0-r0 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (gssdp to libgssdp-1.2-0)

Signed-off-by: Khem Raj <raj.khemgmail.com>