src/meta-openembedded:khronos-cts.inc: respect MLPREFIX when appending DEPENDS with anonymous python
* this causes 2 issues:
  lib32-opengl-es-cts depending on 64bit wayland and wayland-protocols:

  $ bitbake-getvar -r lib32-opengl-es-cts DEPENDS
  #
  # $DEPENDS [14 operations]
  #   set /OE/build/oe-core/openembedded-core/meta/conf/bitbake.conf:309
  #     ""
  #   set /OE/build/oe-core/openembedded-core/meta/conf/documentation.conf:137
  #     [doc] "Lists a recipe's build-time dependencies (i.e. other recipe files)."
  #   :prepend /OE/build/oe-core/openembedded-core/meta/classes-global/base.bbclass:57
  #     "${BASEDEPENDS} "
  #   :prepend /OE/build/oe-core/openembedded-core/meta/classes-recipe/pkgconfig.bbclass:7
  #     "pkgconfig-native "
  #   :prepend /OE/build/oe-core/openembedded-core/meta/classes-recipe/cmake.bbclass:10
  #     "cmake-native "
  #   :append /OE/build/oe-core/openembedded-core/meta/classes-recipe/python3native.bbclass:11
  #     " python3-native "
  #   append /OE/build/oe-core/meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/khronos-cts.inc:28
  #     "python3-lxml-native libpng zlib virtual/libgles2 qemu-native"
  #   :append[libc-musl] /OE/build/oe-core/meta-openembedded/meta-oe/recipes-graphics/vk-gl-cts/khronos-cts.inc:38
  #     " libexecinfo"
  #   rename (to) classextend.py:108 [map_depends_variable]
  #     "DEPENDS_NONML"
  #   set classextend.py:109 [map_depends_variable]
  #     "${oe.classextend.get_depends('DEPENDS', d)}"
  #   append classextend.py:110 [map_depends_variable]
  #     [vardeps] " DEPENDS_NONML"
  #   append cmake.bbclass:25 [__anon_30__OE_build_oe_core_openembedded_core_meta_classes_recipe_cmake_bbclass]
  #     " ninja-native"
  #   append khronos-cts.inc:77 [__anon_80__OE_build_oe_core_meta_openembedded_meta_oe_recipes_graphics_vk_gl_cts_khronos_cts_inc]
  #     " wayland-native wayland wayland-protocols"
  #   append khronos-cts.inc:79 [__anon_80__OE_build_oe_core_meta_openembedded_meta_oe_recipes_graphics_vk_gl_cts_khronos_cts_inc]
  #     " virtual/libx11 virtual/egl "
  # pre-expansion value:
  #   "${oe.classextend.get_depends('DEPENDS', d)} ninja-native wayland-native wayland wayland-protocols virtual/libx11 virtual/egl "
  DEPENDS="cmake-native lib32-libpng pkgconfig-native python3-lxml-native python3-native qemu-native virtual/lib32-arm-oemllib32-linux-gnueabi-compilerlibs virtual/arm-oemllib32-linux-gnueabi-gcc virtual/lib32-libc virtual/lib32-libgles2 lib32-zlib ninja-native wayland-native wayland wayland-protocols virtual/libx11 virtual/egl "

* lib32-opengl-es-cts-dev runtime depending on 64bit wayland-dev wayland-protocols-dev
  as caught by multilib QA check:

  ERROR: QA Issue: lib32-opengl-es-cts package lib32-opengl-es-cts-dev - suspicious values 'wayland-dev wayland-protocols-dev' in RRECOMMENDS [multilib]

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>