src/meta-openembedded:python3-wxgtk4: Needs x11 for sip module
sip/cpp/sip_corewxWindow.cpp requires gdk/gdkx.h which wont be built
when gtk is built without x11, therefore require x11 when building this
recipe, if gdkx.h is removed form includes then it fails

../../../../sip/cpp/sip_corewxWindow.cpp:56:16: error: unknown type name 'XID'
        static XID GetXWindow(const wxWindow* wxwin) {
               ^
../../../../sip/cpp/sip_corewxWindow.cpp:59:28: error: use of undeclared identifier 'GDK_WINDOW_XID'
                    return GDK_WINDOW_XID(gtk_widget_get_window((wxwin)->m_wxwindow));
                           ^
../../../../sip/cpp/sip_corewxWindow.cpp:64:28: error: use of undeclared identifier 'GDK_WINDOW_XID'
                    return GDK_WINDOW_XID(gtk_widget_get_window((wxwin)->m_widget));
                           ^
so it is using it and will need some work to get it going without x11
until then disable building it on non-x11 distros

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Robert Yang <liezhi.yangwindriver.com>