src/poky:libaio: Extend to native
lvm2 currently requires libaio. So building lvm2-native will result in
the following error.

  ERROR: Required build target 'lvm2-native' has no buildable providers.
  Missing or unbuildable dependency chain was: ['lvm2-native', 'libaio-native']

Extend libaio to native to fix this issue.

(From OE-Core rev: fe871d23c2714e66a1f5e2428a16e742ca40fc62)

Signed-off-by: Peter Kjellerstedt <peter.kjellerstedtaxis.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>