src/poky:numactl: Link with libatomic on rv64/rv32
bring a missing commit from meta-oe

Fixes
riscv64-yoe-linux/10.2.0/ld: ./.libs/libnuma.so: undefined reference to `__atomic_fetch_and_1'

(From OE-Core rev: ea70d7f8f78cd793242cf6804840507d2ebd2871)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>