src/meta-openembedded:python3-pyruvate: Fix build with mips
mips/glibc systems have interesting problem where dev_t is not defined
properly for O32 ABI [1], therefore address it for libsystemd crate, it
works fine for musl

Fixes
error[E0308]: mismatched types
   --> /usr/src/debug/python3-pyruvate/1.1.2-r0/cargo_home/bitbake/libsystemd-0.4.1/src/logging.rs:296:25
    |
296 |                 device: stat.st_dev,
    |                         ^^^^^^^^^^^ expected `u64`, found `u32`

[1] https://sourceware.org/bugzilla/show_bug.cgi?id=17786

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Tim Orling <tim.orlingkonsulko.com>
Signed-off-by: Trevor Gamblin <trevor.gamblinwindriver.com>