src/poky:kernel.bbclass: Use KERNEL_STRIP instead of STRIP
Kernel uses its own variables KERNEL_* instead of general toolchain env
variables, therefore use KERNEL_STRIP here explicitly, Problems happen
when using llvm-strip as default STRIP in distro settings, since kernel
defaults to using gcc, system does not stage llvm/clang toolchain into
kernel's staging sysroot and this function ends up with

FileNotFoundError: [Errno 2] No such file or directory: 'riscv64-yoe-linux-llvm-strip'

(From OE-Core rev: 2db0ef8fe6381c893791ad645748f6e7c8134e5f)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Bruce Ashfield <bruce.ashfieldgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>