src/meta-openembedded:mariadb: move /usr/share/mysql to /usr/share/mariadb
Fix error:
$mariadb-install-db --basedir=/usr
FATAL ERROR: Could not find /usr/share/mariadb/fill_help_tables.sql

Upstream commit [1] move /usr/share/mysql to /usr/share/mariadb, this
make related files split into wrong package, and not installed by
default, so cause above error

[1] https://github.com/MariaDB/server/commit/320a4b52c9c73a37b3553cec6a9d170924957c36

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>