src/meta-openembedded:python3-pdm-build-locked: Add recipe
* backporting new recipes is against stable policy, but
  https://git.openembedded.org/meta-openembedded/commit/?h=styhead&id=cb58461c8f9067247d630ec385851ed9c3889f79
  was backported and added this dependency, so now styhead is failing with:

ERROR: Nothing PROVIDES 'python3-pdm-build-locked-native' (but
meta-oe/meta-python/recipes-devtools/python/python3-pdm_2.19.1.bb
DEPENDS on or otherwise requires it). Close matches:
  python3-build-native
  python3-filelock-native
  python3-pdm-backend-native

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>