src/meta-openembedded:libyang: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/include/libyang/config.h conflicts between attempted installs of libyang-dev-2.1.55-r0.core2_64 and lib32-libyang-dev-2.1.55-r0.i686

The differences of config.h are as follows:
@@ -27,8 +27,8 @@
 /** plugins */
 #define LYPLG_SUFFIX ".so"
 #define LYPLG_SUFFIX_LEN (sizeof LYPLG_SUFFIX - 1)
-#define LYPLG_TYPE_DIR "/usr/lib/libyang/types"
-#define LYPLG_EXT_DIR "/usr/lib/libyang/extensions"
+#define LYPLG_TYPE_DIR "/usr/lib64/libyang/types"
+#define LYPLG_EXT_DIR "/usr/lib64/libyang/extensions"

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>