src/poky:linux-yocto/6.12: yaffs2: fix module build
Integrating the following commit(s) to linux-yocto/6.12:

1/1 [
    Author: Mikko Rapeli
    Email: mikko.rapelilinaro.org
    Subject: yaffs2: switch from readlink_copy() to vfs_readlink()
    Date: Fri, 14 Mar 2025 10:33:42 +0200

    To compile also as module. Fixes:

    ERROR: modpost: "readlink_copy" [fs/yaffs2/yaffs.ko] undefined!

    Signed-off-by: Mikko Rapeli <mikko.rapelilinaro.org>
    Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>
]

(From OE-Core rev: 276922ca1957b8e4234fd3e4884b3a2bcd4017fe)

Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>