src/meta-openembedded:blueman: add RDEPEND on python3-fcntl
After updating current poky master python3-fcntl is not installed
into my image anymore. Blueman-applet fails to run with
Error: No module named 'fcntl''Module fcntl not found'

Signed-off-by: Markus Volk <f_l_kt-online.de>
Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit 25c38607014f2d325884ad003c96237906aefa48)
Signed-off-by: Armin Kuster <akuster808gmail.com>