src/meta-virtualization:cloud-init: fix usrmerge QA error:
* respect udevdir variable
* with usrmerge cloud-init triggers QA error:
  ERROR: cloud-init-20.3-r0 do_package_qa: QA Issue: cloud-init package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
  ERROR: cloud-init-20.3-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
  because of:
  /lib/udev/rules.d/66-azure-ephemeral.rules

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>