src/meta-intel:libxcam: Fix compilation error due to unrecognized micros
Vulkan micros was not recognized during compilation.
Log as follows

| x86_64-poky-linux-libtool: compile:  x86_64-poky-linux-g++ -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/pokybuild/yocto-autobuilder-new/yocto-worker/nightly-meta-intel-world/build/build/tmp/work/corei7-64-poky-linux/libxcam/1.4.0-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../../git/modules/vulkan -I../.. -fPIC -Wall -fstack-protector -std=c++0x -I../../../git/xcore -I../../../git/modules -I../../../git/shaders/spv -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/pokybuild/yocto-autobuilder-new/yocto-worker/nightly-meta-intel-world/build/build/tmp/work/corei7-64-poky-linux/libxcam/1.4.0-r0=/usr/src/debug/libxcam/1.4.0-r0 -fdebug-prefix-map=/home/pokybuild/yocto-autobuilder-new/yocto-worker/nightly-meta-intel-world/build/build/tmp/work/corei7-64-poky-linux/libxcam/1.4.0-r0=/usr/src/debug/libxcam/1.4.0-r0 -fdebug-prefix-map=/home/pokybuild/yocto-autobuilder-new/yocto-worker/nightly-meta-intel-world/build/build/tmp/work/corei7-64-poky-linux/libxcam/1.4.0-r0/recipe-sysroot= -fdebug-prefix-map=/home/pokybuild/yocto-autobuilder-new/yocto-worker/nightly-meta-intel-world/build/build/tmp/work/corei7-64-poky-linux/libxcam/1.4.0-r0/recipe-sysroot-native= -fvisibility-inlines-hidden -c ../../../git/modules/vulkan/vk_geomap_handler.cpp  -fPIC -DPIC -o .libs/libxcam_vulkan_la-vk_geomap_handler.o
| ../../../git/modules/vulkan/vk_instance.cpp: In member function 'XCamReturn XCam::VKInstance::query_physical_info()':
| ../../../git/modules/vulkan/vk_instance.cpp:134:30: error: 'VK_PHYSICAL_DEVICE_TYPE_RANGE_SIZE' was not declared in this scope; did you mean 'VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM'?
|   134 |     VkPhysicalDevice gpu_dev[VK_PHYSICAL_DEVICE_TYPE_RANGE_SIZE] = {};
|       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                              VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM
| ../../../git/modules/vulkan/vk_instance.cpp:140:35: error: 'VK_PHYSICAL_DEVICE_TYPE_BEGIN_RANGE' was not declared in this scope; did you mean 'VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM'?
|   140 |         if (dev_prop.deviceType < VK_PHYSICAL_DEVICE_TYPE_BEGIN_RANGE ||
|       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                   VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM
| ../../../git/modules/vulkan/vk_instance.cpp:141:39: error: 'VK_PHYSICAL_DEVICE_TYPE_END_RANGE' was not declared in this scope; did you mean 'VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM'?
|   141 |                 dev_prop.deviceType > VK_PHYSICAL_DEVICE_TYPE_END_RANGE) {
|       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                       VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM
| ../../../git/modules/vulkan/vk_instance.cpp:144:13: error: 'gpu_dev' was not declared in this scope
|   144 |         if (gpu_dev[dev_prop.deviceType]) {
|       |             ^~~~~~~
| ../../../git/modules/vulkan/vk_instance.cpp:150:9: error: 'gpu_dev' was not declared in this scope
|   150 |         gpu_dev[dev_prop.deviceType] = devs[i];
|       |         ^~~~~~~
| ../../../git/modules/vulkan/vk_instance.cpp:158:9: error: 'gpu_dev' was not declared in this scope
|   158 |     if (gpu_dev[VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU])
|       |         ^~~~~~~

Signed-off-by: Mohamad Noor Alim Hussin <mohamad.noor.alim.hussinintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>