src/meta-openembedded:mariadb: change socket location in my.cnf
Change socket location to /var/lib/mysql/mysql.sock. Otherwise, we
could spot errors in systemd systems like below.

mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/tmp/mysql.sock' exists!

This is because mysqld.service is using PrivateTmp=true.

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>