src/poky:gstreamer1.0-plugins-bad: upgrade 1.24.12 -> 1.26.0
- enable analytics since gstreamer1.0-python depend on it now
- explicitly diable options that new added in meson_options.txt
  - lcevcdecoder
  - lcevcencoder
  - tensordecoders
  - nvcomp
  - nvdswrapper
  - svtjpegxs
  - webview2
  - aja
  - cuda-nvmm
  - d3d12
- add backport patch to fix undefined reference to `__atomic_fetch_add_8' issue
  This patch is part of upstream commit
  https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/8637/commits?commit_id=f2b5c0b6020b50f5173e449b45a6f
7a7be31c48f

(From OE-Core rev: 527f58c8d0aa0c1b516ae47feffa406e32dbd81f)

Signed-off-by: Lei Maohui <leimaohuifujitsu.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>