src/poky:weston: Add a knob to control simple clients
Some graphics driver implementations ( e.g sgx ) do not yet support APIs from mesa
21.x, and some portions of weston simple clients depend on these APIs,
therefore introduce a way to specify all or a selection fo clients to
build

Fixes

clients/weston-simple-dmabuf-feedback.p/simple-dmabuf-
feedback.c.o: in function `create_dmabuf_buffer':
| simple-dmabuf-feedback.c:(.text+0x1076): undefined reference to `gbm_bo_get_fd_for_plane'

(From OE-Core rev: 400aae43d08f0b9f787ac0d21cb3c97058d76748)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>