src/meta-openembedded:libxaw: upgrade to 1.0.10 to fix -Werror=pointer-to-int-cast when building for x86-64
* 1.0.9 fails with:
  | XawIm.c:1410:23: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  | XawIm.c:1415:23: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
* fixed upstream:
  http://cgit.freedesktop.org/xorg/lib/libXaw/commit/?id=49c0a2441946f0d70fbd2612f193c95b84dde102
* COPYING changed only formally, stripping trailing spaces in
  http://cgit.freedesktop.org/xorg/lib/libXaw/commit/COPYING?id=37ffe69b10ae29e8f91de6ef647d06804b9d159b

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>