src/poky:poky.yaml.in: add missing locales dependency
This is a requirement for building the documentation, otherwise we get
(on Ubuntu 24.04):

     File "/usr/lib/python3.12/locale.py", line 615, in setlocale
       return _setlocale(category, locale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   locale.Error: unsupported locale setting

(From yocto-docs rev: 0943a7b67ef0012b5d9badc15e0c579dbb9014ae)

Signed-off-by: Antonin Godard <antonin.godardbootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>