src/meta-openembedded:kexec-tools-klibc: Deliberately add -O2
This helps the compiler to be more aggressive and do the expected
optimizations to remove unused code which otherwise gets flagged on some
architectures e.g. armv7l

errors like
undefined reference to `bad_unaligned_access_length'

Also see
http://lists.infradead.org/pipermail/kexec/2009-August/003488.html

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Andrea Adami <andrea.adamigmail.com>