src/meta-virtualization:crun: update to 1.4.3
Bumping crun to version 1.4.3-4-g3b3061a, which comprises the following commits:

    77df89b docs: update known issues with CRI and side-cars
    164d753 wasm, kubernetes: support wasm for kubernetes infrastructure with side-cars
    61c9600 NEWS: tag 1.4.3
    040c59f chore(utils): add pointer casts to avoid C++ permissive mode
    16850e4 build: fix bashism in configure.ac
    e094499 test: fix CI
    22284a9 tests: add codespell tests
    37f13e3 crun.1.md: fix typo
    8fca8bf tests: add fuzzing for idmapped mounts option
    abfdf1f fuzzing: move chdir to Dockerfile
    d935d0a linux: move parsing to separate function
    5c7165a centos9: enable only needed repo
    160e626 centos8: enable only needed repo
    648b132 tests: add tests for idmapped mounts
    916c5cd tests: add check for file ownership
    934e19a tests: add feature check for idmapped mounts
    bf06c8c linux: support options to idmap
    e1ee353 test, container-delete: ignore warn for cgroupv1 when cgroup cleanup fails
    4355edc test: add a test for crun delete
    cdc4f6a utils, rmdir-all: transfer ownership and responsiblity of fd to rmdir_all_fd
    bb5bc67 linux: open source bind mount in the host
    df2fecd cgroup-destory: terminate infinite loop and relay error back to callee
    44d7816 cgroup-destroy: bump delay while deleting from 0.1ms to 10ms
    ec9fa1c Remove ignored arguments
    9854c71 Fix compilation error with seccomp
    58d33b8 crio-tests: skip userns tests with auto annotation
    b3301ad crio-tests: use golang 1.17.6
    192ff3e cri-o: remove locking to a specific commit in CI and use master
    f6fbc8f NEWS: tag 1.4.2
    4029e63 utils: check for dup error
    83668f1 linux: create_missing_devs creates /dev/console
    0b09d62 utils: always create trailing file
    5c47eac container: ignore EROFS when chowning std stream files
    8ff9652 linux: validate sysctls before applying them
    2f5be74 python: fix build
    da28cf1 container: attempt find_executable after setresuid
    9646fde utils: drop const from find_executable
    8026135 NEWS: tag 1.4.1
    8711fbd utils: add a len argument to get_current_timestamp
    b5987ee utils: add printf attribute to xasprintf
    e9ba4ae libcrun: add printf attribute to error functions
    2ca2d06 utils: add attribute malloc to x.*alloc.* functions
    ece4431 utils: add the sentinel attribute to append_paths
    bb57968 cgroup: do not lookup string twice
    d74c5e4 wasm: add docs and example for using crun wasm support on kubernetes
    78384da tests/oci-validation: optimize build
    c7aac36 Revert "oci-validation: checkout last working commit for runtime-tools"
    4cd65c3 utils: drop check for invalid path
    90c6b1f tests/fuzzing/run-tests.sh: fix
    e65f285 ci: add shellcheck job
    b1c520c tests/*/*.sh: add set -e, fix shellcheck warns
    1613f4e tests/cri-o: don't remove non-existing files
    ff3e33b tests/fuzzing: nits
    28c5f89 tests/oci-validation: rename script to run-tests.sh
    2bf7a93 tests/*/*.sh: rm redundant cd
    a51137c ci/gha: skip installing deps if Dockefile is used
    209fe89 ci/gha: don't start docker
    9174557 .github/workflows/test.yaml: nits
    b97d397 errors: use printf compiler annotation
    f12a5ac linux: fix lookup for namespace
    acc5f87 linux: skip setns_with_pidfd with explicit paths
    5f924cb container: allow delete while in created state
    cc70b0a container: merge two if blocks
    6aff973 cgroups: skip setting cpu limits if shares==0
    5930bfa cgroup: append the sd error message in the error
    c9f0b16 gha: simplify deps install
    08b621f tests/podman: exclude --ip6 test case
    1da6b96 Fix some typos found by codespell
    fd6da89 src: rename libcrun_container_kill_all to libcrun_container_killall
    dfd5dae libcrun: unexport str2sig
    21a8daf libcrun: let libcrun_container_kill* accept a string
    dd80179 libcrun: unexport append_paths
    eada263 tests: skip sd_notify tests without systemd
    8ead30f ci: enable codeql analysis
    3a1da09 .github: fix ci build
    a834e9b .github: test --enable-shared
    95b482f src: export some symbols used by crun
    7f37f2e src/libcrun/linux.c:425:77: error: 'OPEN_TREE_CLOEXEC' undeclared (first use in this function); did you mean 'OPEN_TREE_CLONE'?
    3daded0 NEWS: tag 1.4
    a400e8b libocispec: sync from upstream
    76271c9 cgroup: initialize status
    d583bdc utils: fix path check
    2b74dc1 handler: add support for running handlers on kubernetes with containerd
    9b25f52 tests: extend checkpoint/restore test with pre-dump
    587d0b2 tests: add memhog command to init
    fb2a7ed docs: add pre-copy migration options to the man page
    0683fec checkpoint: add pre-dump support
    7ecb4b0 handlers, wasm: add lost support for run.oci.handler=wasm
    020ee61 tests: add tests for CPUShares/CPUWeight on systemd
    58b8879 state: export systemd scope
    3adb2d5 tests: allow to override cgroup manager
    bcbc72d cgroup-systemd: update CPUShares/CPUWeight
    2ba3106 cgroup: add custom update_resources
    2d7a495 update: fix shares file name
    ec70d28 cgroup-systemd: set CPUWeight/CPUShares on the scope cgroup
    4012668 cgroup-resources: move CONVERT_SHARES_TO_CGROUPS_V2 to function
    77318e4 cgroup: add function to write to the files
    6457228 tests: add CRI-O integration tests to the CI
    d6ab372 configure.ac: mark unused variable
    cb4152d ebpf: fix build on 32 bits arches
    2eafdff cgroup: ignore swap limit if it is not enabled
    62e84d8 nix: lock nix version to last working release
    1efb0f9 linux: fix join cgroup v1
    f72414e crun, spec: allow override file name
    5231a30 utils: retry openat2 on EAGAIN
    782fb02 crun: load custom handlers
    e6fda97 build: define CRUN_LIBDIR
    af950dd handlers: support load from .so files
    6d093a0 handlers: split each handler to its own file
    46fb105 utils: remove hardcoded check for wasm
    8f9337e crun, libcrun: move handlers behind an interface
    fd0e171 handler: split libcrun_configure_wasm
    4eb1f03 container: move custom handlers code to new file
    2063305 wasmedge: The wasmedge.h is moved to wasmedge/wasmedge.h
    2b4dfef container, handler: close files marked with O_CLOEXEC
    4898342 linux, exec: try setns with pidfd
    a14ae9e linux: move join namespaces to a new function
    a32286c linux, exec: use CLONE_INTO_CGROUP
    cb5bf95 linux: use clone3 if available
    0e2eda2 tests: fail fuzzing test on crashes
    74a21ed ebpf: handle missing access string
    c1127a3 container: propagate close for ready-fd
    c9c89c6 container: wait_process accepts a struct
    9bf58f2 container: replace sprintf with snprintf
    3191e49 container: drop argument for write_container_status
    91b47f6 container: replace same failure code with a goto
    b5405fc linux: improve detection of /dev target
    dcc87a3 cgroup: move errors check to helper
    0af034d cgroup: hide create/destroy behind a struct
    f95e56a cgroup: move cgroupfs code to new file
    98e4e46 cgroup: move cgroup setup code to new file
    c3119e7 cgroup: move more functions to cgroup-utils
    0272dae cgroup: move setting resources to new file
    80925dc cgroup: move some functions to a new file
    9c014c6 cgroup: rearrange code
    24f6b40 cgroup: quote file names
    ed31849 cgroup: separate each cleanup to a different function
    d9eba41 cgroup: drop argument from libcrun_cgroup_destroy
    f47d933 cgroup: split systemd code to a new file
    aed4362 cgroup: drop unused function
    384cf2a cgroup: drop usage of raw paths
    1f313a8 libcrun: new function libcrun_container_read_pids
    ce7dedf cgroup: move returned data to different struct
    e2670b4 cgroup: drop argument delegate_cgroup
    22d9dcb cgroup: drop argument systemd_subgroup
    a0d4d9f cgroup: drop unused argument create_if_missing
    dc135cf cgroup: drop cgroup_mode argument
    4dcbf43 cgroup: remove unused argument
    16db42f libcrun: unexport unused functions
    4b18425 Also run clang-format on *.c files in tests/
    abdeabf container: allow libcrun_run_linux_container to call final _exit() for handlers
    2d177df container, exec: refactor to new function
    d78dff2 container: attempt chdir twice
    c9052f2 container: make chdir error clearer
    78cf48b linux: use sd_notify_barrier if available
    0fa6447 libocispec: sync with recent commits
    40e4736 utils: move safe_openat fallback to separate function
    82d2170 mounts: handle paths with multiple slashes
    79699be utils: write_file truncates existing files
    ef37d51 linux: Enter specified cgroup namespace
    a36bcdd tests: disable podman unuseful test
    53f2615 .github: use a bind mount for /var dirs
    5566520 tests: add build test for centos:stream9
    940705f tests, centos8: use centos:stream8
    0e99990 Change podman branch to fix CI
    1575f2f Add file-locks checkpoint/restore option
    d7029af linux: replace mounts lookup with gperf hashing
    5511255 linux: support more recursive options
    2dbce9b linux: use bool for is_user_ns
    827b873 linux: new mount option "idmap"
    02938ac linux: add function to send mounts from the host
    b5fc60e linux: provide cleanup private data callback
    a5a2ca5 linux: generalize opening mounts earlier
    4523486 linux: silence warning
    a01a03a tests: update podman
    3c6d57d wasmedge: fix error message if VM fails to get valid result object
    b48b654 crun: show if version supports wasm with configured runtime
    365dc57 linux: new mount option "rro"
    85c5bc9 linux: fix a race when saving external descriptors
    825108e wasm: add support for wasmedge runtime
    33e75d0 fix build error on ubuntu
    e1c7293 clang-check: refactor to suppress -Wunused-but-set-variable where needed
    575c4a6 ci: use latest docker with seccomp profiles supporting clone3
    8e5757a NEWS: tag 1.3
    685078a tests: temporarily switch to fedora:34
    9ea94e9 wasm: allow wasi modules to read args from config
    76759f1 fix status.h compile error in C++
    952913b wasm: replace printf while relaying output to stdout with safe_write
    152a3fc linux: bind mount the current cgroup path
    ce211c5 linux: fix mounting cgroup2 with --net=host
    e31ab81 wasm: add support for annotation module.wasm.image/variant=compat
    2559696 wasm: add documentation
    7407be1 wasm: add support to natively build and run wasm workload and wasm containers
    6d046d6 oci-validation: checkout last working commit for runtime-tools
    eeae045 cgroup: fix race condition when enabling controllers
    fd7b3cb criu: do not override external_descriptors
    979f6f0 criu: save the new descriptors after restore

Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>