src/poky:openssh: disable ciphers not supported by OpenSSL DES
While compiling openssl with option `no-des', it caused the openssh
build failure
...
cipher.c:85:41: error: 'EVP_des_ede3_cbc' undeclared here (not in a function);
...

OpenSSL configured that way defines OPENSSL_NO_DES to disable des

(From OE-Core rev: 08a5cda85594fca8b352841a26131bfac39c8417)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>