src/poky:useradd_base: Fix sed command line for passwd-expire
A previous commit tried to add the --follow-symlinks option to
the perform_passwd_expire function in useradd_base.bbclass, however it used
a single -.

This is interpreted as --file=ollow-symlinks which results in...

sed: couldn't open file ollow-symlinks: No such file or directory

and...

ERROR: <image name>: passwd --expire operation did not succeed.

Fix by adding the missing -

(From OE-Core rev: 3c0deafcfcea3f610c7dd9a2d2884a16fbfe0497)

Signed-off-by:  Adam Johnston <adam.johnstonarm.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>