src/poky:tcl: extend to nativesdk
Fixed:
$ bitbake nativesdk-expect
ERROR: Nothing PROVIDES 'nativesdk-tcl' (but virtual:nativesdk:expect_5.45.bb DEPENDS on or otherwise requires it). Close matches:
[snip]

(From OE-Core rev: 5c950c509edcc50d39a1f426579b354d97178ff2)

(From OE-Core rev: 532d5fd5450b9ac85f81e5909b9eaa26b8493dad)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>