src/meta-openembedded:python-jinja2: Make asyncio specific to python3 module alone
asyncio is not packages seprately with python2 but only with python3

Fixes

ERROR: Nothing RPROVIDES 'python-asyncio' (but /mnt/b/yoe/sources/meta-openembedded/meta-python/recipes-devtools/python/python-jinja2_2.10.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-asyncio' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-asyncio']

Signed-off-by: Khem Raj <raj.khemgmail.com>