src/poky:bluez-hcidump: upgrade from 2.0 to 2.1
[YOCTO #1371]

Recently bluez4 was updated from 4.82 to 4.96 and bluez-hcidump can't build:
src/hcidump.c:54:24: error: redefinition of 'ntoh64'.

In 2.1 the duplicated definition of ntoh64 was removed.

(From OE-Core rev: 15a369b4e65fc8068ba7fec70ec24b7c23e7950b)

Signed-off-by: Dexuan Cui <dexuan.cuiintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>