src/meta-openembedded:glade: 3.20.0 -> 3.20.2
Since glib-2.0 updated to 2.54.2, build glade 3.20.0 failed
...
|../../glade-3.20.0/gladeui/glade-signal-model.c:68:1:
error: conflicting types for 'g_ptr_array_find'
| g_ptr_array_find (GPtrArray *array, gpointer data)
...

The following commit in the new version fixed the issue.
...
commit cb87c89745c93969c3742e7a8a11d546c00107c8
Author: Juan Pablo Ugarte <juanpablougartegmail.com>
Date:   Fri Aug 11 18:17:18 2017 -0300

    GladeSignalModel: rename g_ptr_array_find() to prt_array_find()

    GLib 2.54 introduced g_ptr_array_find() which clashes with our own
function

 gladeui/glade-signal-model.c | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
...

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>