src/meta-openembedded:python-m2crypto: Error fix for swig >= 3.0.5
After swig upgrade to 3.0.6, build the recipes which
depends on python-m2crypto will occur errors like this:
"SALT_LEN = m2.PKCS5_SALT_LEN
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'"

Reference
https://github.com/martinpaljak/M2Crypto/issues/60#issuecomment-75735489

Signed-off-by: Li Xin <lixin.fnstcn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>