src/meta-openembedded:libgtop: fix do_compile error
On some distros, such as fedora32, cross compile failed with following
error since host library is used. undefined reference to
`stat64GLIBC_2.33'

According doc of ld, set searchdir begins with "=", but not hardcoded
locations.

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>