src/poky:linux-dummy: add empty dependent packages
some kernel includes kernel-image-image and kernel-devicetree packages.
these patckages are defined in kernel.bbclass
but, when use linux-dummy, these packages are not defined.
so, define them as empty packages for avoiding compile error:

ERROR: Nothing RPROVIDES 'kernel-devicetree'

(From OE-Core rev: 8dbae2dd5ac3de629957ca699f823f5438e80163)

Signed-off-by: Li Wang <li.wangwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>