src/meta-openembedded:lvm2: restore Upstream-Status
* accidentally removed in:
  https://git.openembedded.org/meta-openembedded/diff/meta-oe/recipes-support/lvm2/files/0001-implement-libc-specific-reopen_stream.patch?id=cc4e9fbd823a9af1f6b8f622ce86d62172ee9ade

* fixes:
  ERROR: QA Issue: Missing Upstream-Status in patch
  TOPDIR/meta-oe/meta-oe/recipes-support/lvm2/files/0001-implement-libc-specific-reopen_stream.patch
  Please add according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status . [patch-status]

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>