src/meta-security:suricata: fix build error introduced by upstream commit
7a2b9acef2 cargo: pass PACKAGECONFIG_CONFARGS to cargo build

 error: unexpected argument '--with-libcap_ng-includes' found
 |
 | Usage: cargo build --verbose... --target [<TRIPLE>] --release --manifest-path <PATH> --offline

Signed-off-by: Armin Kuster <akuster808gmail.com>