src/poky:webkitgtk: Fix compile failures with clang
Backport upstream patch to address build regression with clang

Fixes
webkitgtk-2.24.3/Source/bmalloc/bmalloc/AvailableMemory.cpp:120:31: error: implicit instantiation of undefined template 'std::__1::array<char, 256>'
        std::array<char, 256> statmBuffer;
                              ^

(From OE-Core rev: 94a1c0a15e57844feddad5607fb8643f7c956953)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>