src/meta-openembedded:oscam: respect *flags set from OE
* build with -mfloat-abi=hard are failing with:
  sysroots/foo/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
  because cmake wasn't respecting *flags set from OE

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>