src/meta-virtualization:ceph: fix do_compile error: 'sys_siglist' was not declared
glibc 2.32 has deprecated sys_siglist, oe-core commit
7c19f30849e9a73a7497d8e6c4719a2e57017086, causing ceph
build to fail with error:

ceph-15.2.0/src/global/signal_handler.h:24:26: error: 'sys_siglist' was
not declared

ceph has support for using reentrant strsignal, hence use it.
See commit 82c40b67f5843162a93ebb2c1a006572d8f256a5 in upstream ceph.

Signed-off-by: Sakib Sajal <sakib.sajalwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>