src/poky:qt: fix warning -Wunused-local-typedefs introduced by gcc 4.8
in meta-oe maliit-framework failed with

| In file included from /home/andreas/tmp/oe-core-eglibc/sysroots/overo/usr/include/qt4/QtCore/QtCore:53:0,
|                  from ../utils/core-utils.cpp:18:
| /home/andreas/tmp/oe-core-eglibc/sysroots/overo/usr/include/qt4/QtCore/qtconcurrentfilter.h: In function 'QtConcurrent::ThreadEngineStarter<void> QtConcurrent::filterInternal(Sequence&, KeepFunctor, Redu
| /home/andreas/tmp/oe-core-eglibc/sysroots/overo/usr/include/qt4/QtCore/qtconcurrentfilter.h:108:47: error: typedef 'Iterator' locally defined but not used [-Werror=unused-local-typedefs]
|      typedef typename Sequence::const_iterator Iterator;
|                                                ^
| cc1plus: all warnings being treated as errors

(From OE-Core rev: 4cb93a42bae3dfa53880a9475a92cc046dde5767)

Signed-off-by: Andreas Müller <schnitzeltonygooglemail.com>
Signed-off-by: Saul Wold <sgwlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>