src/poky:avahi: add leading space to RRECOMMENDS append
* in case update-rc.d is already in RRECOMMENDS it fails with
  ERROR: Nothing RPROVIDES 'update-rc.dlibnss-mdns' (but
  meta/recipes-connectivity/avahi/avahi_0.6.31.bb
  RDEPENDS on or otherwise requires it)

(From OE-Core rev: 70dedb67c2b8b7302dc4c51e8c607e57f61f530a)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>