src/poky:mesa: fix build on Arm V5 with soft float
Since 80923e8d ("util/format: Add some NEON intrinsics-based
u_format_unpack.") upstream the build fails on Arm platforms which use
the soft-float ABI, such as qemuarmv5:

 arm_neon.h:31:2: error: #error "NEON intrinsics not available with the
 soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"

Take a patch from upstream to check the ABI being used before trying to
use NEON instructions.

(From OE-Core rev: f3d82abb781c2642a50a60033641194d1e40c212)

Signed-off-by: Ross Burton <ross.burtonarm.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>