src/poky:rpm: fix file conflicts for MIPS64 N32
The following error can occur:
  smart install libc6-2.22-r0.1lib32_mips32r2octeon3 libc6-dbg-2.22-r0.1lib32_mips32r2octeon3
error: file /sbin/ldconfig conflicts between attempted installs of libc6-2.22-r0.1.lib32_mips32r2octeon3 and libc6-2.22-r0.1.octeon3_n32
error: file /sbin/.debug/ldconfig conflicts between attempted installs of libc6-dbg-2.22-r0.1.lib32_mips32r2octeon3 and libc6-dbg-2.22-r0.1.octeon3_n32

This was because:
transactions_color = 001 (ELF32) & 010 (ELF64) & 100 (ELF32 N32 MIPS64)
FColor = Current file color (001) & transaction_color (111)
oFcolor = Previous file color (100) & transaction_color (111)

There are two places where the conflict comparisons occur.  In both places
the 'else' clause was too restrictive (opposite of the 'positive' clause).
This caused the system to only permit a binary comparison - "new preferred" or
"old preferred".  It did not permissing "neither preferred".  By removing the
else comparison the system will now perform a 'last-in-wins' resolution when
"neither is preferred".

Note, if _transaction_color is 3, MIPS64 N32 will be skipped (pretend as
installed).

(From OE-Core rev: 36c225704daa58b98a4b7f2ef315eb944d8628b5)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Mark Hatle <mark.hatlewindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>