src/meta-openembedded:open62541: fix qa error with encryption-openssl PACKAGECONFIG
In case "encryption-openssl" PACKAGECONFIG is enabled, do_package_qa fails:

ERROR: open62541-1.3.8-r0 do_package_qa: QA Issue: File /usr/lib/cmake/open62541/open62541Targets.cmake in package open62541-dev contains reference to TMPDIR [buildpaths]

Fix it by changing the value of RECIPE_SYSROOT to CMAKE_SYSROOT variable,
so the qa check passes, and other CMake projects should be still able to find the
CMake package provided by this recipe.

Signed-off-by: Gyorgy Sarvari <skandigraungmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>