src/meta-cloud-services:python-glance_git: change postgresql-setup to postgresql
Package postgresql provides postgresql-setup file
and so change postgresql-setup to postgresql to
avoid below error when run yocto compliance check
against meta-openstack layer.
ERROR: Nothing RPROVIDES 'postgresql-setup' (but /mybuild/layers/meta-cloud-services/meta-openstack/recipes-extended/packagegroups/packagegroup-cloud-compute.bb, /mybuild/layers/meta-cloud-services/meta-openstack/recipes-devtools/python/python-glance_git.bb, /mybuild/layers/meta-cloud-services/meta-openstack/recipes-extended/packagegroups/packagegroup-cloud-controller.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'postgresql-setup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['postgresql-setup']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-cloud-compute', 'postgresql-setup']

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>