src/poky:libxml2-ptest: set LC_ALL=en_US.UTF-8
We need to specify UTF-8 in the environment to avoid an error
such as:

UnicodeEncodeError: 'ascii' codec can't encode character '\xe4'

(From OE-Core rev: d7f1fe6c8419b8c59e601c56245373d094cae298)

Signed-off-by: Juro Bystricky <juro.bystrickyintel.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>