src/poky:tune/armv7: Delete
armv7 is least common denominator of armv7-a
armv7-m and armv7-r and armv7-m does not support
ARM instructions but only thumb2 instruction set
which means armv7 when chosen will complain if
code is compiled in arm mode which is default
in OE if not specified other wise

if we chose this tuning errors like below pop up

error: target CPU does not support ARM mode

This tuning seems theoretical and base tune
for armv7 would be one of armv7-a,  armv7-m or
armv7-r

(From OE-Core rev: 75b8adbc042e0f65fb1286bc550d02becd3b6aea)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>