src/meta-openembedded:igmpproxy: remove 0001-src-igmpproxy.h-Include-sys-types.h-for-u_short-u_in.patch and _GNU_SOURCE
* it was upgraded to 0.2.1 in:
  commit 50979151e69e5707580b2f3d263a9b36b6a190d5
  Author: Oleksandr Kravchuk <open.sourceoleksandr-kravchuk.com>
  Date:   Sat Mar 16 18:22:59 2019 +0100

    igmpproxy: update to 0.2.1

* which includes _GNU_SOURCE:
  https://github.com/pali/igmpproxy/commit/7d790aa2f16afad63418e573db13ea39d76ed141
* and includes sys/types.h in os-linux.h:
  https://github.com/pali/igmpproxy/commit/6f92242b23178e979f4a806abe4ac9652b51c593
* and the patch doesn't apply cleanly:
  ERROR: Fuzz detected:

  checking file src/igmpproxy.h
  Hunk #1 succeeded at 51 with fuzz 2 (offset 5 lines).

  patching file src/igmpproxy.h
  Hunk #1 succeeded at 51 with fuzz 2 (offset 5 lines).

  The context lines in the patches can be updated with devtool:

      devtool modify lib32-igmpproxy
      devtool finish --force-patch-refresh lib32-igmpproxy <layer_path>

  Don't forget to review changes done by devtool!

  ERROR: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>