src/poky:webkitgtk/epiphany: add opengl to REQUIRED_DISTRO_FEATURES
They can't be built without opengl in DISTRO_FEATURES.
[snip]
|webkitgtk-2.20.3/Source/WebCore/platform/graphics/OpenGLShims.h:23:10:
fatal error: GL/gl.h: No such file or directory
[snip]

Some sort of GL is needed yes. We indicate that with opengl loosely in OE

The epiphany depends on webkitgtk, add opengl to REQUIRED_DISTRO_FEATURES also.

(From OE-Core rev: 059af47ecd75d6b733ba893e000749bf3d89d413)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>