src/poky:mesa: Fix header search paths
mesa build currently emits CLANG_RESOURCE_DIR into compiled objects and
meson calculates it from llvm cmake files from sysroot and it points to
absolute paths in target sysroot. To fix this backport a patch that does
not rely on CLANG_RESOURCE_DIR, however, this patch still leaves it in
code as fallback via FALLBACK_CLANG_RESOURCE_DIR, we are on LLVM 20.x
which will not use this variable, lets just remove detection so it does
not encode hardcoded paths.

Fixes

ERROR: mesa-2_25.0.2-r0 do_package_qa: QA Issue: File /usr/lib/libMesaOpenCL.so.1.0.0 in package libopencl-mesa contains reference to TMPDIR [buildpaths]
ERROR: mesa-2_25.0.2-r0 do_package_qa: Fatal QA errors were found, failing task.

(From OE-Core rev: afcde8eb575684fb514e1012b31bc0da04f4cb28)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Dmitry Baryshkov <dmitry.baryshkovoss.qualcomm.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>