src/meta-openembedded:kernel-selftest: Needs error.h which is missing in musl
prog_tests/flow_dissector.c:3:10: fatal error: error.h: No such file or directory
| #include <error.h>
|          ^~~~~~~~~

Signed-off-by: Khem Raj <raj.khemgmail.com>