src/poky:linux-libc-headers: fix in/if.h includes
The following kernel commits broke the compilation of ppp, due to redefined
structures.

Nothing else breaks in userspace with or without these uapi changes, so we
revert them to keep everything building.

   commit 05ee5de7451796cf9a8aeb2f05a57790d4fd2336
   Author: Mikko Rapeli <mikko.rapeliiki.fi>
   Date:   Mon Aug 22 20:32:42 2016 +0200

       include/uapi/linux/if_pppol2tp.h: include linux/in.h and linux/in6.h

       Fixes userspace compilation errors like:

       error: field <E2><80><98>addr<E2><80><99> has incomplete type
        struct sockaddr_in addr; /* IP address and port to send to */
                           ^
       error: field <E2><80><98>addr<E2><80><99> has incomplete type
        struct sockaddr_in6 addr; /* IP address and port to send to */

       Signed-off-by: Mikko Rapeli <mikko.rapeliiki.fi>
       Signed-off-by: David S. Miller <davemdavemloft.net>

   commit eafe92114308acf14e45c6c3d154a5dad5523d1a
   Author: Mikko Rapeli <mikko.rapeliiki.fi>
   Date:   Mon Aug 22 20:32:43 2016 +0200

       include/uapi/linux/if_pppox.h: include linux/in.h and linux/in6.h

       Fixes userspace compilation errors:

       error: field <E2><80><98>addr<E2><80><99> has incomplete type
        struct sockaddr_in addr; /* IP address and port to send to */

       error: field <E2><80><98>addr<E2><80><99> has incomplete type
        struct sockaddr_in6 addr; /* IP address and port to send to */

       Signed-off-by: Mikko Rapeli <mikko.rapeliiki.fi>
       Signed-off-by: David S. Miller <davemdavemloft.net>

(From OE-Core rev: 12451a412fb7b5706c1553618ee7b704234876cc)

Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>