src/meta-openembedded:frame: add opengl to REQUIRED_DISTRO_FEATURES
Fixes:
  ERROR: Nothing PROVIDES 'virtual/xserver' (but /build/layers/meta-openembedded/meta-oe/recipes-support/canonical-multitouch/frame_2.5.0.bb DEPENDS on or otherwise requires it)
xserver-xorg PROVIDES virtual/xserver but was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'geis', 'frame', 'virtual/xserver']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>