src/meta-openembedded:python3-websockets: upgrade to 8.0.2
The present version was not compatible with python 3.7 because async is
now the proper keyword. The reported werror was:

    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax

Issues like this one: https://github.com/psf/requests-html/issues/65
explains the reason of that.

Signed-off-by: Maciej Pijanowski <maciej.pijanowski3mdeb.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>