src/poky:bitbake: bitbake: providers: fix incorrect return type bug
If no eligible providers are found then an integer zero is returned.
This causes the following error, in two possible places in taskdata.py,
when the return value is used in a list comprehension:

[snip]
    eligible = [p for p in eligible if not p in self.failed_fns]
TypeError: 'int' object is not iterable
[\snip]

Fix by returning the variable eligible itself, of type list.

(Bitbake rev: 217c4b436b588a6a47aeaddf61531711ad3fca67)

Signed-off-by: Charlie Davies <charles.davieswhitetree.xyz>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>