src/meta-openembedded:openvpn: not use the hardcoded libdir
it will lead to QA failure, since .debug dir can not be installed into dbg package

    ERROR: QA Issue: non debug package contains .debug directory: openvpn path
    /work/core2-64-wrs-linux/openvpn/2.3.4-r0/packages-split/openvpn/usr/lib64i
    /openvpn/plugins/.debug/openvpn-plugin-down-root.so [debug-files]

Signed-off-by: Roy Li <rongqing.liwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>