src/poky:rootfs.py: strip kernel-abiversion useless readline
It failed to read Kernel version from kernel-abiversion
file, the reason was it didn't strip the readline.
...
 Error: Kernel version 3.10.25-yocto-standard
  does not match kernel-abiversion (3.10.25-yocto-standard)
...

(From OE-Core rev: 17a0a8f44fe344ab1ae49730d9f17705b43987e5)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Laurentiu Palcu <laurentiu.palcuintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>