src/meta-openembedded:rocksdb: fix build error for DEBUG_BUILD
It fails to build rocksdb when '-Og' is set in CXXFLAGS (e.g.
DEBUG_BUILD = '1' in local.conf):

rocksdb/9.0.0/git/util/xxhash.h:4491:1: error: inlining failed in call
to 'always_inline' 'void XXH3_scrambleAcc_sse2(void*, const void*)':
function not considered for inlining
 4491 | XXH3_scrambleAcc_sse2(void* XXH_RESTRICT acc, const void* XXH_RESTRICT secret)
      | ^~~~~~~~~~~~~~~~~~~~~
rocksdb/9.0.0/git/util/xxhash.h:5139:19: note: called from here
 5139 |         f_scramble(acc, secret + secretSize - XXH_STRIPE_LEN);
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rocksdb/9.0.0/git/util/xxhash.h:4177:1: error: inlining failed in call
to 'always_inline' 'void XXH3_accumulate_sse2(xxh_u64*, const xxh_u8*, const xxh_u8*, size_t)':
function not considered for inlining
 4177 | XXH3_accumulate_##name(xxh_u64* XXH_RESTRICT acc,           \
      | ^~~~~~~~~~~~~~~~

Check and disable inlining when "-Og" is present.

Signed-off-by: Yi Zhao <yi.zhaowindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>