src/poky:rust: Update "do_update_snapshot" task for rust-snapshot.inc
The 'do_update_snapshot' task is failed with below error:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '.../rustc-1.83.0-src/src/stage0.json'

There are changes in use of key-value format in stage0 file in
rust sources and the rust recipe should be apdated for that.

Changes in rust:
https://github.com/rust-lang/rust/commit/1adfffd07f8704ca722f3897719ace079944b0c5

(From OE-Core rev: d64456f6ea58d683993b0bc7294baa889bafdf7b)

Signed-off-by: Yash Shinde <Yash.Shindewindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>