src/meta-openembedded:gjs: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/libexec/installed-tests/gjs/GIMarshallingTests-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 and gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/Regress-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 and gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/Utility-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 and gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/WarnLib-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 and gjs-1.82.1-r0.core2_64

The .typelib file is a binary file that contains runtime information for the GObject type system.
These information include function signature, type size, alignment, etc., which may vary depending on the architecture (32-bit vs 64 bit).

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>