src/poky:git: fix installed-vs-shipped QA Issue
Since commit set default libexecdir to $prefix/libexec
...
commit f35b2e29d9bfa817e64b83df11ebbbfe0f4e8e5c
Author: Ross Burton <ross.burtonintel.com>
Date:   Tue Apr 30 20:35:54 2013 +0100

    bitbake: set default libexecdir to $prefix/libexec
...

It casued '${D}${libdir}' does not exist, and the following
move operation incorrect which triggered QA Issue:
...
ERROR: git-2.7.0-r0 do_package: QA Issue: git: Files/directories were installed but not shipped in any package:
  /usr/lib64
  /usr/lib64/site_perl
  /usr/lib64/site_perl/5.22.1
...

(From OE-Core rev: 2b82a475a7c8310f432b872e9d1e5eca262a03ee)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>