src/meta-openembedded:libchamplain: Require opengl distro feature
It has hard dependency on clutter-gtk-1.0 which needs opengl

Fixes

clutter-gtk-1.0 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libchamplain', 'clutter-gtk-1.0']

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Andreas Müller <schnitzeltonygmail.com>