src/poky:glibc: fix multilib headers conflict for arm
Fixes:
Error: Transaction test error:
  file /usr/include/bits/dl_find_object.h conflicts between attempted installs of lib32-libc6-dev-2.35-r0.armv7vet2hf_vfp and libc6-dev-2.35-r0.cortexa57
  file /usr/include/bits/rseq.h conflicts between attempted installs of lib32-libc6-dev-2.35-r0.armv7vet2hf_vfp and libc6-dev-2.35-r0.cortexa57
  file /usr/include/bits/timesize.h conflicts between attempted installs of lib32-libc6-dev-2.35-r0.armv7vet2hf_vfp and libc6-dev-2.35-r0.cortexa57

(From OE-Core rev: 0982c2bc19f4cacd72fd43f93c6a0a4d45a75c6a)

Signed-off-by: Yi Zhao <yi.zhaowindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>