src/meta-intel:ispc: fix recipe
There are few problems in current recipe:

(1)
ispc needs to invoke native llvm-config from target sysroot to list LLVM
lib libraries. clang already provides crossscripts/llvm-config, which does
the job.

However, using LLVM_TOOLS_BINARY_DIR leads to wrong llvm-config being
used. So remove it from search path for llvm-config.

(2)
Error:
ispc/1.19.0-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/x86_64-poky-linux-ld:
ispc/1.19.0-r0/recipe-sysroot-native/usr/lib/libclang-cpp.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)GLIBCXX_3.4.30'
error: linker command failed with exit code 1 (use -v to see invocation)

Native libraries were being linked to target libraries leading to this
failure. Fix and cleanup DEPENDS/RDEPENDS.

Signed-off-by: Naveen Saini <naveen.kumar.sainiintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>