src/meta-openembedded:uutils-coreutils: remove LIBCLANG_PATH, SELINUX_LIB_DIR, SELINUX_INCLUDE_DIR variables
* don't seem to be needed, I don't see any failures or changes after removing them

* they were needed before in older version as explained by Etienne in:
  https://lists.openembedded.org/g/openembedded-devel/message/115756

regarding SELINUX_INCLUDE_DIR, it was definitely needed as I implemented the recipe. During implementation I submitted this patch to selinux-sys ( https://github.com/koutheir/selinux-sys/commit/a6667c404ecc33266f66e9516bb8e30150c41ec2 ) to correctly use this variable, and was getting a build error without this fix because the rust crate selinux-sys was not finding the selinux header-file (specifically, the bindgen tool).

However, this was in 2022, and since then there has been this patch in selinux-sys: https://github.com/koutheir/selinux-sys/commit/d3ea4674e18c5240918348bea4ec6248e50516e5 , and it seems that the variable is not needed any more.
At least I'm not able to reproduce the build error which I was getting, even with commenting out SELINUX_LIB_DIR and SELINUX_INCLUDE_DIR.

The header-file is used for generating rust code from the C header-file using bindgen, so I don't think it makes a difference whether the native version or the target version is used.

This is the old build error I was getting:
  process didn't exit successfully: `/workdir/build/tmp-glibc/work/armv8a-linux/uutils-coreutils/0.0.14.AUTOINC+43a5b8c7d7-r0/build/target/release/build/selinux-sys-0849198bc1fef4a4/build-script-build` (exit status: 101)
  --- stdout
  cargo:root=/workdir/build/tmp-glibc/work/armv8a-linux/uutils-coreutils/0.0.14.AUTOINC+43a5b8c7d7-r0/build/target/aarch64-snap-linux/release/build/selinux-sys-d96748d49908959f/out
  cargo:rerun-if-env-changed=SELINUX_STATIC_aarch64-snap-linux
  cargo:rerun-if-env-changed=SELINUX_STATIC_aarch64_snap_linux
  cargo:rerun-if-env-changed=TARGET_SELINUX_STATIC

|   --- stderr
|   src/selinux-sys.h:1:10: fatal error: 'selinux/selinux.h' file not found
|   src/selinux-sys.h:1:10: fatal error: 'selinux/selinux.h' file not found, err: true

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>