src/poky:kernel: remove explicit bash call in do_menuconfig
Fixes [BUGID #598]

The explicit addition of "bash" before "make menuconfig"
is clearing variables that are required for pseudo. The
end result is that menuconfig often fails silently with:

ERROR: ld.so: object 'libpseudo.so' from LD_PRELOAD cannot be preloaded: ignored.

Removing bash from the menuconfig SHELLCMDS variable fixes
the psudo problem.

(From OE-Core rev: b909f12a92c86fd2fe9348eeec455e2c9ef71f1a)

Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>