src/meta-openembedded:networkmanager: fix Files/directories were installed but not shipped
Since networkmanager: upgrade 1.22.10 -> 1.22.14, it added a new
build option 'firewalld-zone', while enabling multilib, there is
a QA issue
...
ERROR: QA Issue: networkmanager: Files/directories were installed but not shipped in any package:
  /usr/lib/firewalld
  /usr/lib/firewalld/zones
  /usr/lib/firewalld/zones/nm-shared.xml
...

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>