src/meta-openembedded:meta-xfce: xfconf: fixup installed-vs-shipped QA issue
Since the xfconf uprev, commit 4222cac97678 [xfconf: 4.13.5 ->
4.13.6], we are getting a QA issue:

  ERROR: xfconf-4.13.6-r0 do_package: QA Issue: xfconf: Files/directories were installed but not shipped in any package:
  /usr/lib64/gio/modules/libxfconfgsettingsbackend.la
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  xfconf: 1 installed and not shipped files. [installed-vs-shipped]
  ERROR: xfconf-4.13.6-r0 do_package: Fatal QA errors found, failing task.
  ERROR: xfconf-4.13.6-r0 do_package: Function failed: do_package

We need to include the .la file in the -dev package to avoid this.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>