src/poky:gdb: Alias rpl_stat to stat() on musl
Use CPPFLAGS instead of CFLAGS since there is C++ compiler being used for somefiles

Fixes
gdb/gdbserver/../../../gdb-8.1.1/gdb/gdbserver/../common/common-utils.c:419: undefined reference to `rpl_stat'
| collect2: error: ld returned 1 exit status
| make[4]: *** [Makefile:414: libinproctrace.so] Error 1

(From OE-Core rev: d6806b449ba8b44fd74dfb05c65b9233b6f3ace5)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>