src/poky:scripts/yocto_testresults_query.py: set proper branches when using resulttool
The script currently only works if base and target can be found on default
branches. It breaks if we try to generate a regression report between revisions
that live on different branches (as needed on integration and testing branches).
For example, the following command:

./scripts/yocto_testresults_query.py regression-report yocto-4.0.6 yocto-4.0.7

ends with the follwing error:

[...]
ERROR: Only 1 tester revisions found, unable to generate report
[...]

Read branches from tags names in test results repository, and pass those
branches to resulttool when generating the report

(From OE-Core rev: 6c472b326bcc718459483cc29b310b884742df86)

Signed-off-by: Alexis Lothoré <alexis.lothorebootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>