src/poky:busybox.inc: handle empty DEBUG_PREFIX_MAP
DEBUG_PREFIX_MAP can be empty if e.g. old clang
toolchain doesn't support the default poky values for gcc.

Fixes build failure:

ERROR: Logfile of failure stored in: /home/builder/src/base/build/tmp/work/aarch64-poky-linux/busybox/1.31.0-r
0/temp/log.do_configure.14451
Log data follows:
| DEBUG: Executing shell function do_configure
| sed: -e expression #1, char 0: no previous regular expression
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/builder/src/base/build/tmp/work/aarch64-poky-linux/busybox/1.31.0-r0/temp/run.do_configure.14451' failed with exit code 1:
| sed: -e expression #1, char 0: no previous regular expression
| WARNING: exit code 1 from a shell command.
|

This log entry is really useless for debugging problems so
add "set -x" to the configure script so that details can be seen
if something isn't working.

(From OE-Core rev: 20f1a454317ddff8a2e321c1fe55d086ff6fa286)

Signed-off-by: Mikko Rapeli <mikko.rapelibmw.de>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>