src/meta-openembedded:python3-matplotlib: bump to 3.5.2
There's a bug in 3.5.1 that makes importing matplotlib impossible in
some environments:

>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 895, in <module>
    defaultParams = rcsetup.defaultParams = {
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 898, in <dictcomp>
    rcParamsDefault[key]),
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'webagg.port'

This is fixed in 3.5.2.

Signed-off-by: Bartosz Golaszewski <brglbgdev.pl>
Signed-off-by: Khem Raj <raj.khemgmail.com>