src/meta-openembedded:bdwgc: upgrade 8.0.4 -> 8.0.6
Highlights of this upgrade:
* Fix 'undefined reference to __data_start' linker error on risc-v
* Fix data race in generic_malloc_many
* Fix handling of areas smaller than page size in GC_scratch_recycle
* Fix misaligned tlfs passed to AO_load on m68k
* Fix overflow of scratch_free_ptr value
* Limit number of unmapped regions (to avoid exceeding of vm.max_map_count)

See the following for detailed changes:
* https://github.com/ivmai/bdwgc/releases/tag/v8.0.6

The LIC_FILES_CHKSUM has changed because of update of copyright
year (in README.QUICK).

Signed-off-by: Ivan Maidanski <ivmaimail.ru>
Signed-off-by: Khem Raj <raj.khemgmail.com>