src/poky:python3-setuptools: add missing rdepends for python3-pkg-resources
Add missing rdepends for python3-pkg-resources to fix below error:
 # python3
 [snip]
 import pkg_resources
 [snip]
 ModuleNotFoundError: No module named 'plistlib'
 ModuleNotFoundError: No module named 'email'

(From OE-Core rev: 932b282a51f65c99847651ea1399c38b538bf432)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>