src/meta-openembedded:krb5: Fix install conflict when enable multilib.
Error: Transaction test error:
file /usr/bin/krb5-config conflicts between attempted installs of lib32-krb5-user-1.17.2-r0.armv7ahf_neon and krb5-user-1.17.2-r0.aarch64

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>