src/meta-openembedded:libmicrohttpd: Update to 0.9.34
This update fixes the following build error:

,----[ Build error ]
| ...
| .../libmicrospdy.so: undefined reference to `SSL_get_error'
| .../libmicrospdy.so: undefined reference to `SSL_write'
| .../libmicrospdy.so: undefined reference to `SSL_free'
| ...
`----

Reported-by: Prabhu Sundararaj <prabhu.sundararajfreescale.com>
Signed-off-by: Otavio Salvador <otavioossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>