src/meta-openembedded:curlpp: fix do_compile failed since gcc upgrade to 4.9
The deprecated test code was no longer used, so remove it
to avoid compiling failure with -Werror=unused-function
...
| example21.cpp:51:8: error: 'size_t {anonymous}::readData(char*,
size_t, size_t)' defined but not used [-Werror=unused-function]
|  size_t readData(char *buffer, size_t size, size_t nitems)
...

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>