src/meta-virtualization:xen: patch to fix ARM libxc missing variable init
Fix Xen 4.9.0 build error on ARM architecture with gcc 7:
Import upstream Xen patch 88bfbf90e35f1213f9967a97dee0b2039f9998a4

Error was:
xc_dom_arm.c:229:31: error: 'domctl.u.address_size.size' may be used
uninitialized in this function [-Werror=maybe-uninitialized]

Signed-off-by: Christopher Clark <christopher.clark6baesystems.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>