src/meta-openembedded:ntp: Add missing 'ntp' static group id
This fixes build in reproducible test environment [0]:
ERROR: ntp-4.2.8p17-r0 do_install: ExecutionError[...]
| chown: invalid group: ‘ntp:ntp’

Also add a missing newline at end-of-file.

[0]: https://autobuilder.yoctoproject.org/typhoon/#/builders/155/builds/12/steps/28/logs/stdio line 12221

Signed-off-by: Yoann Congal <yoann.congalsmile.fr>
Signed-off-by: Khem Raj <raj.khemgmail.com>