src/poky:font-util: The recipe produces binaries so don't mark as 'all' architecture
Since font-util produces binaries it shouldn't be marked as "all"
package architecture. To achieve this we need to move the settings
out the common include file.

This fixes errors like:

ERROR: runstrip: ''mips-poky-linux-strip' --remove-section=.comment --remove-section=.note '/srv/home/pokybuild/poky-slave/nightly-external/build/build/tmp/work/all-poky-linux/font-util-1.2.0-r2.1/package/usr/bin/bdftruncate'' strip command failed
ERROR: runstrip: ''mips-poky-linux-strip' --remove-section=.comment --remove-section=.note '/srv/home/pokybuild/poky-slave/nightly-external/build/build/tmp/work/all-poky-linux/font-util-1.2.0-r2.1/package/usr/bin/ucs2any'' strip command failed

(From OE-Core rev: 7aefddc57e9da02298af1aa98abedbe99435e15a)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>