src/meta-openembedded:python3-portalocker: enable ptest
* test_combined.py deleted because it is not a functional test. It checks if the 'combine' function work correctly which is parse README.rst and LICENSE.

* Ptest and library example tested on qemux86-64 and qemuarm64

* Add ptest into PTESTS_FAST_META_PYTHON

qemux86-64:

Testsuite summary
TOTAL: 21
PASS: 21
SKIP: 0
XFAIL: 0
FAIL: 0
XPASS: 0
ERROR: 0
DURATION: 11
END: /usr/lib/python3-portalocker/ptest
2024-03-26T18:47
STOP: ptest-runner
TOTAL: 1 FAIL: 0

qemuarm64:

Testsuite summary
TOTAL: 21
PASS: 21
SKIP: 0
XFAIL: 0
FAIL: 0
XPASS: 0
ERROR: 0
DURATION: 11
END: /usr/lib/python3-portalocker/ptest
2024-03-26T18:52
STOP: ptest-runner
TOTAL: 1 FAIL: 0

Signed-off-by: alperak <alperyasinak1gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>