src/meta-openembedded:python3-pathlib2: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pathlib2
 [snip]
 ModuleNotFoundError: No module named 'ctypes'

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>