src/meta-openembedded:python3-stopit: add missing run-time dependencies
The stopit package needs setuptools python module so add it to RDEPENDS.

This fixes:
    File "/usr/lib64/python3.9/site-packages/stopit/__init__.py", line 10, in <module>
	import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

Signed-off-by: Adrian Zaharia <Adrian.Zahariawindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>