src/meta-openembedded:packagegroup-meta-multimedia: include x265 only with commercial in LICENSE_FLAGS_WHITELIST
* fixes:
  ERROR: Nothing RPROVIDES 'x265' (but meta-openembedded/meta-multimedia/recipes-multimedia/packagegroups/packagegroup-meta-multimedia.bb RDEPENDS on or otherwise requires it)
  x265 was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST

* also include i686 so that it's included e.g. with default DEFAULTTUNE of qemux86 as recipe allows that with:
  COMPATIBLE_HOST = '(x86_64|i.86).*-linux'
  i586 isn't used by qemux86 since:

  commit f3b1e577ec94c849d0354f5679257f02ef4e4fe9
  Author: Alexander Kanavin <alex.kanavingmail.com>
  Date:   Thu May 16 17:04:04 2019 +0200

    qemux86: use a Core 2 Duo CPU instead of the original circa-1993 Pentium

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>