src/meta-intel:libyami: fix build error with gcc9
GCC9 causing multiple build failures:

| ../../git/codecparsers/h264Parser.cpp: In constructor 'YamiParser::H264::PPS::PPS()':
| ../../git/codecparsers/h264Parser.cpp:140:41: error: 'void* memset(void*, int, size_t)' clearing an object of type 'struct YamiParser::H264::PPS' with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
|   140 |     memset(this, 0, offsetof(PPS, m_sps));
...

Signed-off-by: Naveen Saini <naveen.kumar.sainiintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>