src/poky:get_module_deps3.py: Check attribute '__file__'
Check if the module object has attribute '__file__' to fix and
avoid errors like:

AttributeError: module '_abc' has no attribute '__file__'. Did you mean: '__name__'?

(From OE-Core rev: ede7452e6dcb202952b85b76eecbd2e1760b11e9)

Signed-off-by: Leon Anavi <leon.anavikonsulko.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
(cherry picked from commit 8acce12c1a4cf37ac312c92d62a6ae93a349dddf)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>