src/poky:bitbake.conf: Add SRCPV to BB_HASH_CODEPARSER_VALS
Also add SRCPV to the list of BB_HASH_CODEPARSER_VALS for code parser
cache handling. Otherwise an empty SRC_URI in the list triggers this
exception:

bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${bb.fetch2.get_srcrev(d)} which triggered exception
 FetchError: Fetcher failure: SRCREV was used yet no valid SCM was found in SRC_URI
The variable dependency chain for the failure is: SRCPV -> UBOOT_LOCALVERSION -> do_compile

(From OE-Core rev: d17f9da69f430337ee1ef9c09b731c27393eba83)

Signed-off-by: Denys Dmytriyenko <denisdenix.org>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>