src/poky:systemtap: disable libvirt
libvirt is automatically linked to if present, this undetermined
dependency may cause build errors like:

  ../lib/libvirt.so: undefined reference to `libssh2_channel_open_ex'
  ../lib/libvirt.so: undefined reference to `libssh2_session_hostkey'
  ...

Both libvirt and libssh2 are not oe-core recipes for now, just disable
libvirt to fix this issue.

(From OE-Core rev: 815b44914eb30b86dfce0e81ffda7884e0efcc34)

Signed-off-by: Wenzong Fan <wenzong.fanwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>