src/meta-openembedded:freediameter: add dependency on virtual/kernel and use MACHINE_ARCH
* TUNE_PKGARCH cannot RRECOMMEND MACHINE specific kernel-modules
* without virtual/kernel dependency (which isn't really build time
  dependency) the QA check won't traverse the dependencies correctly
  and shows following errors:
  ERROR: QA Issue: freediameter rdepends on kernel-module-ipip, but it isn't a build dependency? [build-deps]
  ERROR: QA Issue: freediameter rdepends on kernel-module-sctp, but it isn't a build dependency? [build-deps]
  ERROR: QA Issue: freediameter rdepends on kernel-module-tipc, but it isn't a build dependency? [build-deps]
  ERROR: QA Issue: freediameter rdepends on kernel-module-udp-tunnel, but it isn't a build dependency? [build-deps]
* also change kernel-module dependencies from RDEPENDS to RRECOMMENDS
  because the kernel config might include these directly and then
  freediameter shouldn't fail to install

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>