src/poky:kernel.bbclass: Make task clean depend on cleaning of make-mod-scripts
The package 'make-mod-scripts' creates files in 'kernel-build-artifacts/include/config'
which are removed by 'cleanall/cleansstate' of 'virtual/kernel'. And this causes the
below error while building out of tree kernel module:
ERROR: Kernel configuration is invalid.
      include/generated/autoconf.h or include/config/auto.conf are missing.
      Run 'make oldconfig && make prepare' on kernel src to fix it.

Suggested-by: Jun Nie <jun.nielinaro.org>

(From OE-Core rev: f79c95f6a883e999e0c2ecfd60b6b696b7595497)

Signed-off-by: Haiqing Bai <Haiqing.Baiwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>