src/meta-virtualization:docker-distribution: fix build error on new hosts
Fix settings for GOROOT, CGO_CFLAGS and CGO_LDFLAGS.

The previous setting for GOROOT is no longer valid as the directory
does not exist for now. So adjust the GOROOT setting.

Currently CGO_CFLAGS is set to use BUILDSDK_CFLAGS, and this is
incorrect. We need target flags instead of SDK related flags. Such
setting happens to work for some hosts. However, when building on
newer hosts, we get QA error like below:

  ERROR: docker-distribution-v2.7.1-r0 do_package_qa:
  QA Issue: /usr/sbin/registry contained in package docker-registry requires
  libc.so.6(GLIBC_2.34)(64bit), but no providers found in RDEPENDS_docker-registry? [file-rdeps]

The above error was found on hardknott on host Fedora 35.
Tracking down the error and I found it's using host stuff which is likely
to be caused by using incorrect CGO_CFLAGS. As the master branch is
using the same settings, it has the same issue.

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>