src/poky:populate_sdk_ext: write_local_conf add shutil import
Add shutil import to resolve error:

Exception: NameError: name 'shutil' is not defined, Did you forget to import 'shutil'

(From OE-Core rev: 6f0d75ed7bbae03301bd41db1076ce926c5e742c)

Signed-off-by: Mark Hatle <mark.hatlekernel.crashing.org>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit b64263a43b4d82f1ebba13815bccb8a8cd3127f9)
Signed-off-by: Mark Hatle <mark.hatlekernel.crashing.org>
Signed-off-by: Steve Sakoman <stevesakoman.com>