src/meta-openembedded:libkcapi: Fix missing bash (for apps) and unneeded checksums (for testapp) when building
Fix build failures:
1. with "apps" PACKAGECONFIG:

    ERROR: libkcapi-1.1.3+gitAUTOINC+1c736c43eb-r0 do_package:
    QA Issue: libkcapi: Files/directories were installed but not shipped in any package:
      /usr/bin/.sha1hmac.hmac
      /usr/lib/.libkcapi.so.1.1.3.hmac

2. with "testapp" PACKAGECONFIG:

    ERROR: libkcapi-1.1.3+gitAUTOINC+1c736c43eb-r0 do_package_qa:
    QA Issue: /usr/libexec/libkcapi/test.sh contained in package libkcapi requires /bin/bash,
    but no providers found in RDEPENDS_libkcapi? [file-rdeps]

Signed-off-by: Krzysztof Kozlowski <krzkkernel.org>
Signed-off-by: Khem Raj <raj.khemgmail.com>