src/poky:packagegroup-core-base-utils: Make it machine specific
Recipe makes use of the variable MACHINE_FEATURES, which is machine
specific:

  ${bb.utils.contains("MACHINE_FEATURES", "keyboard", "kbd", "", d)}

This patch avoids multiconfig errors such as:

ERROR: mc:qt5222:packagegroup-core-base-utils-1.0-r0 do_package_qa_setscene: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_package_qa_setscene(d)
     0003:
File: '/workdir/repo/poky/meta/classes/insane.bbclass', lineno: 1026, function: do_package_qa_setscene
     1022:SSTATETASKS += "do_package_qa"
     1023:do_package_qa[sstate-inputdirs] = ""
     1024:do_package_qa[sstate-outputdirs] = ""
     1025:python do_package_qa_setscene () {
 *** 1026:    sstate_setscene(d)
     1027:}
     1028:addtask do_package_qa_setscene
     1029:
     1030:python do_qa_staging() {

(From OE-Core rev: 70234797b973046a6198bea684bdb757def2dce1)

(From OE-Core rev: 5e9185d34b3a45aadec96273a0570ec5f05f6aec)

Signed-off-by: Ricardo Ribalda Delgado <ricardoribalda.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>