src/meta-openembedded:layer.conf: Add ttf-roboto->fontconfig to SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
it depends on fontcache which pulls in fontconfig into rdeps and results in errors
e.g.

ERROR: ttf-roboto different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
Hash for dependent task fontconfig/fontconfig_2.13.1.bb:do_packagedata changed

Signed-off-by: Khem Raj <raj.khemgmail.com>