src/meta-cgl:ocfs2-tools: fix compile error with glibc 2.26
When glibc upgrade to glibc-2.26.90-14, there was a compile error in fsck.ocfs2,
the compile error messages like,

In file included from /usr/include/string.h:431:0,
                 from ../include/ocfs2/ocfs2.h:41,
                 from pass4.c:32:
include/strings.h:37:1: error: unknown type name 'errcode_t'; did you mean 'mode_t'?
 errcode_t o2fsck_strings_insert(o2fsck_strings *strings, char *string,
 ^~~~~~~~~
 mode_t

Backport a patch to rename strings.h => o2fsck_strings.h

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Adrian Dudau <adrian.dudauenea.com>