src/poky:libuser: enable documentation
Added popt to DEPENDS. This fixes the following build error:

apps/luserdel.c:25:18: fatal error: popt.h: No such file or directory

Remove patch and configure flag which had disabled doc generation

Add docbook-utils-native and linuxdoc-tools-native to DEPENDS

This fixes [BUGID #213]

Signed-off-by: Scott Garman <scott.a.garmanintel.com>