src/meta-openembedded:python3-flask-versioned: Fix PYPA_WHEEL name
Add function to generate expected PYPA_WHEEL name.

Generated name:
/yp/builds/meta-qtec-distro/tmp/work/dbfp4-poky-linux/python3-flask-versioned/0.9.4-20101221-r0/Flask-Versioned-0.9.4-20101221/dist/
Flask_Versioned-0.9.4.post20101221-py3-none-any.whl

Default (wrong) name:
Flask_Versioned-0.9.4-20101221-*.whl

Error:
WARNING: Requirement '/yp/builds/meta-qtec-distro/tmp/work/dbfp4-poky-linux/python3-flask-versioned/0.9.4-20101221-r0/Flask-Versioned-0.9.4-20101221/dist/Flask_Versioned-0.9.4-20101221-*.whl'
looks like a filename, but the file does not exist
ERROR: Flask_Versioned-0.9.4-20101221-*.whl is not a valid wheel filename.

Signed-off-by: Daniel Gomez <danielqtec.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Trevor Gamblin <trevor.gamblinwindriver.com>