src/poky:devtool-source.bbclass: Only create each patch branch once
For conditonally applied patches based on SRC_URI overrides, the
devtool-source class would try to create a new branch for each override
assignment as a postfunc to do_patch, but if the same override was used
multiple times, it would try to create the same branch multiple times,
causing errors like

> Exception: bb.process.ExecutionError: Execution of
\   'git checkout f0f0f0f0f0ff0f0f0f0f0f0f0f0f0f0f0ff0f0f0 -b devtool-override-foo'
\   failed with exit code 128:
> fatal: A branch named 'devtool-override-foo' already exists.

This change makes sure that the devtool-source bbclass will only create
one branch per override.

(From OE-Core rev: 95a921959d340f74b5604df57737c1eeaad0023e)

Signed-off-by: Olof Johansson <olofjnaxis.com>
Reviewed-by: Peter Kjellerstedt <pkjaxis.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>