src/poky:python3-setuptools: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import setuptools
 [snip]
 ModuleNotFoundError: No module named 'json'

(From OE-Core rev: f1dce04d2643352cd7a2c5a91eefc01d52926ecd)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>