src/meta-intel:gmmlib: fix malformed upstream status
INFO: test_patches_upstream_status (common.CommonCheckLayer)
INFO:  ... expected failure
INFO: Traceback (most recent call last):
  File "/data/master/poky/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
    self.assertEqual(len(patches), 0 , \
AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
/data/master/meta-intel/recipes-graphics/gmmlib/files/0001-Add-new-DG2-device-IDs-194.patch

Signed-off-by: Lee Chee Yang <chee.yang.leeintel.com>
Signed-off-by: Anuj Mittal <anuj.mittalintel.com>