src/meta-openembedded:cockpit: Upgrade to 337
Get rid of remoeved configure options

ERROR: QA Issue: cockpit: configure was passed unrecognised options: --disable-pcp --enable-old-bridge --with-cockpit-ws-instance-user --disable-ssh --disable-polkit --with-cockpit-ws-instance-group --with-cockpit-group --with-cockpit-user [unknown-configure-option]

Signed-off-by: Khem Raj <raj.khemgmail.com>