src/meta-openembedded:amtk: Add missing dep on python3-pygments-native
Fixes
  File "TOPDIR/build/tmp/work/mips32r2-yoe-linux/amtk/5.6.1-r0/recipe-sysroot-native/usr/share/gtk-doc/python/gtkdoc/highlight.py", line 27, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'

Signed-off-by: Khem Raj <raj.khemgmail.com>