src/meta-openembedded:libsigc++-2.0: upgrade 2.10.2 -> 2.10.3
2020-03-25  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	2.10.3

2020-03-24  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	README: Describe building with Meson and Autotools

	and remove the description of the directory structure,
	which is not very useful.

2020-03-10  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	examples: Disable deprecated API when building with Meson

	Deprecated SIGCXX API is disabled when example programs are built
	with Autotools. Do the same when building with Meson.

2020-01-13  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	README: Describe building with Meson

2020-01-02  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	docs/reference/meson.build: Check if perl is found

	Don't use perl.path() when configuring Doxyfile, if perl is not found.
	Perl is not required, if build-documentation=false.
	Fixes #53

2019-12-30  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	meson.build: Change project name, sigc++ -> libsigc++

	Autotools make tarballs called libsigc++-x.y.z.tar.xz. No reason to
	change that. The leading "lib" is now also restored in some locations
	in the reference documentation.

2019-12-30  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	Update untracked/README

2019-12-29  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	meson.build: Check if .git is a directory or a file

	In a git worktree, .git is a regular file.

	See https://gitlab.gnome.org/GNOME/pangomm/merge_requests/8

2019-12-29  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	sigc++/meson.build: Library name is sigc-2.0

	Pointed out by Chun-wei Fan in PR #51.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	NMake Makefiles: Separate outdir by toolset version

	This is to reduce the likelihood of accidently mixing DLLs that are
	linked with different CRTs in the build tree.

	Also clean up rules a bit.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	build: Support NMake builds from Meson tarballs

	This adds inference rules to the NMake Makefiles to also look for the
	sources that are in untracked/, and to ensure that the generated MSVC
	build files (sigc++-config.h and sigc.rc) are copied into
	untracked/MSVC_NMake, so that they can be built properly even with
	NMake.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	meson: Build Windows .rc files on Windows

	This ensures that on Windows, the version info resources are indeed
	linked into the libsigc++ DLL.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	meson/Windows: Fix builds when builddir is a subdir of source tree

	It appears that Meson did not construct the paths properly for
	shutil.copy2() when building in a build directory that is a
	subdirectory of the sources, when using meson.current_build_dir(),
	possibly due how path separators are handled.

	Fix this by constructing the paths using project_build_root / 'MSVC_NMake'.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	meson.build: Fix 'meson dist' on Windows

	Since we are assured that we are using Python 3.x on when we run Meson, we
	do not really need to look for the 'python3' executable, but we could
	just use whatever Python interpreter that is used to run Meson.

	This will fix situations where it is commonly the case where we may have
	multiple Python 3.x installations on Windows (www.python.org, and those
	from Cygwin/mingw-w64), so that Meson really uses one and only one
	Python installation to run everything that is Python-related, which will
	thus fix '[meson|ninja] dist' on Visual Studio builds.

2019-12-29  Chun-wei Fan  <fanchunweisrc.gnome.org>

	Meson/MSVC: Support builds directly from GIT checkouts

	It appears that if one uses the m4 that is given by mingw-w64 (and
	perhaps Cygwin), that m4 is enough to generate the sources and headers
	that we need for the build.

	So, remove the lines saying building directly from GIT checkouts are not
	supported.

2019-12-24  Chun-wei Fan  <fanchunweisrc.gnome.org>

	meson: Ensure symbols are exported on MSVC builds

	Make sure the correct build macros are specified when building
	libsigc++, so that:

	-The symbols are properly exported
	-We do not break builds as a result of unecesary warnings

2019-12-24  Chun-wei Fan  <fanchunweisrc.gnome.org>

	meson: Relax MSVC version requirement to 2015

	libsigc++ requires a C++-11-compliant compiler, so we can just make the
	build look for Visual Studio 2015 instead of Visual Studio 2017 15.7.

	Visual Studio 2013 also works, but since it will spew out loads of
	warnings and the latest C++-11 version of glibmm is not buildable with
	Visual Studio 2013, let's just require Visual Studio 2015.

2019-12-24  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	Add support for building libsigc++-2.0 with Meson

	libsigc++-2.0 can be built with either Autotools or Meson.

2019-12-10  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	Make libsigc_manual.xml valid

	Fix errors reported by "xmllint --postvalid".

2019-07-03  Kjell Ahlstedt  <kjellahlstedtgmail.com>

	tests/test_track_obj: Fix for clang++

	clang++ complains if private members are unused, so make them protected.

	error: private field 'bar_' is not used [-Werror,-Wunused-private-field]

Signed-off-by: Andreas Müller <schnitzeltonygmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>