src/meta-openembedded:etcd-cpp-apiv3: Fix build with gprc 2.66+
GPR_ASSERT is removed from latest gprc

Fixes
   | /home/pokybuild/yocto-worker/meta-oe/build/build/tmp-glibc/work/core2-64-poky-linux/etcd-cpp-apiv3/0.15.4/git/src/v3/Action.cpp: In member function 'void etcdv3::Action::waitForResponse()':
   | /home/pokybuild/yocto-worker/meta-oe/build/build/tmp-glibc/work/core2-64-poky-linux/etcd-cpp-apiv3/0.15.4/git/src/v3/Action.cpp:101:5: error: 'GPR_ASSERT' was not declared in this scope
   |   101 |     GPR_ASSERT(got_tag == (void*) this);
   |       |     ^~~~~~~~~~

Signed-off-by: Khem Raj <raj.khemgmail.com>