src/meta-security:python3-pyinotify: Make asyncore support optional for Python 3
Simple fix for Python 3.12 since it dropped asyncore. Catches the import
error instead of using a version check so that the user can install the
compatibility package for any uses that can't be upgraded to asyncio or
similar immediately.

Fixes:
 # python3
 Python 3.12.1 (main, Dec 7 2023, 20:45:44) [GCC 13.2.0] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> import pyinotify
 Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/lib64/python3.12/site-packages/pyinotify.py", line 71, in <module>
 import asyncore
 ModuleNotFoundError: No module named 'asyncore'
 >>>

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>