src/meta-openembedded:pm-graph: parse separated cpu exec line
if cpu exec line was split into different line, there will be an error
when parse it:

  File "/usr/bin/sleepgraph", line 3165, in parseTraceLog
    proclist[name] = int(val[1])
IndexError: list index out of range

check this case and append to parse the unfinished line.

Signed-off-by: Liwei Song <liwei.songwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>