src/meta-openembedded:wireshark: update to new 2.4.5 series
[v2]
Fix epan/.libs/libwireshark.so: error: undefined reference to 'gpg_strerror'

and update to 2.4.5.

includes:
wnpa-sec-2018-05
The IEEE 802.11 dissector could crash. Bug 14442, CVE-2018-7335

wnpa-sec-2018-06
Multiple dissectors could go into large infinite loops. All ASN.1 BER dissectors (Bug 14444), along with the DICOM (Bug 14411), DMP (Bug 14408), LLTD (Bug 14419), OpenFlow (Bug 14420), RELOAD (Bug 14445), RPCoRDMA (Bug 14449), RPKI-Router (Bug 14414), S7COMM (Bug 14423), SCCP (Bug 14413), Thread (Bug 14428), Thrift (Bug 14379), USB (Bug 14421), and WCCP (Bug 14412) dissectors were susceptible.

wnpa-sec-2018-07
The UMTS MAC dissector could crash. Bug 14339, CVE-2018-7334

wnpa-sec-2018-08
The DOCSIS dissector could crash. Bug 14446, CVE-2018-7337

wnpa-sec-2018-09
The FCP dissector could crash. Bug 14374, CVE-2018-7336

wnpa-sec-2018-10
The SIGCOMP dissector could crash. Bug 14398, CVE-2018-7320

wnpa-sec-2018-11
The pcapng file parser could crash. Bug 14403, CVE-2018-7420

wnpa-sec-2018-12
The IPMI dissector could crash. Bug 14409, CVE-2018-7417

wnpa-sec-2018-13
The SIGCOMP dissector could crash. Bug 14410, CVE-2018-7418

wnpa-sec-2018-14
The NBAP disssector could crash. Bug 14443, CVE-2018-7419

Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>