src/poky:libwpe, wpebackend-fdo: add opengl to required DISTRO_FEATURES
* requires virtual/egl which isn't available without opengl in DISTRO_FEATURES
  as shown in world builds without it:
  ERROR: Nothing PROVIDES 'virtual/egl' (but openembedded-core/meta/recipes-sato/webkit/libwpe_1.4.0.1.bb, openembedded-core/meta/recipes-sato/webkit/wpebackend-fdo_1.4.1.bb DEPENDS on or otherwise requires it)

$ bitbake libwpe
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/egl' (but /OE/build/oe-core/openembedded-core/meta/recipes-sato/webkit/libwpe_1.4.0.1.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/kernel
  virtual/make
  virtual/perf
ERROR: Required build target 'libwpe' has no buildable providers.
Missing or unbuildable dependency chain was: ['libwpe', 'virtual/egl']

$ bitbake wpebackend-fdo
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/egl' (but /OE/build/oe-core/openembedded-core/meta/recipes-sato/webkit/wpebackend-fdo_1.4.1.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/kernel
  virtual/make
  virtual/perf
ERROR: Required build target 'wpebackend-fdo' has no buildable providers.
Missing or unbuildable dependency chain was: ['wpebackend-fdo', 'virtual/egl']

$ bitbake webkitgtk
ERROR: Nothing PROVIDES 'webkitgtk'
webkitgtk was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)

(From OE-Core rev: 7214af1d8ed9082cb4646951df8b5d97591a4876)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>