src/meta-openembedded:mpd: add commercial LICENSE_FLAGS when ffmpeg or aac PACKAGECONFIG is enabled
* resolves bitbake world error:
  ERROR: Nothing PROVIDES 'ffmpeg' (but meta-multimedia/recipes-multimedia/musicpd/mpd_0.20.22.bb DEPENDS on or otherwise requires it)
  ffmpeg was skipped: because it has a restricted license 'commercial'. Which is not whitelisted in LICENSE_FLAGS_WHITELIST
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'mpd', 'ffmpeg']

* aac is conditionally included in PACKAGECONFIG based on LICENSE_FLAGS
  since:

  commit f5d271fd545c5b78d4a8fbc81e54df454fa0d5e4
  Author: Armin Kuster <akuster808gmail.com>
  Date:   Mon Oct 1 08:05:28 2018 -0700

    mpd: enable aac PACKAGECONFIG only with commercial LICENSE_FLAGS

  maybe we could use the same for ffmpeg, but the conditional should
  be a bit more complicated, because the aac support is whitelisted by
  either commercial, commercial_faad2 or faad2 in LICENSE_FLAGS_WHITELIST
  not just currently checked 'commercial'.

  and we cannot use LICENSE_FLAGS conditional in both, because that leads to
  bb.data_smart.ExpansionError: Failure expanding variable LICENSE_FLAGS, expression was
  ${bb.utils.contains('PACKAGECONFIG', 'ffmpeg', 'commercial', '', d)}
  which triggered exception RecursionError: maximum recursion depth exceeded

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>