src/meta-openembedded:enscript: fix error with gcc-15
* Imported the submitted patch from:
  https://savannah.gnu.org/bugs/?66845
  to fix:
  http://errors.yoctoproject.org/Errors/Details/851187/
  ../../enscript-1.6.6/compat/regex.c:3565:13: error: too many arguments to function 're_match_2_internal'; expected 0, have 8
 3565 |       val = re_match_2_internal (bufp, string1, size1, string2, size2,
      |             ^~~~~~~~~~~~~~~~~~~  ~~~~

* Modified the Upstream-Status since the same content as
  0001-getopt-Include-string.h-for-strcmp-stcncmp-functions.patch is already in the backport.

Signed-off-by: mark.yang <mark.yanglge.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>