src/meta-openembedded:wxwidgets: enable webkit only with x11 or wayland
* otherwise webkit enabled by default in 7c3dccab64f2c1733169d6fcba56eeb139a05b45 will
  conflict with no_gui PACKAGECONFIG which is enabled in DISTROs without x11 and wayland
* fixes:
  ERROR: meta-oe/meta-oe/recipes-extended/wxwidgets/wxwidgets_3.2.8.bb:
  wxwidgets: PACKAGECONFIG[webkit] Conflict package config 'no_gui' set in PACKAGECONFIG.

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>