src/meta-virtualization:aardvark-dns, netavark: add seccomp to REQUIRED_DISTRO_FEATURES
* because of runtime dependency on slirp4netns

* fixes:
ERROR: Nothing RPROVIDES 'slirp4netns' (but meta-virtualization/recipes-containers/aardvark-dns/aardvark-dns_1.2.0.bb RDEPENDS on or otherwise requires it)
slirp4netns was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'slirp4netns' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['slirp4netns']
NOTE: Runtime target 'aardvark-dns' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aardvark-dns', 'slirp4netns']
NOTE: Runtime target 'netavark-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['netavark-dev', 'aardvark-dns', 'slirp4netns']
NOTE: Runtime target 'netavark' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['netavark', 'aardvark-dns', 'slirp4netns']
NOTE: Runtime target 'aardvark-dns-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aardvark-dns-dev', 'slirp4netns']

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>