src/meta-openembedded:xfce4-session: exclude machine-host dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* this whole machine-host is very bad idea, all changes from postinst
  will be removed when netbase package is upgraded (it has CONFFILES
  set but most users won't know that this entry was appended by
  machine-host package)
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: xfce4-session different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['dbusdbus_1.8.20.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'upowerupower_0.9.14.bb.do_packagedata', 'xfce4-sessionmachine-host.bb.do_packagedata', 'xfce4-sessionxfce4-session_4.12.1.bb.do_package', 'xfce4-sessionxfce4-session_4.12.1.bb.do_packagedata', 'xorg-appiceauth_1.0.7.bb.do_packagedata', 'xorg-appxinit_1.3.4.bb.do_packagedata'] to ['dbusdbus_1.8.20.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'upowerupower_0.9.14.bb.do_packagedata', 'xfce4-sessionmachine-host.bb.do_packagedata', 'xfce4-sessionxfce4-session_4.12.1.bb.do_package', 'xfce4-sessionxfce4-session_4.12.1.bb.do_packagedata', 'xorg-appiceauth_1.0.7.bb.do_packagedata', 'xorg-appxinit_1.3.4.bb.do_packagedata']
meta-openembedded/meta-xfce/recipes-xfce/xfce4-session/machine-host.bb.do_packagedata with hash 7b3f9a883729dfe908e17980476d10e2
 changed to
meta-openembedded/meta-xfce/recipes-xfce/xfce4-session/machine-host.bb.do_packagedata with hash f51309cb641c82a6d8e2dc5387bb6484
Hash for dependent task xfce4-sessionmachine-host.bb.do_packagedata changed from 7b3f9a883729dfe908e17980476d10e2 to f51309cb641c82a6d8e2dc5387bb6484

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>