src/meta-openembedded:packagekit: Fix build with new glib-2.0
Fixes errors like

| pk-main.c:223: error: undefined reference to 'g_thread_supported'
| collect2: error: ld returned 1 exit status
| make[3]: *** [packagekitd] Error 1

This version is dead upstream so this patch is local

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>