src/poky:gcr: fix one parallel build failure
ui/gcr-live-search.c includes gcr/gcr-marshal.h. Because missing
dependency, following error occurred intermittently during doing parallel
build:

 -o ui/libgcr-ui-3.so.1.0.0.p/gcr-live-search.c.o -c ../gcr-3.38.1/ui/gcr-live-search.c
../gcr-3.38.1/ui/gcr-live-search.c:32:10: fatal error: gcr/gcr-marshal.h: No such file or directory
   32 | #include "gcr/gcr-marshal.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

(From OE-Core rev: a6690c22952a315e6c6734a5936d9eb18e1b3004)

Signed-off-by: Changqing Li <changqing.liwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>