src/meta-openembedded:gexiv2: Fix do_package QA issue when usrmerge enabled.
ERROR: gexiv2-0.14.2-r0 do_package: QA Issue: gexiv2: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python3.11
  /usr/lib/python3.11/site-packages
  /usr/lib/python3.11/site-packages/gi
  /usr/lib/python3.11/site-packages/gi/overrides
  /usr/lib/python3.11/site-packages/gi/overrides/GExiv2.py
  /usr/lib/python3.11/site-packages/gi/overrides/__pycache__
  /usr/lib/python3.11/site-packages/gi/overrides/__pycache__/GExiv2.cpython-311.pyc

Signed-off-by: Lei Maohui <leimaohuifujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit eddc2571a759f208cd8e3e05f3ca14457b9169dc)
Signed-off-by: Armin Kuster <akuster808gmail.com>