src/meta-openembedded:opencv: Update contrib 4.5.2 -> 4.5.5
Patch [1] was dropped but contrib repo was not updated leading into the
glog link issues for the sfm module. Update opencv_contrib 4.5.2 ->
4.5.5.

Error:
/var/lib/yocto/builds/build_honister/tmp/work/bobcat-poky-linux/
qtec-screwcounter-camera/1.0+gitAUTOINC+7f76d8d874-r0/
recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/
x86_64-poky-linux/gcc/x86_64-poky-linux/11.2.0/ld:
/var/lib/yocto/builds/build_honister/tmp/work/bobcat-poky-linux/
qtec-screwcounter-camera/1.0+gitAUTOINC+7f76d8d874-r0/recipe-sysroot/
usr/lib/../lib/libopencv_sfm.so:
undefined reference to `google::LogMessageFatal::LogMessageFatal(char
const*, int)'

[1]:
meta-oe/recipes-support/opencv/opencv/0001-sfm-link-with-Glog_LIBS.patch

Signed-off-by: Daniel Gomez <dagmcrgmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>