src/meta-openembedded:breakpad: Drop SRCPV from PV
This causes errors like
OSError: [Errno 36] File name too long:

Signed-off-by: Khem Raj <raj.khemgmail.com>