src/poky:dhcpcd: Fix install conflict when enable multilib.
Error: Transaction test error:
   file /usr/share/man/man8/dhcpcd.8 conflicts between attempted installs of dhcpcd-doc-9.4.1-r0.cortexa57 and lib32-dhcpcd-doc-9.4.1-r0.armv7ahf_neon

The differences between the two files are as follows:
@@ -821,7 +821,7 @@
 If you always use the same options, put them here.
 .It Pa /usr/libexec/dhcpcd-run-hooks
 Bourne shell script that is run to configure or de-configure an interface.
-.It Pa /usr/lib64/dhcpcd/dev
+.It Pa /usr/lib/dhcpcd/dev
 Linux
 .Pa /dev
 management modules.

(From OE-Core rev: ae3aa0ded86ae13060989d19e64795b00946cd2e)

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
(cherry picked from commit 65ca2c4b7349a4f7dcfcc580d926a99c673deb60)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>