src/meta-openembedded:gnome-settings-daemon: Add introspection to UNKNOWN_CONFIGURE_WHITELIST
gobject-introspection is needed unconditionally therefore add "introspection"
to unknown configure option whitelist

Fixes
ERROR: QA Issue: gnome-settings-daemon: configure was passed unrecognised options: introspection [unknown-configure-option]

Signed-off-by: Khem Raj <raj.khemgmail.com>