src/poky:python3: Add ntpath.py to python core
The newer python3 recipe no longer includes ntpath.py in core, leading
to failures in pkg_resources:

  Traceback (most recent call last):
    File "/usr/bin/bmaptool", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 42, in <module>
      import ntpath
  ModuleNotFoundError: No module named 'ntpath'

(From OE-Core rev: 9ff61fa83a0a4f2a7b5b0376b6c48fb1173c9ac7)

Signed-off-by: Alex Kiernan <alex.kiernangmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>