src/meta-openembedded:python3-netaddr: add missing RDEPENDS on python3-pprint
core.py in the netaddr package has

   import pprint as _pprint

and so I hit

    from netaddr import OUI
  File "/usr/lib/python3.12/site-packages/netaddr/__init__.py", line 76, in <module>
    from netaddr.core import (
  File "/usr/lib/python3.12/site-packages/netaddr/core.py", line 9, in <module>
    import pprint as _pprint
ModuleNotFoundError: No module named 'pprint'

Add the missing RDEPENDS.

Signed-off-by: Rasmus Villemoes <raviprevas.dk>
Signed-off-by: Khem Raj <raj.khemgmail.com>