src/meta-openembedded:libconfig,libfile,libtest: Do not inherit allarch
These perl modules use cpan class, which adds build time dependency on
perl, and since perl is arch specific this ends up with sstate signature
differences for do_configure when arch is changed, therefore these
packages needs to be made part of arch package-arch

Fixes

ERROR: libconfig-autoconf-perl different signature for task do_configure.sigdata between qemux86copy and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /home/jenkins/oe/world/yoe/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 43053, PID: 16399
Hash for dependent task libconfig/libconfig-autoconf-perl_0.318.bb:do_prepare_recipe_sysroot changed from 66cd7f8d93afb36b314a0604e94f72151cb18410f395bc949156188a764ad68c to d9752dd39f67802473ebfe048ca1a688d684c7c31483e648c4e43bde9b16e3b5
Unable to find matching sigdata for /home/jenkins/oe/world/yoe/sources/meta-openembedded/meta-perl/recipes-perl/libconfig/libconfig-autoconf-perl_0.318.bb:do_prepare_recipe_sysroot with hashes 66cd7f8d93afb36b314a0604e94f72151cb18410f395bc949156188a764ad68c or d9752dd39f67802473ebfe048ca1a688d684c7c31483e648c4e43bde9b16e3b5

ERROR: libfile-slurper-perl different signature for task do_configure.sigdata between qemux86copy and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /home/jenkins/oe/world/yoe/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 39201, PID: 16448
Hash for dependent task libfile/libfile-slurper-perl_0.012.bb:do_prepare_recipe_sysroot changed from d6fd4eb704e706ed44daf37099d47fd188f6ac8c212c779dbfa7e40cff7bf449 to 9f0c17d2bf8389c634c143cc908e81f85b4d4bdab245199c86d4ae4480856d0d
Unable to find matching sigdata for /home/jenkins/oe/world/yoe/sources/meta-openembedded/meta-perl/recipes-perl/libfile/libfile-slurper-perl_0.012.bb:do_prepare_recipe_sysroot with hashes d6fd4eb704e706ed44daf37099d47fd188f6ac8c212c779dbfa7e40cff7bf449 or 9f0c17d2bf8389c634c143cc908e81f85b4d4bdab245199c86d4ae4480856d0d

ERROR: libtest-warnings-perl different signature for task do_configure.sigdata between qemux86copy and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /home/jenkins/oe/world/yoe/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 43651, PID: 16479
Hash for dependent task libtest/libtest-warnings-perl_0.028.bb:do_prepare_recipe_sysroot changed from 77d070ada82799a51cce33ae63f70dafb2c20111e0dca15afc041efea22f1cd4 to 3d0bd29b23c66f14d4041153683eaa3d4ee0098e2b023747801748eb49da6300
Unable to find matching sigdata for /home/jenkins/oe/world/yoe/sources/meta-openembedded/meta-perl/recipes-perl/libtest/libtest-warnings-perl_0.028.bb:do_prepare_recipe_sysroot with hashes 77d070ada82799a51cce33ae63f70dafb2c20111e0dca15afc041efea22f1cd4 or 3d0bd29b23c66f14d4041153683eaa3d4ee0098e2b023747801748eb49da6300

Signed-off-by: Khem Raj <raj.khemgmail.com>
Cc: Jens Rehsack <snonetbsd.org>