src/meta-virtualization:packagegroup-container: respect seccomp in DISTRO_FEATURES
* fix f53b101d455d7e7447fa83f2faecb5e05d595b3e

* you might want to skip whole packagegroup-netavark without
  seccomp, but without this parsing world in DISTRO without
  seccomp fails with:

ERROR: Nothing RPROVIDES 'netavark' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
netavark was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'netavark' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['netavark']
ERROR: Nothing RPROVIDES 'packagegroup-docker' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-docker'
NOTE: Runtime target 'packagegroup-docker' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-docker']
ERROR: Nothing RPROVIDES 'packagegroup-oci' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-oci'
NOTE: Runtime target 'packagegroup-oci' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-oci']
ERROR: Nothing RPROVIDES 'packagegroup-container' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-container'
NOTE: Runtime target 'packagegroup-container' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-container']
ERROR: Nothing RPROVIDES 'packagegroup-lxc' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-lxc'
NOTE: Runtime target 'packagegroup-lxc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-lxc']
ERROR: Nothing RPROVIDES 'packagegroup-cni' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-cni'
NOTE: Runtime target 'packagegroup-cni' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-cni']
ERROR: Nothing RPROVIDES 'aardvark-dns' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
aardvark-dns was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'aardvark-dns' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['aardvark-dns']
ERROR: Nothing RPROVIDES 'conmon' (but meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
conmon was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'conmon' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['conmon']

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>