src/poky:elfutils: fix build failure with musl
Fix below build failure with musl when ptest
enabled.
| In file included from ../../elfutils-0.176/tests/dwfl-proc-attach.c:33:
| ../../elfutils-0.176/lib/system.h:63:35: error: called object 'err' is not a function or function pointer
|  #define error(status, errno, ...) err(status, __VA_ARGS__)
|                                    ^~~
| ../../elfutils-0.176/tests/dwfl-proc-attach.c:92:5: note: in expansion of macro 'error'
|      error (-1, 0, "dwfl_linux_proc_attach pid %d: %s", pid,
|      ^~~~~
| ../../elfutils-0.176/tests/dwfl-proc-attach.c:79:7: note: declared here
|    int err;
|        ^~~

The root cause is because the conflicts between
vairable and function name, so change the variable
name to workaround it.

(From OE-Core rev: 48dbb1bd980f7ed17a612fa7c1be298f14955c3f)

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>