src/meta-openembedded:xfsdump: fix do_configure failure and remove from blacklist
Add '-D_FILE_OFFSET_BITS=64' to CFLAGS to fix the following do_configure
error.

  FATAL ERROR: cannot find a valid <xfs/xfs.h> header file.

Although -D_FILE_OFFSET_BITS=64 has already been defined in
include/builddefs.in, it only affects the compile process, leaving configure
process unaware of this value.

Remove from blacklist as the configure failure has been fixed by this patch.

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>