src/meta-openembedded:nlohmann-json: Fix SRCREV_FORMAT and do not package git metadata into ptests
SRCREV_FORMAT should append to default for considering both git
repositories.

the git hook scripts require shell to be installed on target and
it may want it from /usr/bin/sh and distro may not provide /usr/bin/sh
since its not having usrmerge distro feature.

Fixes
ERROR: nlohmann-json-3.11.2-r0 do_package_qa: QA Issue: /usr/lib/nlohmann-json/ptest/json_test_data/.git/hooks/update.sample contained in package nlohmann-json-ptest requires /usr/bin/sh, but no providers found in RDEPENDS:nlohmann-json-ptest? [file-rdeps]

Signed-off-by: Khem Raj <raj.khemgmail.com>