src/meta-cloud-services:python-routes: add rdepends on python-repoze.lru
Add the missing rdepends on python-repoze.lru or it will fail with:

  File "/usr/lib64/python2.7/site-packages/routes/mapper.py", line 5, in <module>
    from repoze.lru import LRUCache
  ImportError: No module named repoze.lru

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>