src/poky:piglit: add patch for lack of gbm_bo_map
[Piglit Bug #100978] -- https://bugs.freedesktop.org/show_bug.cgi?id=100978

When linking against Mali 450 r6, errors like the following
can be seen:
  ../../../../lib/libpiglitutil_gl.so.0: undefined reference to `gbm_bo_unmap'
  ../../../../lib/libpiglitutil_gl.so.0: undefined reference to `gbm_bo_map'
  collect2: error: ld returned 1 exit status
  make[2]: *** [bin/point-sprite] Error 1

This is due to gbm_bo_map() and gbm_bo_unmap() being recently
added but not yet implemented by all graphics drivers.

Instead of relying on GBM's version, actually try to link
against those symbols.

Upstream-Status: Submitted [piglitlists.freedesktop.org]

(From OE-Core rev: 2e0c8a510ee60d4ca97e58184c48995cd88a823f)

Signed-off-by: Daniel Díaz <daniel.diazlinaro.org>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>