src/meta-openembedded:xserver-nodm-init-2.0: Remove recipe
The version in oe-core should now do everything this one does with one
exception: it does not RDEPEND on xserver-common. This dependency now
needs to be set explicitly.

Signed-off-by: Jussi Kukkonen <jussi.kukkonenintel.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>