src/meta-amd:bsp/grub: workaround SSE register return with SSE disabled error
When GRUB is compiled with -march=znver1 or -march=znver2 using the GCC
v9.3 and above, the compilation fails with the following error:

recipe-sysroot-native/usr/lib/x86_64-amd-linux/gcc/x86_64-amd-linux/
  10.2.0/include/shaintrin.h:40:1:
  error: SSE register return with SSE disabled

What's interesting, is that -march=skylake also implies -mbmi which
defines __BMI__ but compilation succeeds.

It is probably due to different BMI implementations on AMD and INTEL
processors and the way compiler uses related instructions.

Signed-off-by: Arsalan H. Awan <Arsalan_Awanmentor.com>