src/poky:ca-certificates: Fix reproducibilty and multilib issue
This command was dependent on the order of files on the disk and for multilib builds
could result in:

Error: Transaction check error:
  file /etc/ca-certificates.conf conflicts between attempted installs of ca-certificates-20190110-r0.core2_32 and lib64-ca-certificates-20190110-r0.x86_64

Sorting the file makes things deterministic.

(From OE-Core rev: c8f329fc562c9eecdcc1cb10d2c7661f44110fb4)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>