src/poky:distutils.bbclass: Handle python-backport modules
When installing backport modules they stumble upon each other, complaining with
the following error:

ERROR: The recipe python-backports-ssl is trying to install files into a shared
area when those files already exist.

This is the correct behavior since thats just the way they were designed, all backport
modules provide an __init__.py file (the same among all packages), and without it they
simply wouldnt work.

distutils handles FILES_${PN}* variables for python packages, but it uses wildcards
to include the required files, hence removing the __init__.py files from each backport
package during build time is impossible since it doenst actually contain that value,
this patch simply removes the __init__.py* files from the staging area if they already
exist on sysroot, this way, these are not included in FILES_${PN} anymore, fixing the
issue mentioned above.

[YOCTO #8207]

(From OE-Core rev: e607a89267949b3d5e199b139f752db6000eac25)

Signed-off-by: Alejandro Hernandez <alejandro.hernandezlinux.intel.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>