src/meta-openembedded:minini: fix build when SECURITY_CFLAGS includes -pie -fpie
Separating compile and link steps avoids build errors when
security_flags.inc is used:

  | DEBUG: Executing shell function do_compile
  | ../sysdeps/i386/start.S:98: error: undefined reference to 'main'
  | collect2: error: ld returned 1 exit status

Signed-off-by: Andre McCurdy <armccurdygmail.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>