src/meta-openembedded:breakpad: fix patch striplevel to avoid 'devtool modify breakpad' error
Since the patch is modifying files in a self-contained git repo that is
.gitignored, git ends up thinking we have just touched a submodule.

This leads to 'devtool modify breakpad' failing with:

    Exception: bb.process.ExecutionError: Execution of 'git add .; git -c
    user.name="OpenEmbedded" -c user.email="oe.patchoe" commit -a -m
    "Committing changes from do_patch

    %% ignore - from do_patch"' failed with exit code 1:
    On branch devtool
    Changes not staged for commit:
            modified:   src/third_party/lss (modified content)

            no changes added to commit

            ERROR: Function failed: patch_task_postfunc

Signed-off-by: Chris Laplante <chris.laplanteagilent.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>