src/meta-openembedded:mariadb: upgrade to 10.5.4
* Remove one backported patch
* Remove SRC_URI[md5sum]
* Rebase two patches to fix fuzz warnings
* Add curl depends to fix below error:
  | ./mariadb-10.5.4/storage/maria/libmarias3/libmarias3/marias3.h:26:10: fatal error: curl/curl.h: No such file or directory

* update the pam_user_map.so install logic as below commit introduced in this new
  mariadb version
  236aed3f5f0 MDEV-21656: Wrong directory for pam_user_map.so JIRA:https://jira.mariadb.org/browse/MDEV-17292

* Backport a patch to fix the undefined reference to `crc32c_arm64' on arm64

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>