src/meta-openembedded:lirc: Fix build with usrmerge feature building on ubuntu hosts
We get a very cryptic error during do_package

ERROR: Didn't find service unit 'lircmd.service', specified in SYSTEMD_SERVICE:lirc.

The reason is on ubuntu build hosts configure pokes at build host and
decided its ubuntu and applies hardcoded value of /lib/systemd/system
for systemdunitdir instead of /usr/lib/systemd/system as passed from
recipe

Signed-off-by: Khem Raj <raj.khemgmail.com>