src/meta-openembedded:libplacebo: fix demos PACKAGECONFIG
In case the demos PACKAGECONFIG is enabled, linking fails with
the following error:

| /usr/src/debug/libplacebo/7.349.0/demos/plplay.c:669:(.text.startup+0x90): undefined reference to `parse_args'
| collect2: error: ld returned 1 exit status

The implementation of the missing function is guarded erroneously by
an ifdef flag (HAVE_NUKLEAR, which is only true in case headers from the nuklear
library are present - but in this recipe they are not included).

This patch moves the implementation of this function outside of the ifdef to
avoid the build failure.

Signed-off-by: Gyorgy Sarvari <skandigraungmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>