src/meta-openembedded:mozjs: Fix QA errors when building with multilib
We do not take care of default libdir which accidently
works out to be ok for non-multilib case since its /usr/lib

Fixes error like

ERROR: QA Issue: mozjs: Files/directories were installed but not shipped
  /usr/lib
  /usr/lib/libmozjs-17.0.a
  /usr/lib/libmozjs-17.0.so
  /usr/lib/pkgconfig
  /usr/lib/.debug
  /usr/lib/pkgconfig/mozjs-17.0.pc
  /usr/lib/.debug/libmozjs-17.0.so

Signed-off-by: Khem Raj <raj.khemgmail.com>
Acked-by: Koen Kooi <koendominion.thruhere.net>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>