src/poky:python3-libarchive-c: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import libarchive
 [snip]
 ModuleNotFoundError: No module named 'ctypes'
 ModuleNotFoundError: No module named 'mmap'

(From OE-Core rev: b3a2615878bc7515a7bdace525dc27be45f158e2)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>