src/poky:speexdsp: initial recipe
speexdsp was split off from speex in 1.2rc2, so we need a separate
recipe for speexdsp when before we can upgrade speex.

The speex recipe has so far used the --enable-fixed-point configure
option unconditionally, but I believe that was a mistake, so I
dropped that. The option is still enabled if TARGET_FPU is set to
"soft". Commit e8f707f16a38d85535593a32efff6dcbf4ddb203 added the
TARGET_FPU check, and I think that commit should have removed
--enable-fixed-point from the static configure options, like it
removed --disable-float-api.

The NEON code caused a build failure on qemuarm64. As a workaround,
I disabled NEON optimizations when building for aarch64.

I added a patch that fixes a build failure in alsa-plugins. Compiling
alsa-plugins against the new speexdsp version without the patch
resulted in this error:

In file included from .../usr/include/speex/speexdsp_types.h:122:0,
                 from .../usr/include/speex/speex_preprocess.h:46,
                 from .../alsa-plugins-1.0.29/speex/pcm_speex.c:23:

.../usr/include/speex/speexdsp_config_types.h:13:9: error: unknown type name 'uint16_t'
 typedef uint16_t spx_uint16_t;
         ^

(From OE-Core rev: bb826645d188e5ea78718f3ad4b2e420eec3b354)

(From OE-Core rev: 28b7bccd226c4d9040ef0d8199a29e74f2da72b1)

Signed-off-by: Tanu Kaskinen <tanu.kaskinenlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>