src/poky:libsdl2: Disable video-rpi
When building on Raspbery Pi OS/64-bit, libsdl2 fails with
the error:
   .../tmp/work/aarch64-linux/libsdl2-native/2.9.12-r0/SDL2-2.0.12/src/video/raspberry/SDL.rpivideo.h:47:5:
     error: unknown type name 'EGL_DISPMANX_WINDOW_T'
     EGL_DISPMANX_WINDOW_T dispman_window;

Disable video-rpi to avoid the problem since video suppport is
not needed for rpi and this configuration option is harmless when
building on x86-64 hosts.

(From OE-Core rev: 51009ed1b88aa391aae819fd800b907badc2be8c)

Signed-off-by: Randy MacLeod <Randy.MacLeodwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>