src/meta-openembedded:python3-pydbus: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pydbus
 [snip]
 ModuleNotFoundError: No module named 'socket'
 ModuleNotFoundError: No module named 'logging'

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>