src/poky:shadow: Fix rootfs creation errors
error: file /usr/share/man/man1/su.1 from install of shadow-doc-4.2.1
           conflicts with file from package coreutils-doc-6.9-r5

(From OE-Core rev: 52d3d9e1ab0b510d93c4915baf2a85b9cc949205)

Signed-off-by: Dai Caiyun <daicy.fnstcn.fujitsu.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>