src/meta-openembedded:udpcast: add missing manpages PACKAGECONFIG
The manpages.bbclass adds the 'manpages' PACKAGECONFIG but this isn't
defined:

    ERROR: QA Issue: udpcast: invalid PACKAGECONFIG: manpages [invalid-packageconfig]

There is not an option to disable the manpages, so add a stub
PACKAGECONFIG to silence this error.

Signed-off-by: Ross Burton <ross.burtonarm.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>