src/poky:staging: Handle files moving between dependencies
Currently, if files move between recipes, do_prepare_sysroot can fail with a message like

Exception: FileExistsError: [Errno 17] File exists:
'TMPDIR/sysroots-components/core2-64/libx11/usr/include/X11/extensions/XKBgeom.h' ->
'TMPDIR/work/core2-64-poky-linux/gtk+3/3.24.8-r0/recipe-sysroot/usr/include/X11/extensions/XKBgeom.h'

This is because files are removed and then added per package. What needs to
happen is all removes need to be processed, then all additions.

This patch changes the code to process in two phases, removals first, then additions,
which avoids the problem.

(From OE-Core rev: e3e5ace6e68d5fe68e4add301a44c1a1b8607411)

Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>