src/poky:tune-arm9tdmi.inc: include arm9tdmi in PACKAGE_ARCHS
* when ARM_INSTRUCTION_SET isn't set to thumb, the tune-arm9tdmi.inc isn't
  usable and fails with:
  ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Error, the PACKAGE_ARCHS variable (all any noarch arm armv4 armv4t arm9tdmit fake_arm9tdmi) for DEFAULTTUNE (arm9tdmi) does not contain TUNE_PKGARCH (arm9tdmi).

  Summary: There was 1 ERROR message shown, returning a non-zero exit code.

(From OE-Core rev: 7c2f9bf09c930da335aa88a201656df1e62f3bbd)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>