src/meta-openembedded:microsoft-gsl: Upgrade 4.0.0 -> 4.2.0 to allow CMake 4+ compatibility
- Drop patches because already fixed in newer version

- Fix compile error when compiled with Clang:

assertion_tests.cpp:40:1: error: use of the 'maybe_unused' attribute is a C++17 extension [-Werror,-Wc++17-attribute-extensions]
   40 | TEST(assertion_tests, expects)
      | ^

According to the upstream recommendation, passing the -DGSL_CXX_STANDARD=17 flag to CMake resolves the problem.
This patch applies the suggested workaround until a more permanent solution is provided from upstream.

Upstream discussion -> https://github.com/microsoft/GSL/issues/1178

Changelog:

https://github.com/microsoft/GSL/compare/v4.0.0...v4.2.0
https://github.com/microsoft/GSL/releases/tag/v4.2.0
https://github.com/microsoft/GSL/releases/tag/v4.1.0

Fix:

| CMake Error at tests/CMakeLists.txt:1 (cmake_minimum_required):
|   Compatibility with CMake < 3.5 has been removed from CMake.
|
|   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|   to tell CMake that the project requires at least <min> but has been updated
|   to work with policies introduced by <max> or earlier.
|
|   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
|
|
| -- Configuring incomplete, errors occurred!

Signed-off-by: Alper Ak <alperyasinak1gmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>