src/meta-openembedded:dlt-daemon: Bump to latest revision on master
This helps fix compile errors seen with clang
e.g.
src/lib/dlt_user.c:455:11: error: address argument to atomic operation must be a pointer to _Atomic type ('bool *' invalid)
    if (!(atomic_compare_exchange_strong(&dlt_user_initialised, &expected, true)))
          ^                              ~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khemgmail.com>