src/meta-openembedded:tracker: dont inherit gsettings
this fixes an issue I encountered on raspberrypi4-64 at do_rootfs:
ERROR: hyprland-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['tracker'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /home/flk/poky/build-raspi/tmp/work/raspberrypi4_64-poky-linux/hyprland-image/1.0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /home/flk/poky/build-raspi/tmp/work/raspberrypi4_64-poky-linux/hyprland-image/1.0/temp/log.do_rootfs.629667
ERROR: Task (/home/flk/poky/meta-hyprland-image/recipes-core/images/hyprland-image.bb:do_rootfs) failed with exit code '1'

Signed-off-by: Markus Volk <f_l_kt-online.de>
Signed-off-by: Khem Raj <raj.khemgmail.com>