src/meta-openembedded:gnome-calculator: add opengl to REQUIRED_DISTRO_FEATURES
gnome-calculator depends on gtk4 which depends on libepoxy(an opengl
related library) [1].

Fixes:
   ERROR: Nothing PROVIDES 'gtk4-native' (but /build/layers/meta-openembedded/meta-gnome/recipes-gnome/gnome-calculator/gnome-calculator_42.2.bb DEPENDS on or otherwise requires it)
  gtk4-native was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gnome-calculator', 'gtk4-native']

[1] https://github.com/anholt/libepoxy/

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>