src/meta-virtualization:openvswitch: add missing python modules to execute ovs-test program
ovs-test program requires python-twisted and ovstest python
modules to execute successfully. The changes fix below
errors:

-- snip --
rootqemux86:~# ovs-test
Traceback (most recent call last):
  File "/usr/bin/ovs-test", line 31, in <module>
    import twisted
ImportError: No module named twisted
rootqemux86:~# ovs-test
Traceback (most recent call last):
  File "/usr/bin/ovs-test", line 33, in <module>
    import ovstest.args as args
ImportError: No module named ovstest.args
rootqemux86:~#
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappamvista.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>