src/meta-security:linux-yocto: update the bbappend to 5.x
As linux-yocto upgraded to 5.x in oe-core, update
the bbappend to 5.x to remove the warning

ERROR: No recipes available for:
  .../meta-security/meta-tpm/recipes-kernel/linux/linux-yocto_4.%.bbappend

This patch hasn't been verified any further than allowing bitbake
to complete with a non-linux-yocto kernel. In particular options could
be different, or new ones needed / desired.

Signed-off-by: André Draszik <gitandred.net>
Signed-off-by: Armin Kuster <akuster808gmail.com>