src/meta-tensorflow:tensorflow: fix build lite label_image failed
It caused undefined reference neon_tensor_utils failure
...
|tensor_utils.cc:(.text._ZN6tflite12tensor_utils18ReductionSumVectorEPKfPfii+0x0):
undefined reference to `tflite::tensor_utils::NeonReductionSumVector(float const*,
float*, int, int)'
...

Define Yocto specific cpu `armeabi' for lite label_image

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>