src/meta-openembedded:syslog-ng: fix a multilib build failure and a QA issue
* Use BPN instead of PN to fix the multilib build failure:
ERROR: Function failed: SYSTEMD_SERVICE_lib32-syslog-ng value
lib32-syslog-ng.service does not exist

* Do not add syslog-init for systemd to fix the QA issue:
WARNING: syslog-ng: alternative target (/etc/init.d/syslog or
/etc/init.d/syslog.syslog-ng) does not exist, skipping...
WARNING: syslog-ng: NOT adding alternative provide /etc/init.d/syslog:
/etc/init.d/syslog.syslog-ng does not exist
WARNING: alt_link == alt_target: /etc/init.d/syslog ==
/etc/init.d/syslog

Signed-off-by: Jackie Huang <jackie.huangwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>