src/poky:grub git: update to latest git
Drop the 2 patches since the functionality is upstream now.
Also sync PACKAGECONFIG with grub 2.00 recipe.

The debugedit problem for 64 bit machines in do_package is still present, though:

ERROR: debugedit failed with exit code 256 (cmd was '/build/linaro/build/build/tmp-eglibc/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit' -b '/build/linaro/build/build/tmp-eglibc/work/aarch64-oe-linux' -d '/usr/src/debug' -i -l '/build/linaro/build/build/tmp-eglibc/work/aarch64-oe-linux/grub/2.00+AUTOINC+0776112c53-r0/debugsources.list' '/build/linaro/build/build/tmp-eglibc/work/aarch64-oe-linux/grub/2.00+AUTOINC+0776112c53-r0/package/usr/lib/grub/arm64-efi/cpio_be.module'):
/build/linaro/build/build/tmp-eglibc/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit: /build/linaro/build/build/tmp-eglibc/work/aarch64-oe-linux/grub/2.00+AUTOINC+0776112c53-r0/package/usr/lib/grub/arm64-efi/cpio_be.module: Unhandled relocation 258 in .debug_info section
ERROR: Function failed: split_and_strip_files
ERROR: Logfile of failure stored in: /build/linaro/build/build/tmp-eglibc/work/aarch64-oe-linux/grub/2.00+AUTOINC+0776112c53-r0/temp/log.do_package.29234
ERROR: Task 10 (/build/linaro/build/openembedded-core/meta/recipes-bsp/grub/grub_git.bb, do_package) failed with exit code '1'

(From OE-Core rev: cd29ff3927a6deae5e808525bd56acf7b4b0b60c)

Signed-off-by: Koen Kooi <koen.kooilinaro.org>
Signed-off-by: Saul Wold <sgwlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>