src/poky:llvm: Point llvm-config to one built with llvm-native
If not defined, llvm build system tries to build one
which then confuses the OE QA system since its building
native tool and target packages in same package build
moreover it is not required since we already have it via
llvm-native

Fixes
ERROR: llvm-6.0-r0 do_package_qa: QA Issue: llvm: The compile log indicates that host include and/or library paths were used.

(From OE-Core rev: 7153a17166d9a94fd0ddc36d597a0140979d58ff)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>