src/poky:recipeutils-test: Add missing LIC_FILES_CHKSUM
Fixes
ERROR: QA Issue: recipeutils-test: Recipe file fetches files and does
not have license file information (LIC_FILES_CHKSUM) [license-checksum]

(From OE-Core rev: ee65f7ab11302982124bcd1974a05c87342ab28e)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>