src/poky:tclibc-baremetal: Adds virtual/crypt to ASSUME_PROVIDED
When trying to build meta-toolchain using TCLIBC = "baremetal"
bitbake throws an error due to a mising dependency:

ERROR: Nothing PROVIDES 'virtual/crypt'

glibc PROVIDES virtual/crypt but was skipped:
PREFERRED_PROVIDER_virtual/libc set to musl, not glibc
musl PROVIDES virtual/crypt but was skipped:
PREFERRED_PROVIDER_virtual/i586-poky-elf-libc-for-gcc set to baremetal,
not musl
libxcrypt PROVIDES virtual/crypt but was skipped: Recipe only applies in
nativesdk case for now

This is caused by the changes on commit:
29f65bda6d2c9fea4adb125c4857ee64f9312b9f
nativesdk-glibc: Split glibc and libcrypt to use libxcrypt instead

This is where the concept of virtual/crypt was introduced.

This patch adds virtual/crypt to ASSUME_PROVIDED on tclibc-baremetal,
providing the missing wiring to build meta-toolchain on baremetal
correctly.

(From OE-Core rev: 26a93d2bf7504bf5f3adb085ed2882ae1b1a3701)

Signed-off-by: Alejandro Enedino Hernandez Samaniego <alejandrxilinx.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>