src/poky:python-numpy: fix build for libn32
Fix do_compile failure for libn32. To reproduce, use the following config.

  MACHINE = "qemumips64"
  require conf/multilib.conf
  MULTILIB_GLOBAL_VARIANTS_append = " libn32"
  MULTILIBS ?= "multilib:lib32 multilib:libn32"
  DEFAULTTUNE_virtclass-multilib-lib32 ?= "mips"
  DEFAULTTUNE_virtclass-multilib-libn32 ?= "mips64-n32"

The error message is as following.

  numpy/core/include/numpy/npy_common.h:206:10: error: #error Unsupported size for type off_t

(From OE-Core rev: b659b6dcb6be203e8c7bc678c902d4a31ce9fe70)

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>