src/poky:python3-cryptography: remove --benchmark-disable option
The new version introduced below change, so remove the option
to avoid python3-pytest-benchmark rdepends to fix the gap.
496703c8 Refs #7079 -- added basic scaffholding for benchmarks (#7087)

Fixes:
  # ./run-ptest
  Free memory: 31.283 GB
  ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
  pytest: error: unrecognized arguments: --benchmark-disable
  inifile: /usr/lib/python3-cryptography/ptest/pyproject.toml
  rootdir: /usr/lib/python3-cryptography/ptest

(From OE-Core rev: 7fdfa8504dcc9c15e957256c97b43eec5291216c)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Luca Ceresoli <luca.ceresolibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>