src/poky:mc: unify curses initialization
Since ncurses upgraded to 6.0+20170715, it compile failed
...
| ../../../mc-4.8.19/lib/tty/tty-ncurses.c:199:13: error: dereferencing
pointer to incomplete type 'TERMINAL {aka struct term}'
|      cur_term->Nttyb.c_cc[VINTR] = CTRL ('g');   /* ^g */
|              ^~
...

Backport a patch from upstream fixed the issue.

(From OE-Core rev: fc89bfa89aa785871f7999f2835dbcea06e2823b)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>