src/poky:sbc: Fix for gcc 15 compile error
With the move to gcc 15, the code is now generating a compile error.

../sbc-2.1/sbc/sbc_primitives_armv6.c:284:9:
   error: too many arguments to function 'sbc_analyze_eight_armv6';
      expected 0, have 3

Simple fix is to drop the C standard down to gnu17 to avoid this new
error.

(From OE-Core rev: 2dc0664e966cd8d4c99798cc997c192785773e31)

Signed-off-by: Ryan Eatmon <reatmonti.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briandbootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>