src/meta-virtualization:packagegroup-container: fix do_package_wrte_rpm issue in multilib build
When build lib32-packagegroup-container, the follwing error occurred:

ERROR: lib32-packagegroup-container-1.0-r0 do_package_write_rpm: An allarch packagegroup shouldn't
depend on packages which are dynamically renamed (lib32-ipset-dbg to ipset-dbg)
ERROR: lib32-packagegroup-container-1.0-r0 do_package_write_rpm: An allarch packagegroup shouldn't
depend on packages which are dynamically renamed (lib32-ipset to ipset)
ERROR: lib32-packagegroup-container-1.0-r0 do_package_write_rpm: An allarch packagegroup shouldn't
depend on packages which are dynamically renamed (lib32-ipset-dev to ipset-dev)

To resolve this issue in a multilib build, set PACKAGE_ARCH appropriately to avoid using allarch.

Signed-off-by: Zhang Peng <peng.zhang1.cnwindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>