src/meta-cloud-services:python-psycopg2: reinstate patch to avoid pg_config
When building we get an error:
Error: pg_config executable not found.

Previously there was a patch that removed references to pg_config.
This patch was dropped during the version uprev for an unknown
reason. Reinstate this patch with minor updates to allow it to patch
the new version of python-psycopg2 and get the build working again.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>