src/poky:librsvg: enable vapi build
Otherwise gnome-chess will fail like this:

| error: Package `librsvg-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
| Compilation failed: 1 error(s), 0 warning(s)

(From OE-Core rev: e9d7a381ef47f41d52a2b57de1a5a2920a35f222)

Signed-off-by: Markus Volk <f_l_kt-online.de>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit ed814eff90677f894d9eb480d8d4389c64a35820)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>