src/meta-openembedded:v4l-utils: Add PACKAGECONFIG for v4l2-tracer to fix determinstic build
Fixed do_package error when json-c is in the build dependencies chain:
ERROR: QA Issue: -dev package libv4l-dev contains non-symlink .so '/usr/lib/libv4l2tracer.so' [dev-elf]

This recipe builds out files such as av4l1compat.so v4l2convert.so and
libv4l2tracer.so which are not symlinks.

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>