src/meta-openembedded:net-snmp: refresh patches
Refreshed patches for 5.8 due to the following:

    ERROR: net-snmp-5.8-r0 do_patch: Command Error: 'quilt --quiltrc .../net-snmp/5.8-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
    Applying patch 0001-Add-pkg-config-support-for-building-applications-and.patch
    patching file configure
    ...
    Hunk #1 succeeded at 32248 with fuzz 2 (offset 1826 lines).
    Hunk #2 FAILED at 31447.
    1 out of 2 hunks FAILED -- rejects in file configure
    ...
    Patch 0001-Add-pkg-config-support-for-building-applications-and.patch does not apply (enforce with -f)

Signed-off-by: Patrick Williams <patrickstwcx.xyz>
Signed-off-by: Khem Raj <raj.khemgmail.com>