src/meta-openembedded:ckermit: Pass -DNOARROWKEYS by default
glibc 2.28+ has caught up with rest of libraries
and now build complains in same manner as musl

ckucmd.c: In function 'cmdconchk':
ckucmd.c:7386:14: error: 'FILE' {aka 'struct _IO_FILE'} has no member named '_cnt'
     x = stdin->_cnt;
              ^~

therefore add -DNOARROWKEYS even for glibc as well

Signed-off-by: Khem Raj <raj.khemgmail.com>