src/meta-openembedded:gst-instruments: enable ui PACKAGECONFIG only with GTK3DISTROFEATURES
* fixes:
  ERROR: Nothing PROVIDES 'gtk+3' (but meta-oe/meta-multimedia/recipes-support/gst-instruments/gst-instruments_git.bb DEPENDS on or otherwise requires it)
  gtk+3 was skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES

Signed-off-by: Martin Jansa <martin.jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>