src/meta-openembedded:daemontools: fix build with gcc-15
* Fix prototype declaration and too many arguments function errors due to outdated style
byte_chr.c:9:1: error: number of arguments doesn't match prototype
    9 | {
      | ^
In file included from byte_chr.c:3:
byte.h:6:21: error: prototype declaration
    6 | extern unsigned int byte_chr();
      |                     ^~~~~~~~
...
./compile buffer_get.c
buffer_get.c: In function 'oneread':
buffer_get.c:12:9: error: too many arguments to function 'op'; expected 0, have 3
   12 |     r = op(fd,buf,len);
      |         ^~ ~~
...
supervise.c: In function 'doit':
supervise.c:144:11: error: too many arguments to function 'wait_nohang'; expected 0, have 1
  144 |       r = wait_nohang(&wstat);
      |           ^~~~~~~~~~~ ~~~~~~

Signed-off-by: mark.yang <mark.yanglge.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>