src/meta-openembedded:gjs: Deleted gsettings from gsettings
gsettings shouldn't be added and it causes an error in do_rootfs.

%post(gjs-1.82.1-r0.aarch64): scriptlet start
%post(gjs-1.82.1-r0.aarch64): execv(/bin/sh) pid 217720
+ set -e
+ glib-compile-schemas /datadrive/workdir/build-dir/build-daily/tmp/work/armv8-linux/all-test/rr/rootfs/usr/share/glib-2.0/schemas
Error opening directory “/datadrive/workdir/build-dir/build-daily/tmp/work/armv8-linux/all-test/rr/rootfs/usr/share/glib-2.0/schemas”: No such
file or directory

......

ERROR: Postinstall scriptlets of ['gjs'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Signed-off-by: Lei Maohui <leimaohuifujitsu.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>