src/meta-openembedded:pango: upgrade to 1.29.4
* pango older than 1.29.1 causes ie libglade build fail with
  /usr/include/pango-1.0/pango/pango-script.h:132:12: error: unknown type name 'G_CONST_RETURN'

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Koen Kooi <koendominion.thruhere.net>