src/meta-tensorflow:build tensorflow-for-poets conditionally
Build tensorflow-for-poets only if tensorflow 1.x is available,
otherwise skip it with message:
...
ERROR: Nothing PROVIDES 'tensorflow-for-poets' tensorflow-for-poets was skipped:
It requires tensorflow 1.x, add 'TF_ARGS_EXTRA = "--config=v1"' to local.conf
...

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>