src/meta-openembedded:oprofile: drop kernel-vmlinux from RRECOMMENDS
* now with virtual/kernel dependency dropped we don't want to depend on kernel signature just for
  this RRECOMMENDS
* fixes:
   === Comparing signatures for task do_package_write_ipk.sigdata between hammerhead and mako ===
  ERROR: oprofile different signature for task do_package_write_ipk.sigdata between hammerhead and mako
  NOTE: Starting bitbake server...
  runtaskdeps changed:
  ['binutils/binutils_2.32.bb.do_packagedata', -linux/linux-lg-hammerhead_git.bb.do_packagedata, +linux/linux-lg-mako_git.bb.do_packagedata, 'opkg-utils/opkg-utils_0.4.1.bb.do_populate_sysroot:virtual:native oprofile/oprofile_1.3.0.bb.do_package oprofile/oprofile_1.3.0.bb.do_packagedata pseudo/pseudo_git.bb.do_populate_sysroot:virtual:native xz/xz_5.2.4.bb.do_populate_sysroot:virtual:native']
  linux/linux-lg-hammerhead_git.bb.do_packagedata with hash 0c5215deb4737611ad413f57cf5fbdef8a9b2cc6d04035f754a4e93fb38f61d1
   changed to
  linux/linux-lg-mako_git.bb.do_packagedata with hash 0f3b34773ca3e590739754c25959feb7cdcd67cf7904ac7fe6cc535e8d6519a8
  Dependency on task linux/linux-lg-mako_git.bb.do_packagedata was added with hash 0f3b34773ca3e590739754c25959feb7cdcd67cf7904ac7fe6cc535e8d6519a8
  Dependency on task linux/linux-lg-hammerhead_git.bb.do_packagedata was removed with hash 0c5215deb4737611ad413f57cf5fbdef8a9b2cc6d04035f754a4e93fb38f61d1

  ERROR: 1 errors found in /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/sstate-diff/1563368432/signatures.mako.do_package_write_ipk.sigdata.log

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>