src/poky:packagegroup-self-hosted: include missing (pod2man scp ssh) RPEDENDS packages
Otherwise, the following bitbake error is observed

    rootqemux86-64:~/openembedded-core/build# bitbake -e
    NOTE: Starting bitbake server...
    ERROR: Unable to start bitbake server
    ERROR: Last 10 lines of server log /home/root/openembedded-core/build/bitbake-cookerdaemon.log:
      File "/home/root/openembedded-core/bitbake/lib/bb/cooker.py", line 197, in __init__
        self.initConfigurationData()
      File "/home/root/openembedded-core/bitbake/lib/bb/cooker.py", line 348, in initConfigurationData
        self.databuilder.parseBaseConfiguration()
      File "/home/root/openembedded-core/bitbake/lib/bb/cookerdata.py", line 323, in parseBaseConfiguration
        raise bb.BBHandledException
    bb.BBHandledException
    NOTE: Starting bitbake server...
    ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
      pod2man scp ssh

(From OE-Core rev: 2ece64bf8cb8841e2e1db87d6c426f3f1637e8a7)

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalezlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>