src/meta-openembedded:inetutils: make -syslog rconflict with other system loggers
With oe-core commit cdcebd81c872cb7386c658998e27cf24e1d0447c
[initscripts: don't use update-alternatives] we start seeing a a
rootfs generation failure when both sysklogd and inetutils are present
in the image:

ERROR: do_rootfs: [log_check] : found 1 error message in the logfile:
[log_check] update-alternatives: Error: not linking
.../0.2-r0/rootfs/usr/share/man/man8/syslogd.8 to
/usr/share/man/man8/syslogd.8.inetutils since
.../0.2-r0/rootfs/usr/share/man/man8/syslogd.8 exists and is not a link

As has been done with the other packages which provide system logging
we add an rconflicts to only allow one to exist in a rootfs image at a
time.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>