src/poky:Revert "lttng-tools: Upgrade 2.13.4 -> 2.13.8"
Unfortunately this version upgrade results in failing ptests:

AssertionError: Failed ptests:
{'lttng-tools': ['kernel/test_callstack_11_-_Validate_userspace_callstack',
                 'kernel/test_userspace_probe_94_-_Enable_kernel_userspace_probe_event_for_session_test_userprobe_elf_cxx_function',
                 'kernel/test_userspace_probe_95_-_Start_tracing_for_session_test_userprobe_elf_cxx_function',
                 'kernel/test_userspace_probe_96_-_Stop_lttng_tracing_for_session_test_userprobe_elf_cxx_function',
                 'kernel/test_userspace_probe_97_-_Validate_trace_for_event_userspace_probe_test_event',
                 'kernel/test_userspace_probe_100_-_Enable_kernel_userspace_probe_event_for_session_test_userprobe_elf_cxx_method',
                 'kernel/test_userspace_probe_101_-_Start_tracing_for_session_test_userprobe_elf_cxx_method',
                 'kernel/test_userspace_probe_102_-_Stop_lttng_tracing_for_session_test_userprobe_elf_cxx_method',
                 'kernel/test_userspace_probe_103_-_Validate_trace_for_event_userspace_probe_test_event']}

This reverts commit 17d18936d201a61b16bbc24c9f10af6ef54620fc.

(cherry picked from commit 01cea6f046a6ec018c94ca88b6f8851c2baf43eb)
(From OE-Core rev: 82237927dbbf9ae19dd63622dd02beec3622575e)

Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>