src/meta-openembedded:msgraph: Add opengl to REQUIRED_DISTRO_FEATURES
Fixes the below yocto compliance issue:
  ERROR: Nothing PROVIDES 'rest' (but /build/layers/meta-openembedded/meta-gnome/recipes-gnome/msgraph/msgraph_0.2.1.bb DEPENDS on or otherwise requires it)
  rest was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'msgraph', 'rest']

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>