src/meta-openembedded:gthumb: fix implict dependency on gconf causing configure fail
Currently we see:

  | checking for gconftool-2... no
  | configure: error: gconftool-2 executable not found in your path - should be installed with GConf
  | ERROR: Function failed: do_configure (log file is located at gthumb/2.12.4-r4/temp/log.do_configure.5243)
  ERROR: Task (meta-gnome/recipes-gnome/gthumb/gthumb_2.12.4.bb:do_configure) failed with exit code '1'

Presumably this now happens more regularly with demise of the shared
sysroot.  Adding gconf-native to the dependency list fixes it.

Cc: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Paul Gortmaker <paul.gortmakerwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>