src/poky:toolchain-scripts.bbclass: add PYTHONHOME variable to environment-setup
When relocating the SDK, applications using python will search for
python modules in the default location and will fail to start.
The below errors are thrown by gdb, for example:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

In order to overcome this, add the PYTHONHOME variable to the
environment-setup script for both standalone toolchain and
adt-installer. No need to do that for meta-ide-support environment
script since this toolchain does not get relocated.

[YOCTO #3839]

(From OE-Core rev: e7a21cd69a326ab7e2d0e410db28f24956f61208)

Signed-off-by: Laurentiu Palcu <laurentiu.palcuintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>