src/meta-intel:libyami: update to latest SRCREV
Fixes errors with musl:

| ../../git/codecparsers/vp8_parser.cpp: In member function 'YamiParser::Vp8ParserResult YamiParser::Vp8Parser::ParseFrame(const uint8_t*, size_t, YamiParser::Vp8FrameHeader*)':
| ../../git/codecparsers/vp8_parser.cpp:98:32: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct YamiParser::Vp8FrameHeader'; use assignment or value-initialization instead [-Werror=class-memaccess]
|    memset(fhdr, 0, sizeof(*fhdr));
|                                 ^
| In file included from ../../git/codecparsers/vp8_parser.cpp:44:
| ../../git/codecparsers/vp8_parser.h:131:8: note: 'struct YamiParser::Vp8FrameHeader' declared here
|  struct Vp8FrameHeader {
|         ^~~~~~~~~~~~~~
| cc1plus: all warnings being treated as errors

Also, remove the upstreamed patch and change upstream checks to use git
commits instead.

Signed-off-by: Anuj Mittal <anuj.mittalintel.com>