src/meta-virtualization:lxc: fix compile failure on gcc10
Since oe-core is upgrading gcc to 10.1, there is
a compile failure
...
|../../../lxc-4.0.2/src/lxc/cgroups/cgfsng.c:2100:10: error: writing
1 byte into a region of size 0 [-Werror=stringop-overflow=]
| 2100 |   *slash = '\0';
...

Add gcc option `-Werror=stringop-overflow' to workaround the issue

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>