src/meta-openembedded:mariadb: clean the empty /lib dir
When usrmerge is enabled in DISTRO_FEATURES, there
comes below error:
ERROR: mariadb-10.4.12-r0 do_package_qa: QA Issue: mariadb-leftovers package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
ERROR: mariadb-10.4.12-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

It is because empty /lib dir exists in mariadb-leftovers
as below:
 $ rpm -qpl mariadb-leftovers-10.4.12-r0.core2_64.rpm |grep ^/lib
 /lib

Considering the empty /lib dir is introduced when pam
is enabled in DISTRO_FEATURES, so remove the empty /lib
dir when pam is enabled to fix the above error.

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>