src/meta-openembedded:nautilus3: upgrade to 3.2.1
* old version fails to build:
| In file included from eel-editable-label.c:30:0:
| eel-editable-label.h:112:1: error: unknown type name 'G_CONST_RETURN'
| eel-editable-label.h:112:21: error: expected '=', ',', ';', 'asm' or
'__attribute__' before '*' token
| eel-editable-label.c:684:1: error: unknown type name 'G_CONST_RETURN'
| eel-editable-label.c:684:22: error: expected '=', ',', ';', 'asm' or
'__attribute__' before '*' token
| eel-editable-label.c: In function
'eel_editable_label_accessible_get_character_count':

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>