src/meta-virtualization:libvirt: add dtrace pkgconfig option
If the host machine has dtrace, or systemtap development libraries
installed, libvirt will detect their headers and enable dtrace probe
support.

But since we don't have a dependency on dtrace, the build will fail
with:

  | compilation terminated.
  | In file included from ./internal.h:297:0,
  | from util/bitmap.h:27,
  | from util/bitmap.c:33:
  | ./libvirt_probes.h:9:21: fatal error: sys/sdt.h: No such file or directory

There are three problems:

  - a host contamination issue
  - dtrace/probes being automatically enabled
  - a lack of integrated systemtap/dtrace solution

Fixing any of the above will make the problem go away, to fix currently
broken builds, we can fix the problem by adding dtrace as a PACKAGECONFIG
option, and leaving it disabled. This change doesn't add a dtrace/systemtap
dependency to the config entry, since they haven't been confirmed at this
point.

In the future, we should either fix the host contamination or do a full
systemtap/dtrae integration, but for now, simply disabling it is the
best choice.

Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>