src/poky:oeqa rtc.py: skip if read-only-rootfs
hwclock command fails on read-only-rootfs:

AssertionError: 1 != 0 : Failed to reset RTC time, output: hwclock: cannot open /etc/adjtime: Read-only file system

(From OE-Core rev: b89abb0f4cc28c45a62c524a3e2f96795235e214)

Signed-off-by: Mikko Rapeli <mikko.rapelilinaro.org>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>
(cherry picked from commit 017bf8c160f6ab67d9f8e8d9e30b15bf84f73807)
Signed-off-by: Steve Sakoman <stevesakoman.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>