src/meta-openembedded:python-attrs: fix typo in depends
ERROR: Nothing RPROVIDES 'python-crypto' (but ../meta-python/recipes-devtools/python/python-attrs_17.4.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-crypto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-crypto']

Signed-off-by: Armin Kuster <akuster808gmail.com>