src/meta-openembedded:python3-ipython: Add missing dependency
This fixes the error:

Python 3.11.2 (main, Feb  7 2023, 13:52:42) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/IPython/__init__.py", line 52, in <module>
    from .core.application import Application
  File "/usr/lib/python3.11/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3.11/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3.11/site-packages/IPython/core/ultratb.py", line 101, in <module>
    import stack_data
ModuleNotFoundError: No module named 'stack_data'

Signed-off-by: Zoltán Böszörményi <zboszorgmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>