src/meta-security:parsec-service: fix SRC_URI hash
Fixes:
ERROR: Missing SRC_URI checksum, please add those to the recipe:
SRC_URI[parsec-service-1.2.0.sha256sum] = "f58e7ba859c22cc1904dc8298b1a7d94ee1ba3b4d4808f28e4cc0c96ddb149c9"

Needed to S dir too.

Signed-off-by: Armin Kuster <akuster808gmail.com>

v2]
Fix patch applying