src/meta-security:lib-perl: prefix man pages to avoid conflicting with base perl
The following occurs when pkgs-docs added to image features.

Error: Transaction test error:
  file /usr/share/man/man3/lib.3 conflicts between attempted installs of lib-perl-doc-0.63-r0.corei7_64 and perl-doc-5.34.1-r0.corei7_64

Signed-off-by: Jeremy A. Puhlman <jpuhlmanmvista.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>