src/poky:runqemu: don't complain about conflicting machines if they are equal
When the MACHINE variable was set as an environment variable, via
"export MACHINE=qemuarm" and runqemu was executed as "runqemu qemuarm"

The confusing error message appears:
Error: conflicting MACHINE types [qemuarm] and [qemuarm]

This checks if the two values are equal, in that case there is no problem
and execution can continue.

(From OE-Core rev: 6615a21d578ba9ab053ba0b3deab26ebf88e577b)

Signed-off-by: Pascal Bach <pascal.bachsiemens.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>