src/poky:pcmciautils: Inherit pkgconfig
Fixes
ERROR: pcmciautils-018-r1 do_package: QA Issue: pcmciautils: Files/directories were installed but not shipped in any package:
  /pcmcia-socket-startup
  /pcmcia-check-broken-cis
  /rules.d
  /rules.d/60-pcmcia.rules

Since we do not have pkg-config in native sysroot it is not
computing paths correctly and causes above error

(From OE-Core rev: 748b14caed95e7c0d45f1196398689a22975dcc9)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>