src/meta-openembedded:openocd: prevent fetching git submodules during do_configure
* I've tried just disabling them with:
  --disable-internal-jimtcl --disable-internal-libjaylink
  but that still tries to use missing jim.h:
  | ./src/helper/jim-nvp.h:47:10: fatal error: jim.h: No such file or directory
  |  #include <jim.h>
  |           ^~~~~~~
  | compilation terminated.
  | Makefile:3619: recipe for target 'src/libopenocd_la-openocd.lo' failed
  | make[2]: *** [src/libopenocd_la-openocd.lo] Error 1

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>