src/meta-security:tpm2.0-tss: fix systemd package list
Commit 4c4fa8c "tpm2.0-tss: install resourcemgr service" introduced
systemd support for the resourcemgr package, but left the default
${PN} in SYSTEMD_PACKAGES, leading to an apparently harmless (?) build
error, emitted by systemd.bbclass via bb.error() because tpm2.0-tss
does not have a package of that name:

ERROR: tpm2.0-tss-git-r0 do_package: tpm2.0-tss does not appear in package list, please add it

Signed-off-by: Patrick Ohly <patrick.ohlyintel.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>