src/poky:beecrypt: add patch for build issue on Fedora 17
../../x86_64-linux-libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../.. -I../../include  -isystem/intel/poky/builds/f17/tmp/sysroots/x86_64-linux/usr/include  -isystem/intel/poky/builds/f17/tmp/sysroots/x86_64-linux/usr/include -O2 -pipe -Wa,--noexecstack -c -o Properties.lo Properties.cxx
x86_64-linux-libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../include -isystem/intel/poky/builds/f17/tmp/sysroots/x86_64-linux/usr/include -isystem/intel/poky/builds/f17/tmp/sysroots/x86_64-linux/usr/include -O2 -pipe -Wa,--noexecstack -c Properties.cxx  -fPIC -DPIC -o .libs/Properties.o
In file included from ../../include/beecrypt/c++/util/Hashtable.h:42:0,
                 from ../../include/beecrypt/c++/util/Properties.h:36,
                 from Properties.cxx:25:
../../include/beecrypt/c++/util/AbstractSet.h: In instantiation of 'bool beecrypt::util::AbstractSet<E>::equals(const beecrypt::lang::Object*) const [with E = beecrypt::util::Map<beecrypt::lang::Object, beecrypt::lang::Object>::Entry]':
Properties.cxx:228:1:   required from here
../../include/beecrypt/c++/util/AbstractSet.h:59:27: error: 'containsAll' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
../../include/beecrypt/c++/util/AbstractSet.h:59:27: note: declarations in dependent base 'beecrypt::util::AbstractCollection<beecrypt::util::Map<beecrypt::lang::Object, beecrypt::lang::Object>::Entry>' are not found by unqualified lookup
../../include/beecrypt/c++/util/AbstractSet.h:59:27: note: use 'this->containsAll' instead
../../include/beecrypt/c++/util/AbstractSet.h: In instantiation of 'bool beecrypt::util::AbstractSet<E>::equals(const beecrypt::lang::Object*) const [with E = beecrypt::lang::Object]':
Properties.cxx:228:1:   required from here
../../include/beecrypt/c++/util/AbstractSet.h:59:27: error: 'containsAll' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
../../include/beecrypt/c++/util/AbstractSet.h:59:27: note: declarations in dependent base 'beecrypt::util::AbstractCollection<beecrypt::lang::Object>' are not found by unqualified lookup
../../include/beecrypt/c++/util/AbstractSet.h:59:27: note: use 'this->containsAll' instead

[YOCTO #2593]

(From OE-Core rev: 93aa773c4c03c21a70d7d53cf93e43416e17007c)

Signed-off-by: Saul Wold <sgwlinux.intel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>