src/meta-virtualization:openvswitch: uprev from v2.12 to v2.13
Another straightforward uprev with one fairly large change in the
changelog. The Open Virtual Network component has now been moved to
its own repo (https://github.com/ovn-org/ovn.git). If you were using
this functionality a new recipe will need to be created.

The ptest results are similar to after the v2.12 uprev

    ERROR: 2206 tests were run,
    28 failed unexpectedly.
    62 tests were skipped.

The failed tests were in the following areas:
    checkpatch.at (5)
    ovs-ofctl.at (1)
    tunnel.at(1)
    tunnel-push-pop.at(3)
    tunnel-push-pop-ipv6.at(3)
    dpif-netdev.at (1)
    pmd.at(1)
    ofproto-dpif.at (7)
    bridge.at (2)
    ovsdb-idl.at(1)
    mcast-snooping.at(1)
    packet-type-aware.at(2)

None of these affect core functionality or usecases and are similar to
the results we see with v1.12. If specific usecases are affected by
these failures we should address them on a need to fix basis.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>