src/poky:oeqa/selftest/gcc: Fix kex exchange identification error
while runnig oe-selftest for gcc, some of the testcases that need to be run on qemu
are not running due to below failures:
- kex_exchange_identification: read: Connection reset by peer^M
   Connection reset by 192.168.7.2 port 22^M
   ERROR: Couldn't create remote directory /tmp/runtest.3549814 on ssh

To resolve kex exchange identification error increased the MaxStartups.

(From OE-Core rev: df64d5ab6eb37dcdc2046f449ec539a3f4b985c8)

Signed-off-by: Harish Sadineni <Harish.Sadineniwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>