src/meta-openembedded:Revert "systemd.bbclass: Dont check for multilib and change for nativesdk renaming"
This triggers:

ERROR: Nothing RPROVIDES 'connman-systemd' (but /OE/tentacle/sources/meta-angstrom/recipes-images/angstrom/systemd-image.bb RDEPENDS on or otherwise requires it)

This reverts commit cbac8756e815c3f141cebf6d2e6875400980a4f9.