src/poky:tcl: correct the header location in tcl.pc
The patch alter-includedir.patch previouly install the header
to /usr/include/tcl8.6, but it doesn't reflect in tcl.pc and
the header location still /usr/include in tcl.pc and result
in the below configure failure for other packages such as
python3 which depends on tcl and uses pkg-config to detect tcl.

| conftest.c:161:16: fatal error: tcl.h: No such file or directory
  161 |       #include <tcl.h>

So update alter-includedir.patch to correct the header location
in tcl.pc to keep consistency.

(From OE-Core rev: ff156411380640f99ddb058ed8da0626d3183954)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>