src/meta-openembedded:libjxl: Disable sizeless-vectors on riscv32
They endup in undefined intrinsics demanded by compiler

error: use of undeclared identifier '__riscv_vsetvlmax_e8mf8'

Perhaps an upgrade of vendored highway module ( when it happens)
will fix it

Signed-off-by: Khem Raj <raj.khemgmail.com>