src/poky:qemu_git.bb: remove it
Remove it since we have 2.4.0, the git version is 1.3 can't be built by
deafult:
ERROR: Fetcher failure: Unable to find revision 04024dea2674861fcf13582a77b58130c67fccd8 in branch master even from upstream

We can fix it, but seems that no one uses it any more.

And move patches from "files" dir to "qemu" dir.

(From OE-Core rev: d3c3d62cfb2eeb224fa021af9cd550edf826445e)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>