src/poky:python3: Fix python-distutils variables
python-distutils uses the information from this file for setting the
system variables.

Whithout this patch:

rootqt5022:~# pip install pyzmq

...

x86_64-poky-linux-gcc -m64 -march=btver1 -mtune=btver1
--sysroot=/var/lib/jenkins/jobs/qt5022-cesium/workspace/build/tmp/sysroots/qt5022
-fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types
-DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -DNATIVE_LITTLE_ENDIAN=1
-Ibundled/libsodium/src/libsodium/include
-Ibundled/libsodium/src/libsodium/include/sodium
-I/usr/include/python2.7 -c buildutils/initlibsodium.c -o
build/temp.linux-x86_64-2.7/buildutils/initlibsodium.o
    In file included from /usr/include/python2.7/Python.h:8:0,
                         from buildutils/initlibsodium.c:10:
    /usr/include/python2.7/pyconfig.h:24:27: fatal error: bits/wordsize.h: No such
file or directory
    #include <bits/wordsize.h>
rootqt5022:~# ls /usr/include/bits/wordsize.h
/usr/include/bits/wordsize.h

(From OE-Core rev: 6b918dc24d4ab6dcc3693f7f8a8653535edb58c0)

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribaldagmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>