src/meta-openembedded:postfix: add sendmail to ALTERNATIVE_${PN}
There are several packages provide ${sbindir}/sendmail
and should add sendmail to ALTERNATIVE_${PN}
to make it work well.

And the sendmail is removed from ALTERNATIVE_${PN}
in below commit:

===
commit 7b500488115c67d657312135b48027a1c26e0955
Author: Lei Maohui <leimaohuicn.fujitsu.com>
Date:   Fri Aug 17 18:19:53 2018 -0700

    postfix,esmtp: Fix confilct error in do_rootfs

    Error: Transaction check error:
      file /usr/bin/mailq conflicts between attempted installs of esmtp-1.2-r0.x86_64 and postfix-3.2.2-r0.x86_64
      file /usr/bin/newaliases conflicts between attempted installs of esmtp-1.2-r0.x86_64 and postfix-3.2.2-r0.x86_64

    Signed-off-by: Lei Maohui <leimaohuicn.fujitsu.com>
    Signed-off-by: Khem Raj <raj.khemgmail.com>
===

Add it back to make sendmail works normally

before adding it back:
 # mime-construct --to root --subject mail-20826 --encoding 7bit --string mail_content

 sendmail: account default not found: no configuration file available
 Error closing sendmail: non-zero exit (78) at /usr/bin/mime-construct line 572.
 # echo $?
 78

After adding it back:
 # mime-construct --to root --subject mail-20826 --encoding 7bit --string mail_content
 # echo $?
 0

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>