src/meta-virtualization:virtiofsd: add seccomp to REQUIRED_DISTRO_FEATURES
* otherwise causes world build failures for DISTROs without seccomp:

  ERROR: Nothing PROVIDES 'libseccomp' (but meta-virtualization/recipes-extended/virtiofsd/virtiofsd_1.7.0.bb DEPENDS on or otherwise requires it)
  libseccomp was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>