src/meta-openembedded:android-tools: fix compilation because of include path poisoning
The android-tools's build in several places adds system locations (like
/usr/include/android) to the include path. Extend the OE-specific build
patch to fix those errors.

This fixes errors like:

error: include location "/usr/include/android" is unsafe for cross-compilation.

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkovlinaro.org>
Signed-off-by: Khem Raj <raj.khemgmail.com>