src/poky:opensbi: append LDFLAGS to TARGET_CC_ARCH
To solve the following GNU_HASH error:
ERROR: opensbi-1.4-r0 do_package_qa: QA Issue: File /share/opensbi/lp64/generic/firmware/fw_dynamic.elf in package opensbi doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /share/opensbi/lp64/generic/firmware/fw_payload.elf in package opensbi doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /share/opensbi/lp64/generic/firmware/fw_jump.elf in package opensbi doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

[YOCTO #15370] -- https://bugzilla.yoctoproject.org/show_bug.cgi?id=15370

(From OE-Core rev: b82e1e99feb8b0d70ff4c4bcac67336d562d2e53)

Signed-off-by: Thomas Perrot <thomas.perrotbootlin.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>