src/poky:lttng-tools: Allow reconnect to relayd
If relayd is started after connection attempt from consumerd it will
leave the session in disconnected state and causes the following
inconvenience. This is covered by an upstream feature, see
https://bugs.lttng.org/issues/883. Before it's done, this patches
allows users to reconnect to relayd.

rootlocalhost:~# lttng enable-event --userspace --all
Error: Events: UST create channel failed (channel channel0, session trace_session)
rootlocalhost:~# lttng-relayd -b
Warning: No tracing group detected
rootlocalhost:~# lttng enable-event --userspace --all
Error: Events: UST create channel failed (channel channel0, session trace_session)

(From OE-Core rev: 6f0079a6c3cc8926423cff3a927a78dcecede90d)

Signed-off-by: He Zhe <zhe.hewindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>