src/poky:libtool: Extend fix-final-rpath.patch
When building upower from meta-oe, the following QA error occurred:
ERROR: QA Issue: package upower contains bad RPATH

It appears to have been caused by one of the cases fix-final-rpath.patch
is meant to address but missed. So this change fixes the additional case
that was causing upower to have the QA error.

(From OE-Core rev: d2b2bb7cedb678c9f67ef1d9170fc427d9beee1e)

Signed-off-by: Randy Witt <randy.e.wittlinux.intel.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>