src/meta-openembedded:ufw: Fix packaging errors found with ppc64
default baselib in ppc64 is lib64 which catches this latent issue

ERROR: ufw-0.36.1-r0 do_package: QA Issue: ufw: Files/directories were installed but not shipped in any package:
  /usr/lib/ufw
  /usr/lib/ufw/ufw-init
  /usr/lib/ufw/ufw-init-functions

Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit 42e6f16583e36857152ccb53b177e74f20b02667)
Signed-off-by: Armin Kuster <akuster808gmail.com>