src/meta-openembedded:networkmanager: Fix many typos in DISTRO_FEATURES PACKAGECONFIG decodes
fixes issues found with yocto-check-layer

 File "/home/akuster/oss/maint/openembedded-core/bitbake/lib/bb/data_smart.py", line 436, in DataSmart.expand(s="nss ifupdown netconfig dhclient dnsmasq     ${bb.utils.contains('DISTRO_FEATURES', 'systemd', 'systemd', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'x11', 'consolekit', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'bluetooth', '${BLUEZ}', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'wifi', '', d)} ", varname='PACKAGECONFIG'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value

  File "/home/akuster/oss/maint/openembedded-core/bitbake/lib/bb/data_smart.py", line 426, in DataSmart.expandWithRefs(s="nss ifupdown netconfig dhclient dnsmasq     ${bb.utils.contains('DISTRO_FEATURES', 'systemd', 'systemd', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'x11', 'consolekit', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'bluetooth', 'bluez5', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'wifi', '', d)} ", varname='PACKAGECONFIG'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc

bb.data_smart.ExpansionError: Failure expanding variable PACKAGECONFIG, expression was nss ifupdown netconfig dhclient dnsmasq     ${bb.utils.contains('DISTRO_FEATURES', 'systemd', 'systemd', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'x11', 'consolekit', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'bluetooth', 'bluez5', '', d)}     ${bb.utils.contains('DISTRO_FEATURES', 'wifi', '', d)}  which triggered exception TypeError: contains() missing 1 required positional argument: 'd'

Signed-off-by: Armin Kuster <akuster808gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonaldmentor.com>