src/meta-raspberrypi:packagegroup-rpi-test: include bigbuckbunny in RRECOMMENDS_${PN} only with meta-multimedia
* resolves:
  ERROR: Nothing RPROVIDES 'bigbuckbunny-480p' (but meta-raspberrypi/recipes-core/packagegroups/packagegroup-rpi-test.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'bigbuckbunny-480p' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['bigbuckbunny-480p']
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-rpi-test', 'bigbuckbunny-480p']

  when building without meta-multimedia layer included

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>