src/meta-openembedded:turbostat: Fix build failure for missing kernel internal heaers and clean up
To fix the following build failures
turbostat.c:(.text+0xc28a): undefined reference to `UL'
turbostat.c:33:10: fatal error: sys/capability.h: No such file or directory (for kernel v5.6-rc7)

- Add dependency on libcap for kernel v5.6-rc7 and later versions
- Copy internal linux/const.h used by previously added internal linux/bits.h
- Tweak linux/const.h to allow it to refer to uapi const.h, as
  linux-libc-headers purposely removes _UAPI from the locker macros of the
  headers
- Remove -I for kernel-source in EXTRA_OEMAKE, as linux-kernel-headers has
  provided enough and necessary headers
- Make do_configure depend on kernel's do_shared_workdir

Signed-off-by: He Zhe <zhe.hewindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>