src/meta-openembedded:log4cpp: Keep using std=c++14
It still needs auto_ptr which is pre c++17

| ../../log4cpp/include/log4cpp/BufferingAppender.hh:21:81: error: no template named 'auto_ptr' in namespace 'std'

Signed-off-by: Khem Raj <raj.khemgmail.com>