src/meta-cloud-services:openstackchef: add missing parameter to getVar
Builds are failing with:

File: 'openstackchef_inc.bbclass', lineno: 624, function: deploychef_add_file_to_FILES_PN
0620:    pkg_files = "FILES_%s" %  pkg
0621:    ldata.setVar("OVERRIDES", "%s:%s" % (pkg_files, overrides))
0622:    bb.data.update_data(ldata)
0623:
*** 0624:    dest_base = d.getVar('CHEF_TEMPLATE_BASE')
0625:    pkg_imagedir = d.getVar('CHEF_ROOTFS_BASE', True)
0626:    #Add the packages image base directory if it does not already exist
0627:    if re.search(pkg_imagedir, files) == None:
0628:        #All the directory and all files in it
Exception: TypeError: getVar() takes at least 3 arguments (2 given)

Add the required parameter to fix the build. Chef is planned to be
removed from this layer in the near future, so this change is not
tested.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>