src/meta-security:sssd: fix missing python3-logging run-time dependency
The internal tool sss_analyze is a python script run by the sssctl
command analyze.

The script sss_analyze imports the python module logging[1].

However, the package sssd lacks installing this python module that is
required to run the script.

This adds the missing run-time dependency python3-logging to ensure this
module comes along the package sssd.

Fixes:

	rootqemux86-64:~# sssctl analyze
	Traceback (most recent call last):
	  File "/usr/libexec/sssd/sss_analyze", line 3, in <module>
	    from sssd import sss_analyze
	  File "/usr/lib/python3.12/site-packages/sssd/sss_analyze.py", line 3, in <module>
	    from sssd.modules import request
	  File "/usr/lib/python3.12/site-packages/sssd/modules/request.py", line 2, in <module>
	    import logging
	ModuleNotFoundError: No module named 'logging'

[1]: https://github.com/SSSD/sssd/blob/2.9.2/src/tools/analyzer/source_files.py#L2

Signed-off-by: Gaël PORTAY <gael.portay+rtonegmail.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>