src/meta-openembedded:python3-pid: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import pid
 [snip]
ModuleNotFoundError: No module named 'fcntl'
ModuleNotFoundError: No module named 'logging'
ModuleNotFoundError: No module named 'tempfile'

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>