src/meta-openembedded:python3-matplotlib-inline: update 0.1.6 → 0.1.7 plus fixes
Update to the latest upstream released version.

Add a PYPI_PACKAGE entry to the recipe. Otherwise, during final image
assembly, an error similar to the following would occur due to the fact
the yocto package name (which includes dashes) differs from the download
filename (which includes underscores). NOTE: this would happen with all
package types, not just ipk:

	ERROR: core-image-base-1.0-r0 do_rootfs: Unable to install packages. Command '/scratch/trevor/oe/builds/jupyter/jupyter-rockchip/scarthgap/build/tmp-glibc/work/rock_5a-oe-linux/core-image-base/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /scratch/trevor/oe/builds/jupyter/jupyter-rockchip/scarthgap/build/tmp-glibc/work/rock_5a-oe-linux/core-image-base/1.0/opkg.conf -t /scratch/trevor/oe/builds/jupyter/jupyter-rockchip/scarthgap/build/tmp-glibc/work/rock_5a-oe-linux/core-image-base/1.0/temp/ipktemp/ -o /scratch/trevor/oe/builds/jupyter/jupyter-rockchip/scarthgap/build/tmp-glibc/work/rock_5a-oe-linux/core-image-base/1.0/rootfs --force_postinstall --prefer-arch-to-version  <package list including python3-matplotlib-inline...> returned 255:
	* opkg_solver_install: No candidates to install python3-matplotlib-inline (null)!

Add additional devtool-discovered information:
- update the build mechanism to include python_setuptools_build_meta
- add the RDEPENDS

Signed-off-by: Trevor Woerner <twoernergmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>