src/meta-cgl:resource-agents: Fix error when do_patch
To fix conflict when do_patch:
ERROR: resource-agents-4.5.0-r0 do_patch: QA Issue: Fuzz detected:

Applying patch autoconf-2.73.patch
patching file configure.ac
Hunk #1 succeeded at 883 with fuzz 2.

Signed-off-by: Wang Mingyu <wangmyfujitsu.com>