src/meta-openembedded:poco: Link with libatomic on riscv32
It does not have compiler intrinsics for 64bit atomics
Fixes
 MetricsSample.cpp:(.text._ZN16MetricsSampleApp4mainERKNSt3__16vectorINS0_12basic_stringIcNS0_11char_t
raitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEE[_ZN16MetricsSampleApp4mainERKNSt3__16vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEE]+0x104): undefined reference to `__atomic_compare_exchange_8'

Signed-off-by: Khem Raj <raj.khemgmail.com>