src/meta-openembedded:gnome-themes-extra: fix datadir path
This fixes do_rootfs error if gtk2 is installed

Running transaction test
Error: Transaction test error:
  file /usr conflicts between attempted installs of gnome-theme-adwaita-3.28-r0.corei7_64 and pipewire-modules-zeroconf-discover-0.3.77-r0.corei7_64
  file /usr/lib conflicts between attempted installs of gnome-theme-adwaita-3.28-r0.corei7_64 and pipewire-modules-zeroconf-discover-0.3.77-r0.corei7_64
  file /usr/lib/gtk-2.0 conflicts between attempted installs of gnome-theme-adwaita-3.28-r0.corei7_64 and at-spi2-core-2.48.3-r0.corei7_64
  file /usr/share conflicts between attempted installs of gnome-theme-adwaita-3.28-r0.corei7_64 and ghostscript-10.01.2-r0.corei7_64
  file /usr conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/lib conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/lib/gtk-2.0 conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/lib/gtk-2.0/2.10.0 conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/lib/gtk-2.0/2.10.0/engines conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/share conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64
  file /usr/share/themes conflicts between attempted installs of libgtk-2.0-2.24.33-r0.corei7_64 and gnome-theme-adwaita-3.28-r0.corei7_64

Signed-off-by: Markus Volk <f_l_kt-online.de>
Signed-off-by: Khem Raj <raj.khemgmail.com>