src/poky:documentation: add rpcgen tool to required packages
On recent distros the following error appears without rpcgen host tool:
  ERROR: The following required tools (as specified by HOSTTOOLS)
  appear to be unavailable in PATH, please install them in order to
  proceed:
    rpcgen

(From yocto-docs rev: 66a491e77e1b97a831515d4ac8e0245540d7242a)

Signed-off-by: Goran Cengic <cengicgmail.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>