src/poky:lttng-modules: update to 2.4.1-stable latest
The 3.15, and 3.14.5+ kernels introduced a change to trace_block_rq_complete,
which triggers the following build error:

    probes/../instrumentation/events/lttng-module/../../../probes/lttng-events.h:151:6:
    error: conflicting types for 'trace_block_rq_complete'
    |  void trace_##_name(_proto);
    |       ^
    |
    probes/../instrumentation/events/lttng-module/../../../probes/lttng-events.h:117:2:
    note: in expansion of macro 'DEFINE_EVENT_MAP'
    |   DEFINE_EVENT_MAP(template, name, name, PARAMS(proto), PARAMS(args))
    |   ^
    |
    probes/../instrumentation/events/lttng-module/../../../probes/../instrumentation/events/lttng-module/block.h:235:1:
    note: in expansion of macro 'DEFINE_EVENT'
    |  DEFINE_EVENT(block_rq_with_error, block_rq_complete,

The lttng 2.4.x-stable branch contains the fix (and several other small fixes), so
we bump the SRCREV to import the change.

Build tested against 3.14 and 3.10.

[YOCTO #6459]

(From OE-Core rev: bb304f306c0f6ee496a75a67c0bb8a6c1e41ddf2)

Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>