src/poky:gpgme: remove local m4/python.m4
While multilib, the local m4/python.m4 incorrectly assigned
am_cv_python_pyexecdir and am_cv_python_pythondir which caused
the following error enabled:
...
ERROR: gpgme-1.9.0-r0 do_package: QA Issue: gpgme: Files/directories
were installed but not shipped in any package:
  /usr/lib/python3.5/site-packages/gpg-1.9.0-py3.5.egg-info
...

(From OE-Core rev: f5c7e236582028638a26a5855d5e7ba0b55bb8f0)

Signed-off-by: Hongxu Jia <hongxu.jiawindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>