src/poky:bitbake: BBHandler: Fix __python_func_regexp__ for comment lines
Fixed:
- Add a comment in base.bbclass:
  def oe_import(d):
      import sys
  # Comment
      bbpath = d.getVar("BBPATH").split(":")
  [snip]

  Note, '# Comment' is started with '#', it is legal in python's syntax
  (though maybe not a good style), but bitbake reported errors:

  $ bitbake -p
  ERROR: ParseError at /path/to/base.bbclass:20: unparsed line: '    bbpath = d.getVar("BBPATH").split(":")'

  This error report would mislead people, the real problem is that '# Comment'
  is not supported, but it reports the next line, this may make it hard to debug
  the code are complicated.

We can make __python_func_regexp__ handle '^#' to fix the problem, since it
already can handle blank line "^$" in a python function, so it would be pretty
safe to handle "^#" as well.

(Bitbake rev: 79e62eef1c93f742bf71e9f25db57fdd2ffedd02)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>