src/meta-openembedded:wtmpdb: fix installed-vs-shipped build error
wtmpdb installs a PAM plugin in "${base_libdir}/security/pam_wtmpdb.so".
This path is not in default FILES.

Add this path to FILES:${PN} to fix this error:
  ERROR: wtmpdb-0.11.0-r0 do_package: QA Issue: wtmpdb: Files/directories were installed but not shipped in any package:
    /lib/security/pam_wtmpdb.so
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  wtmpdb: 1 installed and not shipped files. [installed-vs-shipped]
  ERROR: wtmpdb-0.11.0-r0 do_package: Fatal QA errors were found, failing task.
  ERROR: Logfile of failure stored in: .../poky/build-master/tmp/work/core2-64-poky-linux/wtmpdb/0.11.0/temp/log.do_package.939726
  ERROR: Task (.../poky/meta-openembedded/meta-oe/recipes-extended/wtmpdb/wtmpdb_0.11.0.bb:do_package) failed with exit code '1'

Signed-off-by: Yoann Congal <yoann.congalsmile.fr>
Signed-off-by: Khem Raj <raj.khemgmail.com>
(cherry picked from commit a090cd3e0ef554d7171eb84488661599d72fa3e9)
Signed-off-by: Armin Kuster <akuster808gmail.com>