src/poky:psplash: Turn psplash_fb_plot_pixel() into static inline
This function is not used anywhere except psplash-fb.c so make it static
inline function which is portable across compilers

Fixes issues like
psplash-fb.o: In function `psplash_fb_draw_rect':
|
/mnt/home/kraj/work/angstrom/sources/openembedded-core/build/tmp-glibc/work/i586-oe-linux/psplash/0.1+gitAUTOINC+14c8f7b705-r15/git/psplash-fb.c:363:
undefined reference to `psplash_fb_plot_pixel'

(From OE-Core rev: 2429932c2dc1f81bf04f4377911094e2c8a04a19)

(From OE-Core rev: 443f9efa457ab57be8f79bccec8250678d4065c5)

Signed-off-by: Khem Raj <raj.khemgmail.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>