src/meta-openembedded:collectd: build with rrdcached plugin
rrdcached package is provided by rrdtool recipe. The build dependency in PACKAGECONFIG is changed to rrdtool.
    The error was:
     Nothing PROVIDES 'rrdcached' but ../collectd_5.12.0.bb DEPENDS on or otherwise requires it). Close matches:
      rrdtool RPROVIDES rrdcached
    ERROR: Required build target 'collectd' has no buildable providers.
    Missing or unbuildable dependency chain was: ['collectd', 'rrdcached']

    With the patch, collectd builds with no errors and the final image I tested includes collectd with rrdcached plugin.
    Tested on custom image with collectd_5.12.0.

Signed-off-by: Βούλγαρη Αικατερίνη <aikaterini.voulgarisoftcom-int.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>