src/meta-openembedded:gpsd: Correct the creation of the gps-utils-python package
The gps-utils-python package was introduced in commit 66721940 (gpsd:
split python utils from gps-utils), except it was never added to
PACKAGES, which resulted in the following error if anything depends on
gpsd:

  ERROR: Nothing RPROVIDES 'gps-utils-python' (but .../gpsd_3.23.1.bb
  RDEPENDS on or otherwise requires it)

Also remove a no longer relevant comment.

Signed-off-by: Peter Kjellerstedt <peter.kjellerstedtaxis.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>