src/meta-virtualization:libvirt-glib: update 4.0.0 -> 5.0.0
5.0.0 - Nov 28, 2023
====================

- Fix compatiblity with libxml2 >= 2.12.0
- Bump min libvirt version to 2.3.0
- Bump min meson to 0.56.0
- Require use of GCC >= 4.8 / CLang > 3.4 / XCode CLang > 5.1
- Mark USB disks as removable by default
- Add support for audio device backend config
- Add support for DBus graphics backend config
- Add support for controlling firmware feature flags
- Improve compiler flag handling in meson
- Extend library version script handling to FreeBSD
- Fix pointer sign issue in capabilities config API
- Fix compat with gnome.mkenums() in Meson 0.60.0
- Avoid compiler warnings from gi-ir-scanner generated
  code by not setting glib version constraints
- Be more robust about NULL GError parameters
- Disable unimportant cast alignment compiler warnings
- Use 'pragma once' in all header files
- Updated translations

This fixes build after libxml update:
../git/libvirt-gconfig/libvirt-gconfig-object.c:200:37: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Werror=incompatible-pointer-types]
  200 |     xmlSetStructuredErrorFunc(NULL, gvir_xml_structured_error_nop);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /home/flk/poky/build/tmp/work/corei7-64-poky-linux/libvirt-glib/4.0.0/recipe-sysroot/usr/include/libxml2/libxml/relaxng.h:14,

Signed-off-by: Markus Volk <f_l_kt-online.de>
Signed-off-by: Bruce Ashfield <bruce.ashfieldgmail.com>