src/meta-openembedded:gparted: add to deps instead of overwriting
Thsi recipe inherits gtk-icon-cache which adds hicolor-icon-theme to
dependencies conditionally, this however gets lost if the DEPENDS is
using = instead of +=

Fixes

ERROR: QA Issue: gparted rdepends on hicolor-icon-theme, but it isn't a build dependency, missing hicolor-icon-theme in DEPENDS or PACKAGECONFIG? [build-deps]

Signed-off-by: Khem Raj <raj.khemgmail.com>