src/poky:python3-docutils: fix interpreter lines
when compiling a non native variant, latest update
introduced package-qa errors like

ERROR: QA Issue: .../docutils/utils/smartquotes.py contained in package
nativesdk-python3-docutils requires /usr/bin/python3, but no providers
found in RDEPENDS:nativesdk-python3-docutils? [file-rdeps]

Fix that by patching the interpreter lines after install

(From OE-Core rev: f0037d2b2a4b72f279f3fe60c82d4b4044cbc6d5)

Signed-off-by: Konrad Weihmann <kweihmannoutlook.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>