src/meta-cloud-services:python-oauthlib: allow apache to read requires.txt
Apache will error with:

IOError: [Errno 13] Permission denied: \
'/usr/lib/python2.7/site-packages/oauthlib-0.7.2-py2.7.egg-info/requires.txt'

when attempting to login to horizon. Set more permissive permissions
for this file to avoid this.

Signed-off-by: Mark Asselstine <mark.asselstinewindriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfieldwindriver.com>