src/meta-openembedded:README: mention linux-libc-dev:i386 for luajit on ubuntu-21.10
* for host* parts you need to install linux-libc-dev:i386 on ubuntu-21.10
  (not pulled by gcc-multilib already mentioned in meta-oe/README), otherwise
  build for 32bit target will fail like this:

  cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/luajit/2.1.0~beta3-210112-r0/git/src$ gcc  -m32   -Wall   -I. -DLUAJIT_TARGET=LUAJIT_ARCH_arm -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0 -isystem/OE/build/oe-core/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/luajit/2.1.0~beta3-210112-r0/recipe-sysroot-native/usr/include -O2 -pipe -c -o host/minilua.o host/minilua.c
  In file included from /usr/include/bits/errno.h:26,
                   from /usr/include/errno.h:28,
                   from host/minilua.c:40:
  /usr/include/linux/errno.h:1:10: fatal error: asm/errno.h: No such file or directory
      1 | #include <asm/errno.h>
        |          ^~~~~~~~~~~~~
  compilation terminated.

  while for 64bit taget it would build without -m32 and work fine without linux-libc-dev:i386:

  cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/luajit/2.1.0~beta3-210112-r0/git/src$ gcc    -Wall   -I. -DLUAJIT_TARGET=LUAJIT_ARCH_arm -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0 -isystem/OE/build/oe-core/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/luajit/2.1.0~beta3-210112-r0/recipe-sysroot-native/usr/include -O2 -pipe -c -o host/minilua.o host/minilua.c
  <OK>

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>