src/meta-openembedded:bash-completion: resolve sysroot conflicts for util-linux and networkmanager
* continue the priority for packages shipping bash-completion
* oe-core's latest changes turn sysroot conflicts into critical error

ERROR: The recipe bash-completion is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
   /home/a.mueller/tmp/oe-core-glibc/sysroots/overo/usr/share/bash-completion/completions/nmcli
   Matched in manifest-overo-networkmanager.populate_sysroot
   /home/a.mueller/tmp/oe-core-glibc/sysroots/overo/usr/share/bash-completion/completions/su
   Matched in manifest-overo-util-linux.populate_sysroot

Signed-off-by: Andreas Müller <schnitzeltonygooglemail.com>