src/poky:image-live.bbclass: respect IMAGE_MACHINE_SUFFIX
* fixes:
  ERROR: core-image-minimal-1.0-r0 do_bootimg: /OE/build/poky/build/tmp/deploy/images/qemux86-64/core-image-minimal-initramfs-qemux86-64.cpio.gz is invalid. initrd image creation failed.
  ERROR: core-image-minimal-1.0-r0 do_bootimg: ExecutionError('/OE/build/poky/build/tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0-r0/temp/run.build_hddimg.2001892', 1, None, None)
  when IMAGE_MACHINE_SUFFIX is set to empty in local.conf

(From OE-Core rev: ac1977fea5a5d68c197d948a59447472e7c7747b)

Signed-off-by: Martin Jansa <Martin.Jansagmail.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
(cherry picked from commit ed072d2a0abe5a22330160f67ee5e83c2eae1dac)
Signed-off-by: Steve Sakoman <stevesakoman.com>