src/poky:binutils: update SRCREV to fix powerpc gold link bug
Update to the latest commit on the 2.28 branch to pick up:
   a3e00a8 [GOLD] Avoid duplicate PLT stub symbols on ppc32
along with several backported bug fixes for arm*, etc.

This resolves the systemd link error for qemuppc
with the error message:
   .../powerpc-oe-linux-ld.gold:
   error: invalid STB_LOCAL symbol in external symbols
   error: linker defined: multiple definition of '00000001.plt_call.memcpy+8000'
   command line: previous definition here

described in:

[YOCTO #11696]

(From OE-Core rev: 0d1273cdf8652bf1844f1f1fe4ba0eacd27ada65)

Signed-off-by: Randy MacLeod <Randy.MacLeodwindriver.com>
Signed-off-by: Ross Burton <ross.burtonintel.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>