src/meta-openembedded:devilspie2: Add missing dependency on libxinerama
Fixes
| src/xutils.c:29:10: fatal error: 'X11/extensions/Xinerama.h' file not found
| #include <X11/extensions/Xinerama.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
| 1 error generated.

Signed-off-by: Khem Raj <raj.khemgmail.com>