src/poky:strace: Bump to version 4.25
V4L2_CID_USER_IMX_BASE value differs in v4.14 and v4.19 LTS kernels
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/linux/v4l2-controls.h?h=v4.14.79#n191
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/linux/v4l2-controls.h?h=v4.19.1#n191

Building strace v4.24 against 4.19 kernel headers results in following
build failure

  | arm-vaisala-linux-gnueabi-ranlib libstrace.a
  | In file included from ../strace-4.24/static_assert.h:31,
  |                  from ../strace-4.24/xlat/v4l2_pix_fmts.h:4,
  |                  from ../strace-4.24/v4l2.c:78:
  | ../strace-4.24/xlat/v4l2_control_id_bases.h:36:1: error: static assertion failed: "V4L2_CID_USER_IMX_BASE != (V4L2_CID_BASE + 0x1090)"

This Linux kernel ABI breakage that occurred wrt V4L2_CID_USER_IMX_BASE
has been observed and addressed in strace upstream commit
https://github.com/strace/strace/commit/b89a69dec27cf638df0e17db80ed937c3e1abf77

Bump strace to version 4.25 which also addresses ABI breakage so that
strace once again builds against both v4.14 and v4.19 LTS kernel headers

(From OE-Core rev: facb6e2fd887d526e031b6c16b4bb8d385db952a)

Signed-off-by: Niko Mauno <niko.maunovaisala.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>