src/meta-openembedded:esmtp: add sendmail to ALTERNATIVE_${PN}
There are several packages provide ${sbindir}/sendmail
and should add sendmail to ALTERNATIVE_${PN}
to make it work well.

And the sendmail is removed from ALTERNATIVE_${PN}
in below commit:

===
commit 7b500488115c67d657312135b48027a1c26e0955
Author: Lei Maohui <leimaohuicn.fujitsu.com>
Date:   Fri Aug 17 18:19:53 2018 -0700

  postfix,esmtp: Fix confilct error in do_rootfs

  Error: Transaction check error:
  file /usr/bin/mailq conflicts between attempted installs of esmtp-1.2-r0.x86_64 and postfix-3.2.2-r0.x86_64
  file /usr/bin/newaliases conflicts between attempted installs of esmtp-1.2-r0.x86_64 and postfix-3.2.2-r0.x86_64

  Signed-off-by: Lei Maohui <leimaohuicn.fujitsu.com>
  Signed-off-by: Khem Raj <raj.khemgmail.com>
===

Add it back to make sendmail works normally

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>