src/meta-openembedded:rrdtool: fix useless-rpath QA issue
When building rrdtool, we would meet the following error.

  ERROR: QA Issue: rrdtool-python: work/core2-64-poky-linux/rrdtool
  /1.5.4-r0/packages-split/rrdtool-python/usr/lib/python2.7/site-packages
  /rrdtool.so contains probably-redundant RPATH /usr/lib [useless-rpaths]

Fix this issue by removing 'LD_RUN_PATH=$(libdir)' when compiling rrdtool.so.

As we use '--disable-rpath' in EXTRA_OECONF, we don't need to the to remove
'--rpath=$(libdir)' in Makefile.am.

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>