src/meta-openembedded:renderdoc: add x11 to REQUIRED_DISTRO_FEATURES
This recipe depends on having x11 enabled so we add it to fix:

ERROR: Nothing PROVIDES 'libxcb' (but
meta-oe/meta-oe/recipes-graphics/renderdoc/renderdoc_1.4.bb
DEPENDS on or otherwise requires it)
libxcb was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Signed-off-by: Adrian Ratiu <adrian.ratiucollabora.com>
Signed-off-by: Khem Raj <raj.khemgmail.com>