src/meta-cgl:pacemaker: rework 0002-pacemaker-search-header-from-STAGING_INCDIR-to-walka.patch
* Rework the patch as the logic is wrong previously
  as the STAGING_INCDIR is actually applicable in
  cross compiling env.

  Update the patch to locate the right OCF_ROOT_DIR
  in cross compiling env.

* Add "rm -rf ${D}${localstatedir}/lib/heartbeat" to
  fix below error:
  Error: Transaction check error:
  file /var/lib/heartbeat/cores conflicts between attempted installs of pacemaker-1.1.16-r0.core2_64 and cluster-glue-1.0.12-r0.core2_64

Signed-off-by: Mingli Yu <Mingli.Yuwindriver.com>
Signed-off-by: Adrian Dudau <adrian.dudauenea.com>