src/meta-openembedded:liboauth: Add missing OpenSSL build dependency
Fixes:

| liboauth-1.0.3/src/hash.c:363:26: fatal error: openssl/hmac.h:
|  No such file or directory

Signed-off-by: Jacob Kroon <jacob.kroonmikrodidakt.se>
Signed-off-by: Martin Jansa <Martin.Jansagmail.com>