src/poky:gcr: add opengl to REQUIRED_DISTRO_FEATURES
Fixes:
  $ bitbake gcr
  ERROR: Nothing PROVIDES 'gtk4' (but /build/layers/oe-core/meta/recipes-gnome/gcr/gcr_4.0.0.bb DEPENDS on or otherwise requires it)
gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'gcr' has no buildable providers.
  Missing or unbuildable dependency chain was: ['gcr', 'gtk4']

(From OE-Core rev: 47b0bf034796b6f159110dae363fe11eab3eab08)

Signed-off-by: Mingli Yu <mingli.yuwindriver.com>
Signed-off-by: Alexandre Belloni <alexandre.bellonibootlin.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>