src/poky:qemu-native: only depends on libxext-native when x11
Fixed when build without x11 in DISTRO_FEATURES:
ERROR: libxext-native was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

(From OE-Core rev: 012c7fbe0a21e469db5112873e778ff7c3b17237)

Signed-off-by: Robert Yang <liezhi.yangwindriver.com>
Signed-off-by: Richard Purdie <richard.purdielinuxfoundation.org>