src/meta-openembedded:gnome-common: add PACKAGECONFIG for autoconf-archive
Add PACKAGECONFIG for autoconf-archive. Default to enable it to avoid
m4 file conflicts between gnome-common and autoconf-archive.

e.g.
IMAGE_INSTALL_append = " gnome-common autoconf-archive-dev"
bitbake <image>

We enable autoconf-archive PACKAGECONFIG to avoid the following error.

Error: Transaction check error:
  file /usr/share/aclocal/ax_check_enable_debug.m4 conflicts between attempted installs of gnome-common-3.18.0-r0.noarch and autoconf-archive-dev-2016.09.16-r0.core2_64
  file /usr/share/aclocal/ax_code_coverage.m4 conflicts between attempted installs of gnome-common-3.18.0-r0.noarch and autoconf-archive-dev-2016.09.16-r0.core2_64

Signed-off-by: Chen Qi <Qi.Chenwindriver.com>
Signed-off-by: Armin Kuster <akuster808gmail.com>